/// ORACLY Tarot catalogue — structured meanings, TR/EN/RU. No UI.
library;

import '../../../../core/l10n/l10n_triple.dart';
import '../oracly_tarot_card.dart';
import '../oracly_tarot_enums.dart';
import '../oracly_tarot_keywords.dart';
import '../oracly_tarot_meanings.dart';
import '../oracly_tarot_relations.dart';

const kOraclyTarotMajor11to21 = <OraclyTarotCard>[
  OraclyTarotCard(
    id: 'major_11',
    number: 11,
    arcana: OraclyTarotArcana.major,
    suit: OraclyTarotSuit.none,
    name: L10nTriple('Adalet', 'Justice', 'Справедливость'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['ölçü', 'dürüstlük', 'denge'],
      en: ['measure', 'honesty', 'balance'],
      ru: ['мера', 'честность', 'равновесие'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['kaçınma', 'yargı', 'çarpıtma'],
      en: ['evasion', 'verdict', 'distort'],
      ru: ['уклонение', 'приговор', 'искажение'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Terazinin sakin duruşu; her yanın görünmesi.', 'The calm stance of the scales; each side being seen.', 'Спокойная поза весов; каждая сторона видна.'),
      loveMeaning: L10nTriple('İlişkide adil bir konuşma gerekebilir; haklı çıkmak ayrı bir arzudur.', 'A fair conversation may be needed in a bond; being right is a separate wish.', 'В связи может быть нужен честный разговор; быть правым — отдельное желание.'),
      careerMeaning: L10nTriple('Karar, sözleşme veya sorumluluk netleşebilir.', 'A decision, contract, or duty may become clearer.', 'Решение, договор или обязанность могут проясниться.'),
      moneyMeaning: L10nTriple('Hesap ve denge, bulanık harcamayı sakinleştirebilir.', 'Accounts and proportion may quiet muddy spending.', 'Счёт и мера могут успокоить мутные траты.'),
      personalMeaning: L10nTriple('Kendine karşı dürüstlük, başkasını yargılamaktan daha ağır olabilir.', 'Honesty toward oneself may weigh more than judging another.', 'Честность к себе может быть тяжелее суда над другим.'),
      challengeMeaning: L10nTriple('Adalet, soğuk bir hüküm giysisine bürünebilir.', 'Justice may put on the coat of a cold verdict.', 'Справедливость может надеть плащ холодного приговора.'),
      guidanceMeaning: L10nTriple('Ölç; cezalandırma.', 'Measure; do not punish.', 'Меруй; не карай.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha duru bir hesaplaşma — tehdit değil.', 'A possible climate: a clearer reckoning — not a threat.', 'Возможный климат: более ясный разбор — не угроза.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_20', 'swords_11', 'major_06'],
      note: L10nTriple('Mahkeme çağrı, Kılıç Habercisi dil, Aşıklar değer seçimidir.', 'Judgement is a call; Page of Swords speech; Lovers a value choice.', 'Суд — зов; Паж Мечей — речь; Влюблённые — выбор ценности.'),
    ),
    visualAsset: 'assets/tarot/cards/major/11_justice.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'major_12',
    number: 12,
    arcana: OraclyTarotArcana.major,
    suit: OraclyTarotSuit.none,
    name: L10nTriple('Asılan Adam', 'The Hanged Man', 'Повешенный'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['askı', 'perspektif', 'teslim'],
      en: ['suspension', 'angle', 'yielding'],
      ru: ['подвешенность', 'ракурс', 'уступка'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['kurban', 'inat', 'boşa bekleyiş'],
      en: ['martyr', 'stubbornness', 'empty wait'],
      ru: ['жертва', 'упрямство', 'пустое ожидание'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Ters çevrilmiş bir bakış; acele etmeyen bir ara.', 'An inverted gaze; an interval that does not hurry.', 'Перевёрнутый взгляд; промежуток без спешки.'),
      loveMeaning: L10nTriple('İlişkide durak, yeni bir açı verebilir; kendini feda etmek ayrı bir hikâyedir.', 'A pause in a bond may offer a new angle; self-sacrifice is a different story.', 'Пауза в связи может дать новый ракурс; самопожертвование — другая история.'),
      careerMeaning: L10nTriple('Beklemek strateji olabilir; felç olmak değil.', 'Waiting may be strategy; it is not the same as paralysis.', 'Ожидание может быть стратегией; это не паралич.'),
      moneyMeaning: L10nTriple('Erteleme bir ferahlık da bir kaçış da olabilir; hangisi olduğunu sormak gerekir.', 'Delay may be relief or escape; it is worth asking which.', 'Отсрочка может быть облегчением или бегством; стоит спросить, чем именно.'),
      personalMeaning: L10nTriple('Kontrolü bir an bırakmak, yeni bir anlam açabilir.', 'Releasing control for a moment may open another meaning.', 'Отпустить контроль на миг может открыть другой смысл.'),
      challengeMeaning: L10nTriple('Askıda kalmak, hayatın yerine geçebilir.', 'Hanging in wait may replace living.', 'Висение в ожидании может заменить жизнь.'),
      guidanceMeaning: L10nTriple('Açıyı değiştir; kendini cezalandırma.', 'Change the angle; do not punish yourself.', 'Смени ракурс; не наказывай себя.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha yavaş, daha tersine çevrilmiş bir idrak.', 'A possible climate: slower, inverted understanding.', 'Возможный климат: более медленное, перевёрнутое понимание.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_13', 'cups_12', 'swords_12'],
      note: L10nTriple('Ölüm ardından boşluk; Kupa ve Kılıç Şövalyeleri hareketin iki yüzüdür.', 'Death follows with space; Knights of Cups and Swords are two faces of motion.', 'За Смертью — пространство; Рыцари Кубков и Мечей — два лица движения.'),
    ),
    visualAsset: 'assets/tarot/cards/major/12_hanged_man.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'major_13',
    number: 13,
    arcana: OraclyTarotArcana.major,
    suit: OraclyTarotSuit.none,
    name: L10nTriple('Ölüm', 'Death', 'Смерть'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['bitiş', 'boşalma', 'yeniden diziliş'],
      en: ['ending', 'clearing', 're-ordering'],
      ru: ['конец', 'очищение', 'перестановка'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['tutunma', 'inkâr', 'korku'],
      en: ['clinging', 'denial', 'dread'],
      ru: ['цепляние', 'отрицание', 'страх'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Bir biçimin sonu; yer açan bir kapanış. Bedenin sonu değildir.', 'The end of a form; a closing that makes room. Not the end of a body.', 'Конец формы; закрытие, которое освобождает место. Не конец тела.'),
      loveMeaning: L10nTriple('Bir bağın evresi kapanabilir; bu, nefret veya kehanet değildir.', 'A phase of a bond may close; this is not hatred or a prophecy.', 'Фаза связи может закрыться; это не ненависть и не пророчество.'),
      careerMeaning: L10nTriple('Bir rol veya proje tamamlanmak isteyebilir.', 'A role or project may want completion.', 'Роль или проект могут хотеть завершения.'),
      moneyMeaning: L10nTriple('Eski bir düzen çözülebilir; yeni düzen henüz vaat değildir.', 'An old arrangement may dissolve; the new one is not yet a promise.', 'Старый порядок может распасться; новый ещё не обещание.'),
      personalMeaning: L10nTriple('Eski bir kimlik ağır gelebilir; bırakmak yas da ister.', 'An old identity may feel heavy; letting go also asks for mourning.', 'Старая личность может стать тяжёлой; отпускание просит и траура.'),
      challengeMeaning: L10nTriple('Korku, bitişi felaket gibi okuyabilir.', 'Fear may read an ending as catastrophe.', 'Страх может прочесть конец как катастрофу.'),
      guidanceMeaning: L10nTriple('Bitene teşekkür et; cesedi taşıma.', 'Thank what is ending; do not carry the corpse.', 'Поблагодари то, что кончается; не неси труп.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: bir boşluk — içi henüz doldurulmamış.', 'A possible climate: a vacancy — not yet filled.', 'Возможный климат: пустота — ещё не заполненная.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_16', 'major_20', 'cups_05'],
      note: L10nTriple('Kule sarsar, Mahkeme çağırır, Kupa Beşlisi kaybın yasını taşır.', 'The Tower shakes; Judgement calls; Five of Cups holds mourning of loss.', 'Башня трясёт; Суд зовёт; Пятёрка Кубков держит траур потери.'),
    ),
    visualAsset: 'assets/tarot/cards/major/13_death.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'major_14',
    number: 14,
    arcana: OraclyTarotArcana.major,
    suit: OraclyTarotSuit.none,
    name: L10nTriple('Denge', 'Temperance', 'Умеренность'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['harman', 'tempo', 'orta yol'],
      en: ['blend', 'pacing', 'middle'],
      ru: ['смешение', 'темп', 'середина'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['aşırılık', 'acele', 'kopukluk'],
      en: ['excess', 'rush', 'disconnect'],
      ru: ['избыток', 'спешка', 'разрыв'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('İki akışın sabırla karışması.', 'Two streams mixed with patience.', 'Два потока, смешанные с терпением.'),
      loveMeaning: L10nTriple('İlişkide doz ve ritim konuşulabilir; ya hep ya hiç yorucudur.', 'Dose and rhythm may be spoken in a bond; all-or-nothing tires.', 'В связи могут говорить о мере и ритме; всё или ничего утомляет.'),
      careerMeaning: L10nTriple('İşbirliği ve tempo ayarı mümkün görünür.', 'Collaboration and a tempo adjustment may be possible.', 'Возможны сотрудничество и настройка темпа.'),
      moneyMeaning: L10nTriple('Orta yol bütçe, savurganlık ile kısma arasında durabilir.', 'A middle budget may sit between waste and austerity.', 'Средний бюджет может стоять между растратой и урезкой.'),
      personalMeaning: L10nTriple('Zıt yanlar aynı kapta durmayı öğrenebilir.', 'Opposite sides may learn to rest in one vessel.', 'Противоположные стороны могут учиться быть в одном сосуде.'),
      challengeMeaning: L10nTriple('Denge, kararsızlık veya kendini yok sayma olabilir.', 'Balance may become indecision or self-erasure.', 'Баланс может стать нерешительностью или самозабвением.'),
      guidanceMeaning: L10nTriple('Biraz şunu, biraz bunu; hepsini bir anda değil.', 'A little of this, a little of that; not everything at once.', 'Немного того, немного этого; не всё сразу.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha karışık, daha yumuşak bir ritim.', 'A possible climate: a more mixed, softer rhythm.', 'Возможный климат: более смешанный, более мягкий ритм.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_08', 'cups_14', 'pentacles_14'],
      note: L10nTriple('Güç yumuşaklık, Kupa ve Tılsım Kralları ölçü ve maddeyi taşır.', 'Strength is gentleness; Kings of Cups and Pentacles hold measure and matter.', 'Сила — мягкость; Короли Кубков и Пентаклей держат меру и материю.'),
    ),
    visualAsset: 'assets/tarot/cards/major/14_temperance.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'major_15',
    number: 15,
    arcana: OraclyTarotArcana.major,
    suit: OraclyTarotSuit.none,
    name: L10nTriple('Şeytan', 'The Devil', 'Дьявол'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['bağlanma', 'gölge', 'döngü'],
      en: ['attachment', 'shadow', 'loop'],
      ru: ['привязанность', 'тень', 'петля'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['inkâr', 'utanç', 'suçlama'],
      en: ['denial', 'shame', 'blame'],
      ru: ['отрицание', 'стыд', 'вина'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Seçilmiş gibi duran bir zincir; henüz bakılmamış bir arzu.', 'A chain that looks chosen; a desire not yet looked at.', 'Цепь, похожая на выбор; желание, на которое ещё не взглянули.'),
      loveMeaning: L10nTriple('Bağda bağımlılık veya oyun belirebilir; fark etmek ilk adımdır, mahkûm etmek değil.', 'Attachment or a game may appear in a bond; noticing is a first step, not a sentence.', 'В связи могут явиться зависимость или игра; заметить — первый шаг, не приговор.'),
      careerMeaning: L10nTriple('Tükenene kadar süren bir tempo veya toksik bir düzen fark edilebilir.', 'A pace that runs to depletion, or a toxic arrangement, may be noticed.', 'Может быть замечен темп до истощения или токсичный порядок.'),
      moneyMeaning: L10nTriple('Alışkanlık harcaması veya statü oyunu görülebilir.', 'Habit spending or a status game may be seen.', 'Могут быть видны привычные траты или игра статуса.'),
      personalMeaning: L10nTriple('Gölge, utandırılmadan bakılmayı isteyebilir.', 'The shadow may want to be looked at without being shamed.', 'Тень может хотеть взгляда без стыда.'),
      challengeMeaning: L10nTriple('Zincir, \'ben böyleyim\' hikâyesine kilitlenebilir.', 'The chain may lock into an \'this is just who I am\' story.', 'Цепь может замкнуться в истории «я такой».'),
      guidanceMeaning: L10nTriple('Bağı isimlendir; henüz kırmak zorunda değilsin, görmek yeter bir adım.', 'Name the bond; you do not have to break it yet — seeing is already a step.', 'Назови связь; ещё не обязательно рвать — увидеть уже шаг.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: bir alışkanlığın daha görünür olması.', 'A possible climate: a habit becoming more visible.', 'Возможный климат: привычка становится виднее.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_08', 'major_16', 'pentacles_05'],
      note: L10nTriple('Güç merhamet, Kule çatlak, Tılsım Beşlisi yoksunluk izidir.', 'Strength is mercy; the Tower a crack; Five of Pentacles a trace of lack.', 'Сила — милость; Башня — трещина; Пятёрка Пентаклей — след нехватки.'),
    ),
    visualAsset: 'assets/tarot/cards/major/15_devil.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'major_16',
    number: 16,
    arcana: OraclyTarotArcana.major,
    suit: OraclyTarotSuit.none,
    name: L10nTriple('Kule', 'The Tower', 'Башня'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['çatlak', 'sarsıntı', 'açığa çıkış'],
      en: ['crack', 'shake', 'uncovering'],
      ru: ['трещина', 'сотрясение', 'обнажение'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['inkâr', 'erteleme', 'enkaz korkusu'],
      en: ['denial', 'delay', 'wreck-fear'],
      ru: ['отрицание', 'отсрочка', 'страх обломков'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Sahte bir yapının sarsılması; ışığın içeri sızması.', 'A false structure shaking; light leaking in.', 'Ложный строй трясётся; свет просачивается внутрь.'),
      loveMeaning: L10nTriple('İlişkide bir gerçek görünür olabilir; bu, son kehaneti değildir.', 'A truth in a bond may become visible; this is not a prophecy of the end.', 'В связи может стать видна правда; это не пророчество конца.'),
      careerMeaning: L10nTriple('Bir plan veya unvan sarsılabilir; enkazın yanında neyin durduğuna bakılır.', 'A plan or title may shake; one looks at what still stands beside the rubble.', 'План или титул могут тряхнуть; смотрят, что ещё стоит у обломков.'),
      moneyMeaning: L10nTriple('Beklenmedik bir kırılma fark edilebilir; panik tek yanıt olmak zorunda değildir.', 'An unexpected break may be noticed; panic need not be the only reply.', 'Может быть замечен неожиданный разрыв; паника не обязана быть единственным ответом.'),
      personalMeaning: L10nTriple('Ego kalesi çatladığında nefes de girebilir.', 'When the ego-fortress cracks, breath can enter too.', 'Когда крепость эго трескается, может войти и дыхание.'),
      challengeMeaning: L10nTriple('Sarsıntı, her şey bitti hikâyesine bağlanabilir.', 'The shake may be bound into a story that everything is over.', 'Сотрясение может стать историей, что всё кончено.'),
      guidanceMeaning: L10nTriple('Yıkılanı say; ayakta kalanı da say.', 'Count what fell; count what still stands.', 'Сочти упавшее; сочти и то, что ещё стоит.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha çıplak bir gerçeklik — felaket ilanı değil.', 'A possible climate: a barer reality — not a declaration of disaster.', 'Возможный климат: более голая реальность — не объявление бедствия.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_13', 'major_17', 'swords_10'],
      note: L10nTriple('Ölüm kapatır, Yıldız sakinleşir, Kılıç Onu zihinsel yük izidir.', 'Death closes; the Star calms; Ten of Swords is a trace of mental load.', 'Смерть закрывает; Звезда успокаивает; Десятка Мечей — след умственной ноши.'),
    ),
    visualAsset: 'assets/tarot/cards/major/16_tower.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'major_17',
    number: 17,
    arcana: OraclyTarotArcana.major,
    suit: OraclyTarotSuit.none,
    name: L10nTriple('Yıldız', 'The Star', 'Звезда'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['umut', 'arınma', 'sakin ışık'],
      en: ['hope', 'rinsing', 'quiet light'],
      ru: ['надежда', 'омовение', 'тихий свет'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['sönükleşme', 'erteleme', 'inanmama'],
      en: ['dimming', 'delay', 'disbelief'],
      ru: ['угасание', 'отсрочка', 'неверие'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Fırtınadan sonra duru bir ışık; vaat değil, nefes.', 'Clear light after weather; not a vow, a breath.', 'Чистый свет после погоды; не обет, дыхание.'),
      loveMeaning: L10nTriple('İlişkide yumuşak bir onarım mümkün görünebilir; acele mutluluk dayatması sakin değildir.', 'Gentle repair in a bond may look possible; forcing quick happiness is not calm.', 'В связи возможен мягкий ремонт; навязывать быстрое счастье не спокойно.'),
      careerMeaning: L10nTriple('Uzun vadeli bir yön, gürültüsüzce belirebilir.', 'A longer heading may appear without noise.', 'Более дальний курс может явиться без шума.'),
      moneyMeaning: L10nTriple('Sade bir umut, abartılı kazanç hayalinden daha duru durabilir.', 'A simple hope may sit more clearly than a inflated gain-fantasy.', 'Простая надежда может быть яснее раздутой фантазии выигрыша.'),
      personalMeaning: L10nTriple('İçeride yıkanmış bir açıklık hissedilebilir.', 'A rinsed openness may be felt inside.', 'Внутри может ощущаться промытая открытость.'),
      challengeMeaning: L10nTriple('Umut, eylemden kopuk bir rüyaya kayabilir.', 'Hope may slide into a dream unhooked from action.', 'Надежда может стать сном без действия.'),
      guidanceMeaning: L10nTriple('Işığı küçük tut; sahne ışığı yapmak zorunda değilsin.', 'Keep the light small; it does not have to be a spotlight.', 'Держи свет малым; ему не обязательно быть прожектором.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha sakin bir güven — garanti değil.', 'A possible climate: quieter trust — not a guarantee.', 'Возможный климат: более тихое доверие — не гарантия.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_00', 'major_19', 'cups_09'],
      note: L10nTriple('Deli eşik, Güneş görünürlük, Kupa Dokuzu iç doyum izidir.', 'The Fool is threshold; the Sun visibility; Nine of Cups inner enough-ness.', 'Шут — порог; Солнце — видимость; Девятка Кубков — внутренняя достаточность.'),
    ),
    visualAsset: 'assets/tarot/cards/major/17_star.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'major_18',
    number: 18,
    arcana: OraclyTarotArcana.major,
    suit: OraclyTarotSuit.none,
    name: L10nTriple('Ay', 'The Moon', 'Луна'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['belirsizlik', 'rüya', 'gölge yol'],
      en: ['unclearness', 'dream', 'shadow path'],
      ru: ['неясность', 'сон', 'теневая тропа'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['korku', 'yanılsama', 'şüphe fırtınası'],
      en: ['fear', 'illusion', 'storm of doubt'],
      ru: ['страх', 'иллюзия', 'буря сомнения'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Net olmayan bir yol; ay ışığında seçilen adım.', 'A path not fully clear; a step chosen in moonlight.', 'Путь не до конца ясный; шаг, выбранный при луне.'),
      loveMeaning: L10nTriple('Duygular bulanık olabilir; her gölge ihanet demek değildir.', 'Feelings may be cloudy; not every shadow means betrayal.', 'Чувства могут быть мутными; не каждая тень — измена.'),
      careerMeaning: L10nTriple('Belirsiz bir ortamda sezgi ile doğrulama birlikte yürüyebilir.', 'In an unclear setting, sensing and checking may walk together.', 'В неясной обстановке чутьё и проверка могут идти вместе.'),
      moneyMeaning: L10nTriple('Bulanık bilgiyle karar vermek yorucu olabilir; beklemek de bir seçenektir.', 'Deciding on cloudy information may tire; waiting is also an option.', 'Решать по мутным сведениям утомляет; ждать — тоже выбор.'),
      personalMeaning: L10nTriple('Korku, gerçekten büyük olmayabilir; yine de hissedilir.', 'Fear may not be as large as it feels; it is still felt.', 'Страх может быть не так велик, как кажется; его всё же чувствуют.'),
      challengeMeaning: L10nTriple('Belirsizlik, her şeyi tehdit gibi okumaya kayabilir.', 'Unclearness may slide into reading everything as threat.', 'Неясность может стать чтением всего как угрозы.'),
      guidanceMeaning: L10nTriple('Yavaş yürü; her sese inanmak zorunda değilsin.', 'Walk slowly; you do not have to believe every sound.', 'Иди медленно; не обязательно верить каждому звуку.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha sisli bir ara — sonsuza dek sürecek diye bir iddia yok.', 'A possible climate: a foggier interval — no claim that it lasts forever.', 'Возможный климат: более туманный промежуток — нет утверждения, что он вечен.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_02', 'major_19', 'swords_07'],
      note: L10nTriple('Başrahibe giz, Güneş açıklık, Kılıç Yedilisi kaçış izidir.', 'Priestess is the hidden; the Sun the open; Seven of Swords a trace of slipping away.', 'Жрица — скрытое; Солнце — открытое; Семёрка Мечей — след ускользания.'),
    ),
    visualAsset: 'assets/tarot/cards/major/18_moon.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'major_19',
    number: 19,
    arcana: OraclyTarotArcana.major,
    suit: OraclyTarotSuit.none,
    name: L10nTriple('Güneş', 'The Sun', 'Солнце'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['aydınlık', 'görünürlük', 'canlılık'],
      en: ['clarity', 'visibility', 'aliveness'],
      ru: ['ясность', 'видимость', 'живость'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['gösteriş', 'yanılsama neşe', 'körlük'],
      en: ['display', 'false cheer', 'blindness'],
      ru: ['показ', 'ложная радость', 'слепота'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Gölgesiz kalan bir açıklık; ısının paylaşılması.', 'An openness left without shade; warmth being shared.', 'Открытость без тени; тепло, которым делятся.'),
      loveMeaning: L10nTriple('İlişkide neşe ve sadelik belirebilir; sahne neşesi ayrıdır.', 'Joy and simplicity may appear in a bond; staged cheer is another thing.', 'В связи могут явиться радость и простота; сценическая весёлость — иное.'),
      careerMeaning: L10nTriple('Emeğin görünür olması mümkün görünür.', 'Work becoming visible may be possible.', 'Возможно, труд станет видимым.'),
      moneyMeaning: L10nTriple('Daha duru bir bolluk hissi gelebilir; şişkin vaat değildir.', 'A clearer sense of enough may arrive; it is not an inflated promise.', 'Может прийти более ясное чувство достаточности; это не раздутое обещание.'),
      personalMeaning: L10nTriple('Kendini gizlemeden durmak hafifleyebilir.', 'Standing without hiding oneself may feel lighter.', 'Стоять, не прячась, может стать легче.'),
      challengeMeaning: L10nTriple('Işık, başkasının gölgesini yok saymaya kayabilir.', 'Light may slide into ignoring another’s shade.', 'Свет может начать не замечать чужую тень.'),
      guidanceMeaning: L10nTriple('Parla; yakma.', 'Shine; do not scorch.', 'Свети; не обжигай.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha görünür, daha sıcak bir ara.', 'A possible climate: a more visible, warmer interval.', 'Возможный климат: более видимый, более тёплый промежуток.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_17', 'wands_03', 'cups_06'],
      note: L10nTriple('Yıldız sakin umut, Değnek Üçlüsü büyüme, Kupa Altılısı hatırlanan bağdır.', 'The Star is quiet hope; Three of Wands growth; Six of Cups a remembered bond.', 'Звезда — тихая надежда; Тройка Жезлов — рост; Шестёрка Кубков — вспомненная связь.'),
    ),
    visualAsset: 'assets/tarot/cards/major/19_sun.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'major_20',
    number: 20,
    arcana: OraclyTarotArcana.major,
    suit: OraclyTarotSuit.none,
    name: L10nTriple('Mahkeme', 'Judgement', 'Суд'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['çağrı', 'gözden geçirme', 'uyanış'],
      en: ['call', 'review', 'waking'],
      ru: ['зов', 'пересмотр', 'пробуждение'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['kaçınma', 'ağır yargı', 'erteleme'],
      en: ['avoidance', 'harsh verdict', 'delay'],
      ru: ['избегание', 'суровый приговор', 'отсрочка'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('İsmiyle çağrılmak; geçmişi dinleyip ayağa kalkmak.', 'Being called by name; hearing the past and standing up.', 'Зов по имени; услышать прошлое и встать.'),
      loveMeaning: L10nTriple('Eski bir bağ veya söz yeniden duyulabilir; bu, geri dön kehaneti değildir.', 'An old bond or word may be heard again; this is not a prophecy of return.', 'Старая связь или слово могут быть услышаны снова; это не пророчество возврата.'),
      careerMeaning: L10nTriple('Bir çağrı, meslek veya hesaplaşma konuşulabilir.', 'A calling, a vocation, or a reckoning may be spoken.', 'Могут говорить о призвании, ремесле или разборе.'),
      moneyMeaning: L10nTriple('Eski bir hesap yeniden açılabilir; utanç tek dil olmak zorunda değildir.', 'An old account may reopen; shame need not be the only language.', 'Старый счёт может открыться снова; стыд не обязан быть единственным языком.'),
      personalMeaning: L10nTriple('Kendini yeniden adlandırmak mümkün görünebilir.', 'Renaming oneself may look possible.', 'Переименовать себя может казаться возможным.'),
      challengeMeaning: L10nTriple('Çağrı, acımasız bir mahkemeye dönüşebilir.', 'The call may become a merciless court.', 'Зов может стать беспощадным судом.'),
      guidanceMeaning: L10nTriple('Duy; hemen hüküm verme.', 'Hear; do not pass sentence at once.', 'Услышь; не выноси приговор сразу.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: bir uyanış aralığı — yeni hayat garantisi değil.', 'A possible climate: an interval of waking — not a guarantee of a new life.', 'Возможный климат: промежуток пробуждения — не гарантия новой жизни.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_11', 'major_13', 'major_21'],
      note: L10nTriple('Adalet ölçü, Ölüm kapanış, Dünya tamamlanmadır.', 'Justice is measure; Death a closing; the World completion.', 'Справедливость — мера; Смерть — закрытие; Мир — завершение.'),
    ),
    visualAsset: 'assets/tarot/cards/major/20_judgement.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'major_21',
    number: 21,
    arcana: OraclyTarotArcana.major,
    suit: OraclyTarotSuit.none,
    name: L10nTriple('Dünya', 'The World', 'Мир'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['tamamlanma', 'bütünlük', 'eşik sonu'],
      en: ['completion', 'wholeness', 'end of a threshold'],
      ru: ['завершение', 'целостность', 'конец порога'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['eksik iş', 'dağılma', 'kapanmama'],
      en: ['unfinished work', 'scatter', 'unclosed'],
      ru: ['недоделанное', 'рассев', 'незакрытость'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Bir çemberin kapanışı; dansın sakin hali.', 'A circle closing; the calm form of a dance.', 'Круг закрывается; спокойный вид танца.'),
      loveMeaning: L10nTriple('Bir bağ olgun bir duruşa gelebilir; sonsuzluk iddiası taşımaz.', 'A bond may arrive at a mature stance; it carries no claim of forever.', 'Связь может прийти к зрелой позе; в ней нет утверждения навсегда.'),
      careerMeaning: L10nTriple('Bir evre tamamlanmak isteyebilir; alkış şart değildir.', 'A phase of work may want completion; applause is not required.', 'Фаза дела может хотеть завершения; аплодисменты не обязательны.'),
      moneyMeaning: L10nTriple('Bir döngünün hesabı kapanabilir; yeni döngü henüz yazılmamıştır.', 'An account of a cycle may close; the next cycle is not yet written.', 'Счёт цикла может закрыться; следующий цикл ещё не написан.'),
      personalMeaning: L10nTriple('Parçaların bir arada durduğu bir an hissedilebilir.', 'A moment may be felt when the pieces stand together.', 'Может быть миг, когда части стоят вместе.'),
      challengeMeaning: L10nTriple('Tamamlanma, durağanlığa veya yeni bir şeye korkuya kayabilir.', 'Completion may slide into stagnation or fear of the next thing.', 'Завершение может стать застоем или страхом следующего.'),
      guidanceMeaning: L10nTriple('Çemberi kapat; hemen yeni bir circusa atlama.', 'Close the circle; do not leap into a new circus at once.', 'Закрой круг; не прыгай сразу в новый цирк.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: bir eşiğin sonu ve henüz isimsiz bir sonrası.', 'A possible climate: the end of a threshold and a not-yet-named after.', 'Возможный климат: конец порога и ещё не названное после.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_00', 'major_10', 'major_17'],
      note: L10nTriple('Deli yeni eşik, Çark dönüş, Yıldız sakin ışıktır.', 'The Fool is a new threshold; the Wheel a turn; the Star quiet light.', 'Шут — новый порог; Колесо — поворот; Звезда — тихий свет.'),
    ),
    visualAsset: 'assets/tarot/cards/major/21_world.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
];
