/// ORACLY Tarot catalogue — structured meanings, TR/EN/RU. No UI.
library;

import '../../../../core/l10n/l10n_triple.dart';
import '../oracly_tarot_card.dart';
import '../oracly_tarot_enums.dart';
import '../oracly_tarot_keywords.dart';
import '../oracly_tarot_meanings.dart';
import '../oracly_tarot_relations.dart';

const kOraclyTarotSwords = <OraclyTarotCard>[
  OraclyTarotCard(
    id: 'swords_01',
    number: 1,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.swords,
    name: L10nTriple('Kılıç Ası', 'Ace of Swords', 'Туз Мечей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['keskinlik', 'fikir', 'hava'],
      en: ['edge', 'idea', 'air'],
      ru: ['остриё', 'идея', 'воздух'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['sert söz', 'dağınık zihin', 'kesmek için kesmek'],
      en: ['harsh word', 'scattered mind', 'cutting to cut'],
      ru: ['жёсткое слово', 'рассеянный ум', 'резать ради резанья'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('İlk keskinlik; henüz savaş değil.', 'A first edge; not yet a war.', 'Первое остриё; ещё не война.'),
      loveMeaning: L10nTriple('Bağda net bir cümle gerekebilir.', 'A clear sentence may be needed in a bond.', 'В связи может быть нужна ясная фраза.'),
      careerMeaning: L10nTriple('İş te yeni bir fikir belirebilir.', 'A new idea at work may appear.', 'На работе может явиться новая идея.'),
      moneyMeaning: L10nTriple('Keskin bir karar kaynakları da ayırabilir.', 'A sharp decision may also divide means.', 'Острое решение может разделить и средства.'),
      personalMeaning: L10nTriple('İçeride duru bir düşünce uyanabilir.', 'A clear thought may wake inside.', 'Внутри может проснуться ясная мысль.'),
      challengeMeaning: L10nTriple('Keskinlik, yaralamaya kayabilir.', 'Edge may slide into wounding.', 'Остриё может стать ранением.'),
      guidanceMeaning: L10nTriple('Net ol; keserek konuşma.', 'Be clear; do not speak by cutting.', 'Будь ясен; не говори режа.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha duru bir fikir.', 'A possible climate: a clearer idea.', 'Возможный климат: более ясная идея.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['wands_01', 'major_01', 'swords_02'],
      note: L10nTriple('Değnek Ası kıvılcım, Büyücü el, Kılıç İkilisi duruştur.', 'Ace of Wands spark; Magician hand; Two of Swords stance.', 'Туз Жезлов — искра; Маг — рука; Двойка Мечей — поза.'),
    ),
    visualAsset: 'assets/tarot/cards/swords/01_ace.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'swords_02',
    number: 2,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.swords,
    name: L10nTriple('Kılıç İkilisi', 'Two of Swords', 'Двойка Мечей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['körü körüne duruş', 'iki düşünce', 'kapalı göz'],
      en: ['stalemate', 'two thoughts', 'closed eyes'],
      ru: ['тупик', 'две мысли', 'закрытые глаза'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['karar kaçışı', 'inkâr', 'donma'],
      en: ['flight from decision', 'denial', 'freeze'],
      ru: ['бегство от решения', 'отрицание', 'заморозка'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('İki kılıç arasında duran zihin.', 'A mind standing between two swords.', 'Ум, стоящий между двумя мечами.'),
      loveMeaning: L10nTriple('İlişkide bir durak, seçim korkusu olabilir.', 'A pause in a bond may be fear of choosing.', 'Пауза в связи может быть страхом выбора.'),
      careerMeaning: L10nTriple('İş te iki görüş kilitlenebilir.', 'Two views at work may lock.', 'На работе два взгляда могут замкнуться.'),
      moneyMeaning: L10nTriple('Kararsızlık harcamayı da dondurabilir.', 'Indecision may also freeze spending.', 'Нерешительность может заморозить и траты.'),
      personalMeaning: L10nTriple('İçeride görmemek için kapanan göz olabilir.', 'Eyes closed in order not to see may live inside.', 'Внутри могут жить глаза, закрытые чтобы не видеть.'),
      challengeMeaning: L10nTriple('Duruş, sonsuz ertelemeye kayabilir.', 'The stance may slide into endless delay.', 'Поза может стать бесконечной отсрочкой.'),
      guidanceMeaning: L10nTriple('Gözünü aç; henüz vurmak zorunda değilsin.', 'Open your eyes; you do not have to strike yet.', 'Открой глаза; ещё не обязательно бить.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: seçimden önceki kilit.', 'A possible climate: a lock before choosing.', 'Возможный климат: замок до выбора.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_06', 'cups_02', 'wands_02'],
      note: L10nTriple('Aşıklar seçim, Kupa ve Değnek ikilileri bağ ve ufuktur.', 'Lovers choice; Twos of Cups and Wands bond and horizon.', 'Влюблённые — выбор; Двойки Кубков и Жезлов — связь и горизонт.'),
    ),
    visualAsset: 'assets/tarot/cards/swords/02_two.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'swords_03',
    number: 3,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.swords,
    name: L10nTriple('Kılıç Üçlüsü', 'Three of Swords', 'Тройка Мечей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['kırık söz', 'acı netlik', 'kalp kenarı'],
      en: ['broken word', 'painful clarity', 'heart-edge'],
      ru: ['сломанное слово', 'больная ясность', 'край сердца'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['dramatik acı', 'suçlama', 'kapanmama'],
      en: ['dramatic pain', 'blame', 'unclosed'],
      ru: ['драматическая боль', 'вина', 'незакрытость'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Keskin bir üzüntü; tiyatro değildir.', 'A sharp sorrow; it is not theatre.', 'Острая печаль; это не театр.'),
      loveMeaning: L10nTriple('Bağda inciten bir gerçek konuşulabilir.', 'A hurting truth may be spoken in a bond.', 'В связи может быть сказана ранящая правда.'),
      careerMeaning: L10nTriple('İş te hayal kırıklığı belirginleşebilir.', 'Disappointment at work may sharpen.', 'На работе может обостриться разочарование.'),
      moneyMeaning: L10nTriple('Bir kayıp hesabı açılabilir.', 'An account of loss may open.', 'Может открыться счёт потери.'),
      personalMeaning: L10nTriple('İçeride kırık ve hâlâ duru bir yer olabilir.', 'A place both broken and still clear may live inside.', 'Внутри может жить место и сломанное, и всё ещё ясное.'),
      challengeMeaning: L10nTriple('Acı, kimlik olabilir.', 'Pain may become identity.', 'Боль может стать личностью.'),
      guidanceMeaning: L10nTriple('Acıyı adlandır; sahne yapma.', 'Name the pain; do not stage it.', 'Назови боль; не ставь её на сцену.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha çıplak bir üzüntü.', 'A possible climate: barer sorrow.', 'Возможный климат: более голая печаль.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['cups_05', 'major_13', 'swords_05'],
      note: L10nTriple('Kupa Beşlisi yas, Ölüm kapanış, Kılıç Beşlisi çatışmadır.', 'Five of Cups mourning; Death closing; Five of Swords clash.', 'Пятёрка Кубков — траур; Смерть — закрытие; Пятёрка Мечей — спор.'),
    ),
    visualAsset: 'assets/tarot/cards/swords/03_three.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'swords_04',
    number: 4,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.swords,
    name: L10nTriple('Kılıç Dörtlüsü', 'Four of Swords', 'Четвёрка Мечей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['dinlenme', 'zihin molası', 'kın'],
      en: ['rest', 'mind pause', 'sheath'],
      ru: ['отдых', 'пауза ума', 'ножны'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['kaçış uyku', 'erteleme', 'uyuşma'],
      en: ['escape-sleep', 'delay', 'numbness'],
      ru: ['сон-бегство', 'отсрочка', 'онемение'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Kının içindeki kılıç; savaş bitmiş gibi değil, ara.', 'Sword in the sheath; not as if war ended — an interval.', 'Меч в ножнах; не будто война кончилась — промежуток.'),
      loveMeaning: L10nTriple('Bağda sessiz bir ara gerekebilir.', 'A quiet interval may be needed in a bond.', 'В связи может быть нужен тихий промежуток.'),
      careerMeaning: L10nTriple('İş te durup düşünmek sakin duruştur.', 'Stopping to think at work is a calm stance.', 'На работе остановиться и подумать — спокойная поза.'),
      moneyMeaning: L10nTriple('Harcama molası bir nefes olabilir.', 'A pause in spending may be a breath.', 'Пауза в тратах может быть дыханием.'),
      personalMeaning: L10nTriple('İçeride yorgun bir zihin yere yatmak isteyebilir.', 'A tired mind may want to lie down inside.', 'Внутри усталый ум может хотеть лечь.'),
      challengeMeaning: L10nTriple('Mola, hayattan çekilmeye kayabilir.', 'The pause may slide into withdrawing from life.', 'Пауза может стать уходом из жизни.'),
      guidanceMeaning: L10nTriple('Kınına koy; kaybolma.', 'Sheathe; do not disappear.', 'Вложи в ножны; не исчезай.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: zihinsel bir kış uykusu değil, kısa bir kın.', 'A possible climate: not mental hibernation — a brief sheath.', 'Возможный климат: не спячка ума — краткие ножны.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_09', 'cups_04', 'major_12'],
      note: L10nTriple('Ermiş yalnızlık, Kupa Dördü durgunluk, Asılan Adam açıdır.', 'Hermit solitude; Four of Cups stillness; Hanged Man angle.', 'Отшельник — одиночество; Четвёрка Кубков — застой; Повешенный — ракурс.'),
    ),
    visualAsset: 'assets/tarot/cards/swords/04_four.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'swords_05',
    number: 5,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.swords,
    name: L10nTriple('Kılıç Beşlisi', 'Five of Swords', 'Пятёрка Мечей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['boş zafer', 'incitme', 'söz savaşı'],
      en: ['hollow win', 'hurting', 'war of words'],
      ru: ['пустая победа', 'ранение', 'война слов'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['aşağılık', 'intikam', 'yalnız kalma'],
      en: ['humiliation', 'revenge', 'being left'],
      ru: ['унижение', 'месть', 'остаться одному'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Kazanılmış gibi duran bir kesik; neşe yoktur.', 'A cut that looks like winning; there is no joy.', 'Разрез, похожий на победу; радости нет.'),
      loveMeaning: L10nTriple('Bağda incitici bir haklılık belirebilir.', 'A hurting rightness may appear in a bond.', 'В связи может явиться ранящая правота.'),
      careerMeaning: L10nTriple('İş te rekabetin gölgesi görülebilir.', 'The shadow of rivalry at work may be seen.', 'На работе может быть видна тень соперничества.'),
      moneyMeaning: L10nTriple('Kazanç, ilişki maliyetine bağlanabilir.', 'Gain may be bound to a relational cost.', 'Прибыль может быть связана с ценой отношений.'),
      personalMeaning: L10nTriple('İçeride \'ben kazandım\' ve boşluk birlikte durabilir.', '\'I won\' and vacancy may stand together inside.', 'Внутри вместе могут стоять «я выиграл» и пустота.'),
      challengeMeaning: L10nTriple('Zafer, yalnızlığa kayabilir.', 'Winning may slide into aloneness.', 'Победа может стать одиночеством.'),
      guidanceMeaning: L10nTriple('Kılıcı indir; puan sayma.', 'Lower the sword; do not keep score.', 'Опусти меч; не веди счёт.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: sözlerin keskinleştiği bir ara.', 'A possible climate: an interval where words sharpen.', 'Возможный климат: промежуток, где слова острятся.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['wands_05', 'cups_05', 'major_15'],
      note: L10nTriple('Değnek ve Kupa Beşlisi sınav ve yas, Şeytan bağlanmadır.', 'Fives of Wands and Cups trial and mourning; Devil attachment.', 'Пятёрки Жезлов и Кубков — испытание и траур; Дьявол — привязанность.'),
    ),
    visualAsset: 'assets/tarot/cards/swords/05_five.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'swords_06',
    number: 6,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.swords,
    name: L10nTriple('Kılıç Altılısı', 'Six of Swords', 'Шестёрка Мечей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['geçiş', 'sakin su üstü', 'yükü taşıma'],
      en: ['crossing', 'calm water surface', 'carrying the load'],
      ru: ['переход', 'спокойная гладь', 'нести ношу'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['kaçış', 'geçmişi götürme', 'varamama korkusu'],
      en: ['escape', 'carrying the past', 'fear of not arriving'],
      ru: ['бегство', 'нести прошлое', 'страх не прибыть'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Suyun üstünde giden zihin; henüz liman değil.', 'Mind traveling on water; not yet harbor.', 'Ум, идущий по воде; ещё не гавань.'),
      loveMeaning: L10nTriple('Bağda bir geçiş dönemi belirebilir.', 'A crossing period may appear in a bond.', 'В связи может явиться период перехода.'),
      careerMeaning: L10nTriple('İş te yer veya rol değişimi konuşulabilir.', 'A change of place or role at work may be spoken.', 'На работе могут говорить о смене места или роли.'),
      moneyMeaning: L10nTriple('Kaynakları taşıyarak geçmek gerekebilir.', 'Means may need to be carried across.', 'Средства, возможно, нужно нести через переход.'),
      personalMeaning: L10nTriple('İçeride yola çıkan yorgun bir duruluk olabilir.', 'A tired clarity setting out may live inside.', 'Внутри может жить усталая ясность, выходящая в путь.'),
      challengeMeaning: L10nTriple('Geçiş, kaçış olabilir.', 'The crossing may be escape.', 'Переход может быть бегством.'),
      guidanceMeaning: L10nTriple('Taşı; bütün geçmişi tekneye yükleme.', 'Carry; do not load the whole past into the boat.', 'Неси; не грузи всё прошлое в лодку.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha sakin bir geçit.', 'A possible climate: a calmer passage.', 'Возможный климат: более спокойный проход.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['wands_06', 'major_07', 'cups_08'],
      note: L10nTriple('Değnek Altılısı geçiş, Savaş Arabası yön, Kupa Sekizlisi ayrılıştır.', 'Six of Wands crossing; Chariot heading; Eight of Cups leaving.', 'Шестёрка Жезлов — переход; Колесница — курс; Восьмёрка Кубков — уход.'),
    ),
    visualAsset: 'assets/tarot/cards/swords/06_six.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'swords_07',
    number: 7,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.swords,
    name: L10nTriple('Kılıç Yedilisi', 'Seven of Swords', 'Семёрка Мечей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['saklama', 'kayış', 'strateji'],
      en: ['hiding', 'slip', 'strategy'],
      ru: ['укрытие', 'скольжение', 'стратегия'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['hırsızlık hissi', 'güvensizlik', 'yalnız plan'],
      en: ['theft-feeling', 'mistrust', 'lone plan'],
      ru: ['ощущение кражи', 'недоверие', 'одинокий план'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Görünmeden çekilen bir kılıç; yargı değil, iz.', 'A sword drawn unseen; not a verdict — a trace.', 'Меч, извлечённый невидимо; не приговор — след.'),
      loveMeaning: L10nTriple('Bağda saklanan bir söz olabilir.', 'A hidden word may sit in a bond.', 'В связи может сидеть скрытое слово.'),
      careerMeaning: L10nTriple('İş te dolaylı bir hareket fark edilebilir.', 'An indirect move at work may be noticed.', 'На работе может быть замечено косвенное движение.'),
      moneyMeaning: L10nTriple('Kaynakların sessizce kayması görülebilir.', 'Means quietly slipping may be seen.', 'Может быть видно тихое ускользание средств.'),
      personalMeaning: L10nTriple('İçeride gizlenen bir strateji olabilir.', 'A hidden strategy may live inside.', 'Внутри может жить скрытая стратегия.'),
      challengeMeaning: L10nTriple('Kayış, kendine de yalan olabilir.', 'The slip may also be a lie to oneself.', 'Скольжение может быть и ложью себе.'),
      guidanceMeaning: L10nTriple('Gizlediğini gör; hırsız ilan etme.', 'See what is hidden; do not declare a thief.', 'Увидь скрытое; не объявляй вора.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha dolaylı bir zihin.', 'A possible climate: a more indirect mind.', 'Возможный климат: более косвенный ум.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_18', 'cups_07', 'pentacles_07'],
      note: L10nTriple('Ay sis, Kupa Yedilisi hayal, Tılsım Yedilisi bekleyiştir.', 'Moon mist; Seven of Cups dream; Seven of Pentacles waiting.', 'Луна — туман; Семёрка Кубков — мечта; Семёрка Пентаклей — ожидание.'),
    ),
    visualAsset: 'assets/tarot/cards/swords/07_seven.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'swords_08',
    number: 8,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.swords,
    name: L10nTriple('Kılıç Sekizlisi', 'Eight of Swords', 'Восьмёрка Мечей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['sıkışma', 'kendi kılıcı', 'bağlı zihin'],
      en: ['tightness', 'one\'s own sword', 'bound mind'],
      ru: ['теснота', 'свой меч', 'связанный ум'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['kurban hikâyesi', 'hareketsizlik', 'korku ağı'],
      en: ['victim story', 'immobility', 'web of fear'],
      ru: ['история жертвы', 'неподвижность', 'сеть страха'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Kendi düşüncesiyle sarılı zihin.', 'A mind wrapped in its own thought.', 'Ум, обмотанный собственной мыслью.'),
      loveMeaning: L10nTriple('Bağda çıkışsızlık hissedilebilir; kapı yok değildir.', 'No-exit may be felt in a bond; it does not mean there is no door.', 'В связи может ощущаться безвыходность; это не значит, что нет двери.'),
      careerMeaning: L10nTriple('İş te sıkışmış bir rol belirebilir.', 'A stuck role at work may appear.', 'На работе может явиться застрявшая роль.'),
      moneyMeaning: L10nTriple('Kaynak korkusu hareketi dondurabilir.', 'Fear around means may freeze motion.', 'Страх вокруг средств может заморозить движение.'),
      personalMeaning: L10nTriple('İçeride kendi kurduğu bir ağ olabilir.', 'A web one built oneself may live inside.', 'Внутри может жить сеть, которую сплели сами.'),
      challengeMeaning: L10nTriple('Sıkışma, gerçek dış kısıttan ayrı durabilir.', 'Tightness may sit apart from a real outer limit.', 'Теснота может стоять отдельно от реального внешнего предела.'),
      guidanceMeaning: L10nTriple('Bağı fark et; henüz kesmek zorunda değilsin.', 'Notice the bind; you do not have to cut yet.', 'Заметь связь; ещё не обязательно резать.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: zihinsel bir daralma.', 'A possible climate: a mental narrowing.', 'Возможный климат: умственное сужение.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_15', 'wands_08', 'cups_08'],
      note: L10nTriple('Şeytan bağ, Değnek Sekizlisi hız, Kupa Sekizlisi ayrılıştır.', 'Devil bind; Eight of Wands speed; Eight of Cups leaving.', 'Дьявол — связь; Восьмёрка Жезлов — скорость; Восьмёрка Кубков — уход.'),
    ),
    visualAsset: 'assets/tarot/cards/swords/08_eight.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'swords_09',
    number: 9,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.swords,
    name: L10nTriple('Kılıç Dokuzlusu', 'Nine of Swords', 'Девятка Мечей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['gece düşüncesi', 'kaygı', 'zihin yükü'],
      en: ['night thought', 'anxiety', 'mind load'],
      ru: ['ночная мысль', 'тревога', 'ноша ума'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['felaket hayali', 'uykusuzluk kimliği', 'suç'],
      en: ['catastrophe-dream', 'insomnia-identity', 'guilt'],
      ru: ['мечта-катастрофа', 'личность бессонницы', 'вина'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Gece çoğalan kılıçlar; gündüz kadar gerçek olmayabilirler.', 'Swords that multiply at night; they may be less real by day.', 'Мечи, что множатся ночью; днём они могут быть менее реальны.'),
      loveMeaning: L10nTriple('Bağda kaygı konuşmaları artabilir.', 'Anxious talk may increase in a bond.', 'В связи могут усилиться тревожные разговоры.'),
      careerMeaning: L10nTriple('İş te gece zihni işi büyütebilir.', 'The night-mind may enlarge work.', 'Ночной ум может увеличить дело.'),
      moneyMeaning: L10nTriple('Para korkusu, gerçek hesaptan büyük durabilir.', 'Money-fear may sit larger than the real account.', 'Страх денег может быть больше реального счёта.'),
      personalMeaning: L10nTriple('İçeride uyanık duran bir nöbetçi olabilir.', 'A sentry that will not sleep may live inside.', 'Внутри может жить часовой, который не спит.'),
      challengeMeaning: L10nTriple('Kaygı, kehanet gibi giyinebilir.', 'Anxiety may dress as prophecy.', 'Тревога может одеться пророчеством.'),
      guidanceMeaning: L10nTriple('Düşünceyi say; hepsine inanma.', 'Count the thoughts; do not believe them all.', 'Сочти мысли; не верь всем.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha gürültülü bir gece zihni.', 'A possible climate: a noisier night-mind.', 'Возможный климат: более шумный ночной ум.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_18', 'wands_09', 'cups_09'],
      note: L10nTriple('Ay belirsizlik, Değnek Dokuzu nöbet, Kupa Dokuzu yeterliliktir.', 'Moon unclearness; Nine of Wands watch; Nine of Cups enough.', 'Луна — неясность; Девятка Жезлов — дозор; Девятка Кубков — довольно.'),
    ),
    visualAsset: 'assets/tarot/cards/swords/09_nine.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'swords_10',
    number: 10,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.swords,
    name: L10nTriple('Kılıç Onlusu', 'Ten of Swords', 'Десятка Мечей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['bitmiş savaş', 'zihin sonu', 'yerde kılıç'],
      en: ['finished war', 'mind\'s end', 'sword on ground'],
      ru: ['законченная война', 'конец ума', 'меч на земле'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['felaket kimliği', 'kalkmama', 'her şey bitti hikâyesi'],
      en: ['disaster-identity', 'not rising', 'all-is-over story'],
      ru: ['личность бедствия', 'не вставать', 'история «всё кончено»'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Zihinsel bir son; bedenin sonu değildir.', 'A mental ending; not the end of a body.', 'Умственный конец; не конец тела.'),
      loveMeaning: L10nTriple('Bağda tükenmiş bir dil belirebilir.', 'Exhausted language may appear in a bond.', 'В связи может явиться исчерпанный язык.'),
      careerMeaning: L10nTriple('Bir iş fikrinin sonu konuşulabilir.', 'The end of a work idea may be spoken.', 'Могут говорить о конце рабочей идеи.'),
      moneyMeaning: L10nTriple('Bir düzenin zihnen kapandığı hissedilebilir.', 'An arrangement may feel mentally closed.', 'Порядок может ощущаться умственно закрытым.'),
      personalMeaning: L10nTriple('İçeride \'tamam\' diyen yorgun bir yer olabilir.', 'A tired place saying \'enough\' may live inside.', 'Внутри может жить усталое место, говорящее «всё».'),
      challengeMeaning: L10nTriple('Son, sonsuz yenilgi hikâyesine bağlanabilir.', 'The end may bind to a story of endless defeat.', 'Конец может привязаться к истории вечного поражения.'),
      guidanceMeaning: L10nTriple('Yerde yatmayı bitir; henüz dans etmek zorunda değilsin.', 'Finish lying on the ground; you do not have to dance yet.', 'Закончи лежать на земле; ещё не обязательно танцевать.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: bir zihin döngüsünün sonu.', 'A possible climate: the end of a mind-cycle.', 'Возможный климат: конец цикла ума.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_13', 'major_16', 'wands_10'],
      note: L10nTriple('Ölüm biçim sonu, Kule çatlak, Değnek Onu omuz yüküdür.', 'Death end of form; Tower crack; Ten of Wands shoulder-load.', 'Смерть — конец формы; Башня — трещина; Десятка Жезлов — ноша плеч.'),
    ),
    visualAsset: 'assets/tarot/cards/swords/10_ten.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'swords_11',
    number: 11,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.swords,
    name: L10nTriple('Kılıç Habercisi', 'Page of Swords', 'Паж Мечей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['merak', 'keskin öğrenci', 'soru'],
      en: ['curiosity', 'sharp student', 'question'],
      ru: ['любопытство', 'острый ученик', 'вопрос'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['dedikodu', 'acele hüküm', 'dinlememe'],
      en: ['gossip', 'hasty verdict', 'not listening'],
      ru: ['сплетня', 'поспешный приговор', 'неслушание'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Havanın habercisi; yargıç değil.', 'Messenger of air; not a judge.', 'Вестник воздуха; не судья.'),
      loveMeaning: L10nTriple('Bağda soru sormak yumuşak bir kapı olabilir.', 'Asking in a bond may be a gentle door.', 'Спрашивать в связи может быть мягкой дверью.'),
      careerMeaning: L10nTriple('İş te öğrenilecek bir dil belirebilir.', 'A language to be learned at work may appear.', 'На работе может явиться язык, которому учатся.'),
      moneyMeaning: L10nTriple('Bilgi, spekülasyondan ayrı durmalıdır.', 'Information should sit apart from speculation.', 'Сведение должно стоять отдельно от догадки.'),
      personalMeaning: L10nTriple('İçeride keskin ve henüz olgun olmayan bir zihin olabilir.', 'A sharp, not-yet-mature mind may live inside.', 'Внутри может жить острый, ещё не зрелый ум.'),
      challengeMeaning: L10nTriple('Soru, yaralamaya kayabilir.', 'The question may slide into wounding.', 'Вопрос может стать ранением.'),
      guidanceMeaning: L10nTriple('Sor; mahkeme kurma.', 'Ask; do not assemble a court.', 'Спроси; не собирай суд.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha keskin bir merak.', 'A possible climate: sharper curiosity.', 'Возможный климат: более острое любопытство.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_01', 'wands_11', 'cups_11'],
      note: L10nTriple('Büyücü zanaat, Değnek ve Kupa Habercileri ateş ve sudur.', 'Magician craft; Pages of Wands and Cups fire and water.', 'Маг — ремесло; Пажи Жезлов и Кубков — огонь и вода.'),
    ),
    visualAsset: 'assets/tarot/cards/swords/11_page.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'swords_12',
    number: 12,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.swords,
    name: L10nTriple('Kılıç Şövalyesi', 'Knight of Swords', 'Рыцарь Мечей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['hızlı zihin', 'söz atı', 'ileri kesiş'],
      en: ['fast mind', 'word-horse', 'forward cut'],
      ru: ['быстрый ум', 'конь слова', 'разрез вперёд'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['düşüncesiz hız', 'saldırı', 'dinlememe'],
      en: ['thoughtless speed', 'attack', 'not listening'],
      ru: ['бессмысленная скорость', 'атака', 'неслушание'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Düşünceyle yola çıkan kılıç.', 'A sword that takes thought on the road.', 'Меч, берущий мысль в дорогу.'),
      loveMeaning: L10nTriple('Bağda hızlı sözler belirebilir.', 'Quick words may appear in a bond.', 'В связи могут явиться быстрые слова.'),
      careerMeaning: L10nTriple('İş te ani bir hamle mümkün görünür.', 'A sudden move at work may be possible.', 'На работе возможен внезапный ход.'),
      moneyMeaning: L10nTriple('Hızlı karar kaynakları da sarsabilir.', 'A fast decision may also shake means.', 'Быстрое решение может тряхнуть и средства.'),
      personalMeaning: L10nTriple('İçeride duramayan bir argüman olabilir.', 'An argument that cannot wait may live inside.', 'Внутри может жить довод, который не ждёт.'),
      challengeMeaning: L10nTriple('Hız, başkasını ezmeye kayabilir.', 'Speed may slide into crushing another.', 'Скорость может начать давить другого.'),
      guidanceMeaning: L10nTriple('Sür; rastgele kesme.', 'Ride; do not cut at random.', 'Скачи; не режь наугад.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha hızlı bir zihin.', 'A possible climate: a quicker mind.', 'Возможный климат: более быстрый ум.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['wands_12', 'major_07', 'cups_12'],
      note: L10nTriple('Değnek Şövalyesi ateş, Savaş Arabası yön, Kupa Şövalyesi gönül yoludur.', 'Knight of Wands fire; Chariot heading; Knight of Cups heart-road.', 'Рыцарь Жезлов — огонь; Колесница — курс; Рыцарь Кубков — дорога сердца.'),
    ),
    visualAsset: 'assets/tarot/cards/swords/12_knight.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'swords_13',
    number: 13,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.swords,
    name: L10nTriple('Kılıç Kraliçesi', 'Queen of Swords', 'Королева Мечей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['dürüst sınır', 'keskin şefkat', 'net söz'],
      en: ['honest boundary', 'sharp kindness', 'clear word'],
      ru: ['честная граница', 'острая доброта', 'ясное слово'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['soğuk yargı', 'mesafe silahı', 'acı dil'],
      en: ['cold verdict', 'distance-as-weapon', 'bitter tongue'],
      ru: ['холодный приговор', 'дистанция-оружие', 'горький язык'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Gerçeği nazik tutan zihin.', 'A mind that holds truth kindly.', 'Ум, держащий правду мягко.'),
      loveMeaning: L10nTriple('Bağda dürüst bir sınır konuşulabilir.', 'An honest boundary may be spoken in a bond.', 'В связи может быть сказана честная граница.'),
      careerMeaning: L10nTriple('İş te net ve adil dil sakin durabilir.', 'Clear and fair speech at work may sit calmly.', 'На работе ясная и честная речь может сидеть спокойно.'),
      moneyMeaning: L10nTriple('Hesap, utandırmadan duru olabilir.', 'An account may be clear without shaming.', 'Счёт может быть ясен без стыда.'),
      personalMeaning: L10nTriple('İçeride hem keskin hem koruyan bir yer olabilir.', 'A place both sharp and protecting may live inside.', 'Внутри может жить место и острое, и защищающее.'),
      challengeMeaning: L10nTriple('Netlik, soğumaya kayabilir.', 'Clarity may slide into coldness.', 'Ясность может стать холодом.'),
      guidanceMeaning: L10nTriple('Doğru söyle; keserek söyleme.', 'Speak truly; do not speak by cutting.', 'Говори правду; не говори режа.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha dürüst bir dil.', 'A possible climate: more honest speech.', 'Возможный климат: более честная речь.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_11', 'cups_13', 'swords_14'],
      note: L10nTriple('Adalet ölçü, Kupa Kraliçesi şefkat, Kılıç Kralı zihin yönüdür.', 'Justice measure; Queen of Cups compassion; King of Swords mind-heading.', 'Справедливость — мера; Королева Кубков — сострадание; Король Мечей — курс ума.'),
    ),
    visualAsset: 'assets/tarot/cards/swords/13_queen.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'swords_14',
    number: 14,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.swords,
    name: L10nTriple('Kılıç Kralı', 'King of Swords', 'Король Мечей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['ilke', 'sakin yargı', 'zihin omurgası'],
      en: ['principle', 'calm judgement', 'mind-spine'],
      ru: ['принцип', 'спокойное суждение', 'хребет ума'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['katılık', 'kalpsiz kural', 'mesafe putu'],
      en: ['rigidity', 'heartless rule', 'idol of distance'],
      ru: ['жёсткость', 'бессердечное правило', 'кумир дистанции'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('İlkeyle duran kılıç.', 'A sword that stands on principle.', 'Меч, стоящий на принципе.'),
      loveMeaning: L10nTriple('Bağda ilke ve netlik öne çıkabilir.', 'Principle and clarity may come forward in a bond.', 'В связи могут выйти принцип и ясность.'),
      careerMeaning: L10nTriple('İş te adil bir karar duruşu belirebilir.', 'A stance of fair decision at work may appear.', 'На работе может явиться поза справедливого решения.'),
      moneyMeaning: L10nTriple('Kural, kaynağı da düzenleyebilir.', 'A rule may also order means.', 'Правило может упорядочить и средства.'),
      personalMeaning: L10nTriple('İçeride soğuk değil, duru bir omurga istenebilir.', 'A spine that is clear, not cold, may be wanted inside.', 'Внутри может быть нужен хребет ясный, не холодный.'),
      challengeMeaning: L10nTriple('İlke, insanı ezmeye kayabilir.', 'Principle may slide into crushing a person.', 'Принцип может начать давить человека.'),
      guidanceMeaning: L10nTriple('İlkeyi tut; kalbi dışarıda bırakma.', 'Hold the principle; do not leave the heart outside.', 'Держи принцип; не оставляй сердце вовне.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha ilkeli bir zihin.', 'A possible climate: a more principled mind.', 'Возможный климат: более принципиальный ум.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_04', 'major_11', 'pentacles_14'],
      note: L10nTriple('İmparator yapı, Adalet ölçü, Tılsım Kralı madde yönüdür.', 'Emperor structure; Justice measure; King of Pentacles matter-heading.', 'Император — строй; Справедливость — мера; Король Пентаклей — курс материи.'),
    ),
    visualAsset: 'assets/tarot/cards/swords/14_king.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
];
