/// ORACLY Tarot catalogue — structured meanings, TR/EN/RU. No UI.
library;

import '../../../../core/l10n/l10n_triple.dart';
import '../oracly_tarot_card.dart';
import '../oracly_tarot_enums.dart';
import '../oracly_tarot_keywords.dart';
import '../oracly_tarot_meanings.dart';
import '../oracly_tarot_relations.dart';

const kOraclyTarotCups = <OraclyTarotCard>[
  OraclyTarotCard(
    id: 'cups_01',
    number: 1,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.cups,
    name: L10nTriple('Kupa Ası', 'Ace of Cups', 'Туз Кубков'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['açılış', 'duygu', 'kadeh'],
      en: ['opening', 'feeling', 'cup'],
      ru: ['открытие', 'чувство', 'чаша'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['taşma', 'kapanma', 'duygu korkusu'],
      en: ['overflow', 'closing', 'fear of feeling'],
      ru: ['перелив', 'закрытие', 'страх чувства'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('İlk su; henüz hikâye olmayan bir duygu.', 'First water; a feeling not yet a story.', 'Первая вода; чувство, ещё не ставшее историей.'),
      loveMeaning: L10nTriple('Bağda taze bir açıklık belirebilir.', 'A fresh openness may appear in a bond.', 'В связи может явиться свежая открытость.'),
      careerMeaning: L10nTriple('İşin insani yanı hatırlanabilir.', 'The human side of work may be remembered.', 'Может вспомниться человеческая сторона дела.'),
      moneyMeaning: L10nTriple('Cömertlik ile savurganlık karışmamalıdır.', 'Generosity and waste should not be mixed.', 'Щедрость и растрата не должны смешиваться.'),
      personalMeaning: L10nTriple('İçeride yumuşak bir kap uyanabilir.', 'A soft vessel may wake inside.', 'Внутри может проснуться мягкий сосуд.'),
      challengeMeaning: L10nTriple('Duygu, taşmaya kayabilir.', 'Feeling may slide into overflow.', 'Чувство может стать переливом.'),
      guidanceMeaning: L10nTriple('Kadehi tut; herkese dökmek zorunda değilsin.', 'Hold the cup; you do not have to pour it for everyone.', 'Держи чашу; не обязательно лить её всем.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: duygusal bir açıklık.', 'A possible climate: an emotional opening.', 'Возможный климат: эмоциональное открытие.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['wands_01', 'major_02', 'cups_02'],
      note: L10nTriple('Değnek Ası irade, Başrahibe giz, Kupa İkilisi bağ izidir.', 'Ace of Wands is will; Priestess the hidden; Two of Cups a bond.', 'Туз Жезлов — воля; Жрица — скрытое; Двойка Кубков — связь.'),
    ),
    visualAsset: 'assets/tarot/cards/cups/01_ace.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'cups_02',
    number: 2,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.cups,
    name: L10nTriple('Kupa İkilisi', 'Two of Cups', 'Двойка Кубков'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['karşılıklılık', 'kadeh', 'bağ'],
      en: ['reciprocity', 'cup', 'bond'],
      ru: ['взаимность', 'чаша', 'связь'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['dengesizlik', 'yansıtma', 'acele birlik'],
      en: ['imbalance', 'projection', 'hasty union'],
      ru: ['дисбаланс', 'проекция', 'поспешный союз'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('İki kadehin buluşması; henüz evlilik kehaneti değil.', 'Two cups meeting; not a marriage prophecy.', 'Встреча двух чаш; не пророчество брака.'),
      loveMeaning: L10nTriple('Bağda karşılıklılık konuşulabilir.', 'Reciprocity in a bond may be spoken.', 'В связи могут говорить о взаимности.'),
      careerMeaning: L10nTriple('İş ortaklığı insani bir ton alabilir.', 'A work partnership may take a human tone.', 'Рабочее партнёрство может принять человеческий тон.'),
      moneyMeaning: L10nTriple('Paylaşım, hesap kitap olmadan da düşünülebilir.', 'Sharing may be thought without a ledger.', 'Делёж можно мыслить и без книги счетов.'),
      personalMeaning: L10nTriple('İçeride \'sen ve ben\' cümlesi yumuşak durabilir.', 'The phrase \'you and I\' may sit softly inside.', 'Внутри мягко может стоять фраза «ты и я».'),
      challengeMeaning: L10nTriple('Birlik, kendini kaybetmeye kayabilir.', 'Union may slide into losing oneself.', 'Союз может стать потерей себя.'),
      guidanceMeaning: L10nTriple('Uzanan kadehi gör; henüz içmek zorunda değilsin.', 'See the offered cup; you do not have to drink yet.', 'Увидь протянутую чашу; ещё не обязательно пить.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha karşılıklı bir bağ.', 'A possible climate: a more reciprocal bond.', 'Возможный климат: более взаимная связь.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_06', 'wands_02', 'swords_02'],
      note: L10nTriple('Aşıklar seçim, Değnek ve Kılıç ikilileri tempo ve mesafedir.', 'Lovers are choice; Twos of Wands and Swords tempo and distance.', 'Влюблённые — выбор; Двойки Жезлов и Мечей — темп и дистанция.'),
    ),
    visualAsset: 'assets/tarot/cards/cups/02_two.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'cups_03',
    number: 3,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.cups,
    name: L10nTriple('Kupa Üçlüsü', 'Three of Cups', 'Тройка Кубков'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['paylaşım', 'kutlama', 'dostluk'],
      en: ['sharing', 'marking', 'friendship'],
      ru: ['деление', 'отмечание', 'дружба'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['yüzeysellik', 'dışlanma', 'fazla gürültü'],
      en: ['surface', 'exclusion', 'too much noise'],
      ru: ['поверхность', 'исключение', 'слишком много шума'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Üç kadehin masası; yalnızlığın karşıtı, evliliğin değil.', 'A table of three cups; opposite of solitude, not of marriage.', 'Стол трёх чаш; противоположность одиночеству, не браку.'),
      loveMeaning: L10nTriple('Bağ çevresinde dostluk belirginleşebilir.', 'Friendship around a bond may become clearer.', 'Вокруг связи может проясниться дружба.'),
      careerMeaning: L10nTriple('İş te işbirliği neşesi belirebilir.', 'The joy of collaboration may appear at work.', 'На работе может явиться радость сотрудничества.'),
      moneyMeaning: L10nTriple('Paylaşılan bir masanın maliyeti de vardır.', 'A shared table also has a cost.', 'У общего стола тоже есть цена.'),
      personalMeaning: L10nTriple('İçeride \'biz\' kelimesi ısınabilir.', 'The word \'we\' may warm inside.', 'Внутри может согреться слово «мы».'),
      challengeMeaning: L10nTriple('Kutlama, içi boş gürültüye kayabilir.', 'Marking may slide into empty noise.', 'Отмечание может стать пустым шумом.'),
      guidanceMeaning: L10nTriple('Masaya otur; her kadehi bitirmek zorunda değilsin.', 'Sit at the table; you do not have to empty every cup.', 'Сядь за стол; не обязательно опустошать каждую чашу.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha paylaşılmış bir neşe.', 'A possible climate: more shared gladness.', 'Возможный климат: более разделённая радость.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['wands_03', 'major_03', 'pentacles_03'],
      note: L10nTriple('Değnek Üçlüsü büyüme, İmparatoriçe bakım, Tılsım Üçlüsü zanaattır.', 'Three of Wands growth; Empress care; Three of Pentacles craft.', 'Тройка Жезлов — рост; Императрица — забота; Тройка Пентаклей — ремесло.'),
    ),
    visualAsset: 'assets/tarot/cards/cups/03_three.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'cups_04',
    number: 4,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.cups,
    name: L10nTriple('Kupa Dörtlüsü', 'Four of Cups', 'Четвёрка Кубков'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['durgunluk', 'doyum', 'içeri bakış'],
      en: ['stillness', 'enough', 'inward look'],
      ru: ['застой', 'достаточность', 'взгляд внутрь'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['nankörlük', 'kaçış', 'duygu körlüğü'],
      en: ['ingratitude', 'escape', 'feeling-blind'],
      ru: ['неблагодарность', 'бегство', 'слепота чувства'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Öndeki kadeh; bakılmayan su.', 'The cup in front; water not looked at.', 'Чаша перед тобой; вода, на которую не смотрят.'),
      loveMeaning: L10nTriple('İlişkide bıkkınlık, yokluk anlamına gelmez.', 'Weariness in a bond does not mean absence.', 'Усталость в связи не значит отсутствие.'),
      careerMeaning: L10nTriple('İşin anlamı soluk görünebilir.', 'The meaning of work may look pale.', 'Смысл дела может казаться бледным.'),
      moneyMeaning: L10nTriple('Yetmez hissi, gerçek yokluktan ayrı durabilir.', 'A sense of not-enough may sit apart from real lack.', 'Чувство «мало» может стоять отдельно от настоящей нехватки.'),
      personalMeaning: L10nTriple('İçeride doymuş ama susuz bir yer olabilir.', 'A place full yet thirsty may live inside.', 'Внутри может жить место сытое и всё же жаждущее.'),
      challengeMeaning: L10nTriple('Durgunluk, küçümsemeye kayabilir.', 'Stillness may slide into disdain.', 'Застой может стать пренебрежением.'),
      guidanceMeaning: L10nTriple('Öndeki kadehe bak; yeni bir tane istemeden önce.', 'Look at the cup in front before wanting a new one.', 'Посмотри на чашу перед собой, прежде чем хотеть новую.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: duygusal bir ara duruş.', 'A possible climate: an emotional pause.', 'Возможный климат: эмоциональная пауза.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['wands_04', 'major_12', 'swords_04'],
      note: L10nTriple('Değnek Dördü mola, Asılan Adam açı, Kılıç Dördü dinlenmedir.', 'Four of Wands pause; Hanged Man angle; Four of Swords rest.', 'Четвёрка Жезлов — пауза; Повешенный — ракурс; Четвёрка Мечей — отдых.'),
    ),
    visualAsset: 'assets/tarot/cards/cups/04_four.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'cups_05',
    number: 5,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.cups,
    name: L10nTriple('Kupa Beşlisi', 'Five of Cups', 'Пятёрка Кубков'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['kayıp', 'yas', 'dökülen su'],
      en: ['loss', 'mourning', 'spilled water'],
      ru: ['потеря', 'траур', 'пролитая вода'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['sadece kayba bakmak', 'umutsuzluk', 'inkâr'],
      en: ['seeing only loss', 'despair', 'denial'],
      ru: ['видеть только потерю', 'отчаяние', 'отрицание'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Dökülen kadehler; ayakta duranlar da vardır.', 'Spilled cups; some still stand.', 'Пролитые чаши; некоторые ещё стоят.'),
      loveMeaning: L10nTriple('Bağda bir yas katmanı belirebilir.', 'A layer of mourning may appear in a bond.', 'В связи может явиться слой траура.'),
      careerMeaning: L10nTriple('Bir iş kaybı hissedilebilir; kimlik bitişi değildir.', 'A work loss may be felt; it is not the end of identity.', 'Может ощущаться потеря в деле; это не конец личности.'),
      moneyMeaning: L10nTriple('Maddi bir dökülme fark edilebilir.', 'A material spill may be noticed.', 'Может быть заметен материальный пролив.'),
      personalMeaning: L10nTriple('İçeride ağlayan ve hâlâ bakan iki yer olabilir.', 'Two places may live inside: one weeping, one still looking.', 'Внутри могут жить два места: одно плачет, другое всё ещё смотрит.'),
      challengeMeaning: L10nTriple('Yas, her şey bitti hikâyesine bağlanabilir.', 'Mourning may bind to a story that all is over.', 'Траур может привязаться к истории, что всё кончено.'),
      guidanceMeaning: L10nTriple('Döküleni gör; ayaktakini de say.', 'See what spilled; count what still stands.', 'Увидь пролитое; сочти и то, что стоит.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha dürüst bir keder.', 'A possible climate: more honest grief.', 'Возможный климат: более честная печаль.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_13', 'swords_05', 'pentacles_05'],
      note: L10nTriple('Ölüm kapanış, Kılıç ve Tılsım Beşlisi çatışma ve yoksunluk izidir.', 'Death is closing; Fives of Swords and Pentacles clash and lack.', 'Смерть — закрытие; Пятёрки Мечей и Пентаклей — спор и нехватка.'),
    ),
    visualAsset: 'assets/tarot/cards/cups/05_five.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'cups_06',
    number: 6,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.cups,
    name: L10nTriple('Kupa Altılısı', 'Six of Cups', 'Шестёрка Кубков'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['hatıra', 'sadelik', 'geçmiş su'],
      en: ['memory', 'simplicity', 'past water'],
      ru: ['память', 'простота', 'прошлая вода'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['geçmişe kilit', 'çocuk rolü', 'şimdiyi kaçırma'],
      en: ['lock to past', 'child role', 'missing now'],
      ru: ['замок на прошлом', 'роль ребёнка', 'пропуск сейчас'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Eski bir kadeh; bugünün masasında durabilir.', 'An old cup; it may sit on today\'s table.', 'Старая чаша; она может стоять на сегодняшнем столе.'),
      loveMeaning: L10nTriple('Bağda hatırlanan bir yumuşaklık belirebilir.', 'A remembered softness may appear in a bond.', 'В связи может явиться вспомненная мягкость.'),
      careerMeaning: L10nTriple('Eski bir iş bağı veya sade bir yöntem hatırlanabilir.', 'An old work tie or a simple method may be remembered.', 'Может вспомниться старая рабочая связь или простой метод.'),
      moneyMeaning: L10nTriple('Geçmiş bir güvenlik hissi kaynaklara da değebilir.', 'A past sense of safety may also touch means.', 'Прошлое чувство безопасности может коснуться и средств.'),
      personalMeaning: L10nTriple('İçeride çocuk bir yer ısınabilir.', 'A child-place may warm inside.', 'Внутри может согреться детское место.'),
      challengeMeaning: L10nTriple('Hatıra, şimdiyi durdurabilir.', 'Memory may stop the present.', 'Память может остановить настоящее.'),
      guidanceMeaning: L10nTriple('Hatırla; orada kalma.', 'Remember; do not remain there.', 'Вспомни; не оставайся там.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha sade bir duygu.', 'A possible climate: a simpler feeling.', 'Возможный климат: более простое чувство.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['wands_06', 'major_19', 'cups_10'],
      note: L10nTriple('Değnek Altılısı geçiş, Güneş açıklık, Kupa Onu paylaşılmış masadır.', 'Six of Wands crossing; Sun openness; Ten of Cups a shared table.', 'Шестёрка Жезлов — переход; Солнце — открытость; Десятка Кубков — общий стол.'),
    ),
    visualAsset: 'assets/tarot/cards/cups/06_six.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'cups_07',
    number: 7,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.cups,
    name: L10nTriple('Kupa Yedilisi', 'Seven of Cups', 'Семёрка Кубков'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['seçenek', 'hayal', 'sisli kadeh'],
      en: ['options', 'dream', 'misty cup'],
      ru: ['варианты', 'мечта', 'туманная чаша'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['kaçış hayali', 'kararsızlık', 'gerçekten kopma'],
      en: ['escape-dream', 'indecision', 'split from real'],
      ru: ['мечта-бегство', 'нерешительность', 'отрыв от реального'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Birçok kadeh; hepsi su değildir.', 'Many cups; not all hold water.', 'Много чаш; не во всех вода.'),
      loveMeaning: L10nTriple('İlişkide birkaç imge çatışabilir.', 'Several images may clash in a bond.', 'В связи могут столкнуться несколько образов.'),
      careerMeaning: L10nTriple('İş te çok seçenek dağınık durabilir.', 'Many work options may sit scattered.', 'Много рабочих вариантов могут лежать вразброс.'),
      moneyMeaning: L10nTriple('Hayali kazanç, duru hesaptan ayrıdır.', 'Imagined gain sits apart from a clear account.', 'Воображаемая прибыль стоит отдельно от ясного счёта.'),
      personalMeaning: L10nTriple('İçeride sisli bir istek korosu olabilir.', 'A choir of misty wants may live inside.', 'Внутри может жить хор туманных желаний.'),
      challengeMeaning: L10nTriple('Hayal, seçmemenin bahanesi olabilir.', 'Dreaming may become an excuse not to choose.', 'Мечта может стать отговоркой не выбирать.'),
      guidanceMeaning: L10nTriple('Kadehlerden birine dokun; hepsini seyretme.', 'Touch one cup; do not only watch them all.', 'Дотронься до одной чаши; не только смотри на все.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: seçenek sisli bir ara.', 'A possible climate: a misty interval of options.', 'Возможный климат: туманный промежуток вариантов.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_18', 'swords_07', 'wands_07'],
      note: L10nTriple('Ay belirsizlik, Kılıç Yedilisi kayış, Değnek Yedilisi duruştur.', 'Moon unclearness; Seven of Swords slip; Seven of Wands stance.', 'Луна — неясность; Семёрка Мечей — ускользание; Семёрка Жезлов — стойка.'),
    ),
    visualAsset: 'assets/tarot/cards/cups/07_seven.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'cups_08',
    number: 8,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.cups,
    name: L10nTriple('Kupa Sekizlisi', 'Eight of Cups', 'Восьмёрка Кубков'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['ayrılış', 'daha derin su', 'sırt'],
      en: ['leaving', 'deeper water', 'back turned'],
      ru: ['уход', 'более глубокая вода', 'спина'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['kaçış', 'pişmanlık', 'yarım bırakma'],
      en: ['escape', 'regret', 'leaving half'],
      ru: ['бегство', 'сожаление', 'бросать наполовину'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Bırakılan kadeh; daha derin bir arayış.', 'A cup left behind; a deeper search.', 'Оставленная чаша; более глубокий поиск.'),
      loveMeaning: L10nTriple('Bağda bir uzaklaşma ihtiyacı belirebilir.', 'A need to step away may appear in a bond.', 'В связи может явиться нужда отойти.'),
      careerMeaning: L10nTriple('Bir işi bırakmak anlam arayışı olabilir.', 'Leaving a job may be a search for meaning.', 'Уход с дела может быть поиском смысла.'),
      moneyMeaning: L10nTriple('Maddi konfor, iç boşluğu doldurmayabilir.', 'Material comfort may not fill an inner vacancy.', 'Материальный уют может не заполнить внутреннюю пустоту.'),
      personalMeaning: L10nTriple('İçeride \'bu kadar değil\' cümlesi duruyor olabilir.', 'The sentence \'this is not enough\' may be standing inside.', 'Внутри может стоять фраза «этого мало».'),
      challengeMeaning: L10nTriple('Ayrılış, küçümseme olabilir.', 'Leaving may be disdain.', 'Уход может быть пренебрежением.'),
      guidanceMeaning: L10nTriple('Sırtını dön; yakarak gitme.', 'Turn your back; do not leave by burning.', 'Повернись спиной; не уходи сжигая.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha derin bir arayış aralığı.', 'A possible climate: an interval of deeper search.', 'Возможный климат: промежуток более глубокого поиска.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_09', 'wands_08', 'swords_08'],
      note: L10nTriple('Ermiş yalnız ışık, Değnek Sekizlisi hız, Kılıç Sekizlisi sıkışmadır.', 'Hermit solitary light; Eight of Wands speed; Eight of Swords tightness.', 'Отшельник — одинокий свет; Восьмёрка Жезлов — скорость; Восьмёрка Мечей — теснота.'),
    ),
    visualAsset: 'assets/tarot/cards/cups/08_eight.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'cups_09',
    number: 9,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.cups,
    name: L10nTriple('Kupa Dokuzlusu', 'Nine of Cups', 'Девятка Кубков'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['iç doyum', 'dilek', 'sakin su'],
      en: ['inner enough', 'wish', 'calm water'],
      ru: ['внутренняя достаточность', 'желание', 'спокойная вода'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['şişirme', 'yalnız zafer', 'doyumsuzluk'],
      en: ['inflation', 'lone victory', 'never enough'],
      ru: ['раздувание', 'одинокая победа', 'никогда не довольно'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Dolu bir kadeh; sahne mutluluğu değil.', 'A full cup; not staged happiness.', 'Полная чаша; не сценическое счастье.'),
      loveMeaning: L10nTriple('Bağda yeterlilik hissedilebilir.', 'Enough-ness may be felt in a bond.', 'В связи может ощущаться достаточность.'),
      careerMeaning: L10nTriple('İş te kişisel bir tatmin belirebilir.', 'A personal enough at work may appear.', 'На работе может явиться личная достаточность.'),
      moneyMeaning: L10nTriple('İstek ile ihtiyaç ayrılabilir.', 'Wish and need may separate.', 'Желание и нужда могут разделиться.'),
      personalMeaning: L10nTriple('İçeride \'yeter\' diyebilen bir yer olabilir.', 'A place able to say \'enough\' may live inside.', 'Внутри может жить место, способное сказать «довольно».'),
      challengeMeaning: L10nTriple('Doyum, başkasını dışarıda bırakmaya kayabilir.', 'Enough-ness may slide into leaving others out.', 'Достаточность может начать оставлять других вовне.'),
      guidanceMeaning: L10nTriple('Kadehi tadına bak; vitrine koyma.', 'Taste the cup; do not put it in a shop window.', 'Вкуси чашу; не ставь её в витрину.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha sakin bir yeterlilik.', 'A possible climate: quieter enough-ness.', 'Возможный климат: более тихая достаточность.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_17', 'pentacles_09', 'cups_10'],
      note: L10nTriple('Yıldız sakin umut, Tılsım Dokuzu yeter, Kupa Onu masadır.', 'Star quiet hope; Nine of Pentacles enough; Ten of Cups the table.', 'Звезда — тихая надежда; Девятка Пентаклей — довольно; Десятка Кубков — стол.'),
    ),
    visualAsset: 'assets/tarot/cards/cups/09_nine.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'cups_10',
    number: 10,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.cups,
    name: L10nTriple('Kupa Onlusu', 'Ten of Cups', 'Десятка Кубков'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['paylaşılan masa', 'aile suyu', 'çember'],
      en: ['shared table', 'family water', 'circle'],
      ru: ['общий стол', 'семейная вода', 'круг'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['ideal sahne', 'baskı mutluluk', 'çatlak gizleme'],
      en: ['ideal stage', 'forced joy', 'hiding cracks'],
      ru: ['идеальная сцена', 'навязанная радость', 'скрытие трещин'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Dolu masanın sakin hali; sonsuzluk iddiası yok.', 'The calm form of a full table; no claim of forever.', 'Спокойный вид полного стола; нет утверждения навсегда.'),
      loveMeaning: L10nTriple('Bağda aidiyet ve paylaşım öne çıkabilir.', 'Belonging and sharing may come forward in a bond.', 'В связи могут выйти принадлежность и делёж.'),
      careerMeaning: L10nTriple('İş te bir ekip duygusu belirebilir.', 'A sense of team at work may appear.', 'На работе может явиться чувство команды.'),
      moneyMeaning: L10nTriple('Paylaşılan refah, vitrin refahından ayrıdır.', 'Shared plenty sits apart from display plenty.', 'Общее изобилие стоит отдельно от витринного.'),
      personalMeaning: L10nTriple('İçeride ev gibi bir daire ısınabilir.', 'A household circle may warm inside.', 'Внутри может согреться домашний круг.'),
      challengeMeaning: L10nTriple('Çember, dışarıdakini suçlamaya kayabilir.', 'The circle may slide into blaming the outsider.', 'Круг может начать винить внешнего.'),
      guidanceMeaning: L10nTriple('Masayı kur; sahne dekoru yapma.', 'Set the table; do not build stage scenery.', 'Накрой стол; не строй сценические декорации.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha paylaşılmış bir duruş.', 'A possible climate: a more shared stance.', 'Возможный климат: более общая поза.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['wands_10', 'pentacles_10', 'major_21'],
      note: L10nTriple('Değnek Onu yük, Tılsım Onu soy, Dünya tamamlanmadır.', 'Ten of Wands load; Ten of Pentacles lineage; World completion.', 'Десятка Жезлов — ноша; Десятка Пентаклей — род; Мир — завершение.'),
    ),
    visualAsset: 'assets/tarot/cards/cups/10_ten.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'cups_11',
    number: 11,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.cups,
    name: L10nTriple('Kupa Habercisi', 'Page of Cups', 'Паж Кубков'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['duygu haberi', 'yumuşak merak', 'rüya kadehi'],
      en: ['feeling-news', 'soft curiosity', 'dream cup'],
      ru: ['весть чувства', 'мягкое любопытство', 'чаша сна'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['aşırı duyarlılık', 'kaçış hayali', 'alınma'],
      en: ['over-sensitivity', 'escape-dream', 'taking offense'],
      ru: ['сверхчувствительность', 'мечта-бегство', 'обида'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Suyun habercisi; henüz derin deniz değil.', 'Messenger of water; not yet the deep sea.', 'Вестник воды; ещё не глубокое море.'),
      loveMeaning: L10nTriple('Bağda utangaç bir açıklık belirebilir.', 'A shy openness may appear in a bond.', 'В связи может явиться застенчивая открытость.'),
      careerMeaning: L10nTriple('İş te insani bir sezgi kapısı aralanabilir.', 'A door of human sensing at work may open a little.', 'На работе может чуть открыться дверь человеческого чутья.'),
      moneyMeaning: L10nTriple('Küçük bir gönül hareketi kaynaklara da değebilir.', 'A small heart-move may also touch means.', 'Малое движение сердца может коснуться и средств.'),
      personalMeaning: L10nTriple('İçeride şiir gibi bir yer uyanabilir.', 'A place like a poem may wake inside.', 'Внутри может проснуться место, похожее на стихотворение.'),
      challengeMeaning: L10nTriple('Haberci, her şeyi işaret okumaya kayabilir.', 'The messenger may slide into reading omens in everything.', 'Вестник может начать читать приметы во всём.'),
      guidanceMeaning: L10nTriple('Hisset; her duyguyu kehanet yapma.', 'Feel; do not make every feeling an oracle.', 'Чувствуй; не делай из каждого чувства оракула.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha yumuşak bir merak.', 'A possible climate: softer curiosity.', 'Возможный климат: более мягкое любопытство.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['wands_11', 'major_18', 'cups_12'],
      note: L10nTriple('Değnek Habercisi kıvılcım, Ay sis, Kupa Şövalyesi yolculuktur.', 'Page of Wands spark; Moon mist; Knight of Cups journey.', 'Паж Жезлов — искра; Луна — туман; Рыцарь Кубков — путь.'),
    ),
    visualAsset: 'assets/tarot/cards/cups/11_page.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'cups_12',
    number: 12,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.cups,
    name: L10nTriple('Kupa Şövalyesi', 'Knight of Cups', 'Рыцарь Кубков'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['duygu yolculuğu', 'teklif', 'akış'],
      en: ['feeling-journey', 'offer', 'flow'],
      ru: ['путь чувства', 'предложение', 'поток'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['dağıtılmış gönül', 'kaçış romantizmi', 'sözde derinlik'],
      en: ['scattered heart', 'escape-romance', 'seeming depth'],
      ru: ['рассеянное сердце', 'романтика бегства', 'кажущаяся глубина'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Kadehle yola çıkan duruş.', 'A stance that takes the cup on the road.', 'Поза, берущая чашу в дорогу.'),
      loveMeaning: L10nTriple('Bağda bir teklif veya yumuşak takip belirebilir.', 'An offer or a gentle following may appear in a bond.', 'В связи может явиться предложение или мягкое следование.'),
      careerMeaning: L10nTriple('İş te anlam arayan bir hareket mümkün görünür.', 'A motion seeking meaning at work may be possible.', 'На работе возможно движение в поиске смысла.'),
      moneyMeaning: L10nTriple('Gönül ile hesap ayrı durabilir.', 'Heart and account may sit apart.', 'Сердце и счёт могут стоять отдельно.'),
      personalMeaning: L10nTriple('İçeride akan ve duramayan bir su olabilir.', 'Water that flows and cannot stay may live inside.', 'Внутри может жить вода, которая течёт и не стоит.'),
      challengeMeaning: L10nTriple('Yolculuk, bağlanamamaya kayabilir.', 'The journey may slide into inability to bind.', 'Путь может стать неумением связываться.'),
      guidanceMeaning: L10nTriple('Teklifi götür; her kapıyı çalma.', 'Carry the offer; do not knock every door.', 'Неси предложение; не стучи в каждую дверь.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha akışkan bir gönül.', 'A possible climate: a more fluid heart.', 'Возможный климат: более текучее сердце.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['wands_12', 'major_14', 'swords_12'],
      note: L10nTriple('Değnek Şövalyesi ateş yol, Denge harman, Kılıç Şövalyesi zihin yoludur.', 'Knight of Wands fire-road; Temperance blend; Knight of Swords mind-road.', 'Рыцарь Жезлов — огненная дорога; Умеренность — смесь; Рыцарь Мечей — дорога ума.'),
    ),
    visualAsset: 'assets/tarot/cards/cups/12_knight.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'cups_13',
    number: 13,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.cups,
    name: L10nTriple('Kupa Kraliçesi', 'Queen of Cups', 'Королева Кубков'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['derin kadeh', 'şefkat', 'iç deniz'],
      en: ['deep cup', 'compassion', 'inner sea'],
      ru: ['глубокая чаша', 'сострадание', 'внутреннее море'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['taşma', 'sınır yokluğu', 'kurtarıcılık'],
      en: ['overflow', 'no boundary', 'rescuing'],
      ru: ['перелив', 'нет границы', 'спасательство'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Duyguyu tutan olgun kap.', 'A mature vessel that holds feeling.', 'Зрелый сосуд, держащий чувство.'),
      loveMeaning: L10nTriple('Bağda derin şefkat belirebilir; erime ayrıdır.', 'Deep compassion may appear in a bond; melting away is another matter.', 'В связи может явиться глубокое сострадание; раствориться — иное.'),
      careerMeaning: L10nTriple('İş te duygusal zekâ sakin durabilir.', 'Emotional intelligence at work may sit calmly.', 'На работе эмоциональный ум может сидеть спокойно.'),
      moneyMeaning: L10nTriple('Cömertlik, kendini yok etmeden durabilir.', 'Generosity may stand without self-erasure.', 'Щедрость может стоять без самозабвения.'),
      personalMeaning: L10nTriple('İçeride başkasını dinleyebilen bir deniz olabilir.', 'A sea able to listen to another may live inside.', 'Внутри может жить море, способное слушать другого.'),
      challengeMeaning: L10nTriple('Şefkat, sınır kaybına kayabilir.', 'Compassion may slide into lost boundary.', 'Сострадание может стать потерей границы.'),
      guidanceMeaning: L10nTriple('Tut; boğulma.', 'Hold; do not drown.', 'Держи; не тони.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha derin bir şefkat.', 'A possible climate: deeper compassion.', 'Возможный климат: более глубокое сострадание.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_03', 'wands_13', 'cups_14'],
      note: L10nTriple('İmparatoriçe bakım, Değnek Kraliçesi ev ateşi, Kupa Kralı ölçü sudur.', 'Empress care; Queen of Wands household fire; King of Cups measured water.', 'Императрица — забота; Королева Жезлов — домашний огонь; Король Кубков — мерная вода.'),
    ),
    visualAsset: 'assets/tarot/cards/cups/13_queen.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'cups_14',
    number: 14,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.cups,
    name: L10nTriple('Kupa Kralı', 'King of Cups', 'Король Кубков'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['ölçülü su', 'sakin kaptan', 'duygu yönü'],
      en: ['measured water', 'calm captain', 'feeling-heading'],
      ru: ['мерная вода', 'спокойный капитан', 'курс чувства'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['soğukluk', 'bastırma', 'duygu yokmuş gibi'],
      en: ['coldness', 'suppression', 'as if no feeling'],
      ru: ['холод', 'подавление', 'будто нет чувства'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Suyu yönlendiren sakin duruş.', 'A calm stance that steers water.', 'Спокойная поза, ведущая воду.'),
      loveMeaning: L10nTriple('Bağda olgun bir duygusal netlik belirebilir.', 'Mature emotional clarity may appear in a bond.', 'В связи может явиться зрелая эмоциональная ясность.'),
      careerMeaning: L10nTriple('İş te sakin bir insan yönetimi mümkün görünür.', 'Calm people-stewardship at work may be possible.', 'На работе возможно спокойное управление людьми.'),
      moneyMeaning: L10nTriple('Duygu ile hesabı aynı masada tutmak sakinleştirir.', 'Holding feeling and account at the same table steadies.', 'Держать чувство и счёт за одним столом успокаивает.'),
      personalMeaning: L10nTriple('İçeride hem derin hem ölçülü bir kaptan olabilir.', 'A captain both deep and measured may live inside.', 'Внутри может жить капитан и глубокий, и мерный.'),
      challengeMeaning: L10nTriple('Ölçü, duygusuzluğa kayabilir.', 'Measure may slide into feelinglessness.', 'Мера может стать бесчувственностью.'),
      guidanceMeaning: L10nTriple('Yön ver; donma.', 'Steer; do not freeze.', 'Веди; не замерзай.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha olgun bir duygu yönü.', 'A possible climate: a more mature heading of feeling.', 'Возможный климат: более зрелый курс чувства.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_14', 'swords_14', 'pentacles_14'],
      note: L10nTriple('Denge harman, Kılıç ve Tılsım Kralları zihin ve madde yönüdür.', 'Temperance blend; Kings of Swords and Pentacles mind and matter heading.', 'Умеренность — смесь; Короли Мечей и Пентаклей — курс ума и материи.'),
    ),
    visualAsset: 'assets/tarot/cards/cups/14_king.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
];
