/// ORACLY Tarot catalogue — structured meanings, TR/EN/RU. No UI.
library;

import '../../../../core/l10n/l10n_triple.dart';
import '../oracly_tarot_card.dart';
import '../oracly_tarot_enums.dart';
import '../oracly_tarot_keywords.dart';
import '../oracly_tarot_meanings.dart';
import '../oracly_tarot_relations.dart';

const kOraclyTarotMajor00to10 = <OraclyTarotCard>[
  OraclyTarotCard(
    id: 'major_00',
    number: 0,
    arcana: OraclyTarotArcana.major,
    suit: OraclyTarotSuit.none,
    name: L10nTriple('Deli', 'The Fool', 'Шут'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['eşik', 'merak', 'izin'],
      en: ['threshold', 'curiosity', 'permission'],
      ru: ['порог', 'любопытство', 'разрешение'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['acele', 'dağılma', 'kaçış'],
      en: ['haste', 'scatter', 'avoidance'],
      ru: ['спешка', 'рассеянность', 'избегание'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Henüz bağlanmamış bir adım; eşikte duran merak.', 'A step not yet claimed; curiosity at a threshold.', 'Шаг, который ещё не выбран; любопытство на пороге.'),
      loveMeaning: L10nTriple('Bağda taze bir açıklık belirebilir; acele bir sözden önce durmak değerli olabilir.', 'A fresh openness may appear in a bond; pausing before a hasty vow can matter.', 'В связи может появиться свежая открытость; пауза перед поспешным словом бывает важна.'),
      careerMeaning: L10nTriple('Yeni bir iş hareketi mümkün görünür; deneyimden önce niyeti netleştirmek sakinleştirir.', 'A new work movement may be possible; clarifying intent before experience steadies the step.', 'Возможно новое движение в деле; ясность намерения до опыта успокаивает шаг.'),
      moneyMeaning: L10nTriple('Kaynaklar henüz şekil almamış olabilir; ilk harcamayı bir soru gibi tutmak yardımcı olabilir.', 'Resources may still be unformed; holding the first spend as a question can help.', 'Средства могут быть ещё бесформенными; первый расход стоит держать как вопрос.'),
      personalMeaning: L10nTriple('İçeride bir izin hissi uyanabilir: henüz kimse olmadan yola bakmak.', 'An inner permission may stir: looking at the road before becoming anyone.', 'Внутри может проснуться разрешение: смотреть на путь, ещё ни кем не став.'),
      challengeMeaning: L10nTriple('Merak, hazır olmadan atlamaya dönüşebilir.', 'Curiosity may tilt into leaping before one is ready.', 'Любопытство может стать прыжком без готовности.'),
      guidanceMeaning: L10nTriple('Kapıya yaklaş; henüz bütün cevapları taşımak zorunda değilsin.', 'Approach the door; you do not have to carry every answer yet.', 'Подойди к двери; не обязательно нести все ответы сразу.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha açık bir başlangıç — vaat değil, davet.', 'A possible climate: a more open beginning — an invitation, not a promise.', 'Возможный климат: более открытое начало — приглашение, не обещание.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_17', 'major_21', 'wands_01'],
      note: L10nTriple('Yıldız ve Dünya ile eşik ailesinde konuşabilir; Değnek Ası ilk kıvılcımı taşır.', 'May converse with the Star and World as a threshold family; Ace of Wands carries the first spark.', 'Может говорить со Звездой и Миром как семейство порога; Туз Жезлов несёт первую искру.'),
    ),
    visualAsset: 'assets/tarot/cards/major/00_fool.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'major_01',
    number: 1,
    arcana: OraclyTarotArcana.major,
    suit: OraclyTarotSuit.none,
    name: L10nTriple('Büyücü', 'The Magician', 'Маг'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['dikkat', 'zanaat', 'yön'],
      en: ['attention', 'craft', 'direction'],
      ru: ['внимание', 'ремесло', 'направление'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['dağınık irade', 'gösteriş', 'savurganlık'],
      en: ['scattered will', 'display', 'waste'],
      ru: ['рассеянная воля', 'показ', 'трата'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Elin, bakışın ve niyetin aynı masada buluşması.', 'Hand, gaze, and intent meeting at the same table.', 'Рука, взгляд и намерение встречаются за одним столом.'),
      loveMeaning: L10nTriple('İlişkide net bir jest mümkün olabilir; sözün davranışla uyumu önem kazanabilir.', 'A clear gesture in relating may be possible; speech matching action may matter more.', 'Возможен ясный жест в близости; согласие слова и поступка может стать важнее.'),
      careerMeaning: L10nTriple('Yeteneği görünür kılmak bir seçenek olabilir; araçları abartmadan kullanmak sakin duruştur.', 'Making a skill visible may be an option; using tools without display is the calmer stance.', 'Сделать умение видимым может быть выбором; пользоваться средствами без показухи — более спокойная поза.'),
      moneyMeaning: L10nTriple('Kaynakları bir araya getirmek mümkün görünür; hepsini bir anda harcamak gerekmez.', 'Gathering means may be possible; they need not all be spent at once.', 'Собрать средства, возможно, уместно; не обязательно тратить всё сразу.'),
      personalMeaning: L10nTriple('Odak, dağınık bir gücü sade bir işe çevirebilir.', 'Focus may turn scattered force into a simple task.', 'Фокус может превратить рассеянную силу в простое дело.'),
      challengeMeaning: L10nTriple('Yetenek, başkalarını etkilemek için kullanılabilir.', 'Skill may be used to impress rather than to make.', 'Умение может служить впечатлению, а не делу.'),
      guidanceMeaning: L10nTriple('Bir aracı seç ve onu sonuna kadar kullan; hepsini birden savurma.', 'Choose one tool and use it through; do not scatter them all.', 'Выбери один инструмент и доведи его; не разбрасывай все сразу.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha bilinçli bir yön — sonuç garantisi değil.', 'A possible climate: more conscious direction — not a guaranteed outcome.', 'Возможный климат: более сознательное направление — не гарантия итога.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_02', 'wands_01', 'pentacles_01'],
      note: L10nTriple('Başrahibe iç sesi tutar; Asa ve Tılsım Ası el ile maddeyi hatırlatır.', 'The Priestess holds inner hearing; Aces of Wands and Pentacles recall hand and matter.', 'Жрица держит внутренний слух; Тузы Жезлов и Пентаклей напоминают о руке и материи.'),
    ),
    visualAsset: 'assets/tarot/cards/major/01_magician.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'major_02',
    number: 2,
    arcana: OraclyTarotArcana.major,
    suit: OraclyTarotSuit.none,
    name: L10nTriple('Başrahibe', 'The High Priestess', 'Верховная Жрица'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['sessizlik', 'sezgi', 'giz'],
      en: ['silence', 'sensing', 'withholding'],
      ru: ['тишина', 'чутьё', 'удержание'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['inkâr', 'kapalı sır', 'kopukluk'],
      en: ['denial', 'closed secret', 'disconnect'],
      ru: ['отрицание', 'закрытая тайна', 'разрыв'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Henüz söze dökülmemiş bir bilgi; perde arkasındaki duruş.', 'Knowing not yet spoken; a stance behind the veil.', 'Знание, ещё не сказанное; поза за завесой.'),
      loveMeaning: L10nTriple('Bağda söylenmeyen bir katman olabilir; zorlamak yerine beklemek daha nazik olabilir.', 'A bond may hold an unspoken layer; waiting may be kinder than forcing.', 'В связи может быть несказанный слой; ждать бывает мягче, чем давить.'),
      careerMeaning: L10nTriple('Görünmeyen bilgi işe yön verebilir; her şeyi hemen açıklamak gerekmez.', 'Unseen knowledge may guide work; not everything needs to be declared at once.', 'Невидимое знание может вести дело; не всё нужно сразу объявлять.'),
      moneyMeaning: L10nTriple('Gizli bir maliyet veya saklı bir kaynak fark edilebilir; acele spekülasyon sakin değildir.', 'A hidden cost or a held resource may be noticed; hasty speculation is not calm.', 'Может открыться скрытый расход или удержанный ресурс; спешная игра не спокойна.'),
      personalMeaning: L10nTriple('İç ses, gürültüden çekildiğinde daha net duyulabilir.', 'The inner voice may be clearer when noise recedes.', 'Внутренний голос яснее, когда шум отступает.'),
      challengeMeaning: L10nTriple('Sessizlik, kaçış veya başkalarını dışarıda bırakmak olabilir.', 'Silence may become avoidance or shutting others out.', 'Тишина может стать избеганием или отсечением других.'),
      guidanceMeaning: L10nTriple('Cevabı biraz daha içerde tut; henüz sahneye çıkarmak zorunda değilsin.', 'Keep the answer a little longer inside; it does not have to take the stage yet.', 'Подержи ответ ещё внутри; ему не обязательно выходить на сцену.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha içsel bir dinleme dönemi.', 'A possible climate: a period of more inward listening.', 'Возможный климат: время более внутреннего слушания.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_18', 'cups_01', 'major_09'],
      note: L10nTriple('Ay belirsiz görmeyi, Kupa Ası duyguyu, Ermiş yalnız ışığı taşır.', 'The Moon holds unclear seeing; Ace of Cups feeling; the Hermit solitary light.', 'Луна — неясное зрение; Туз Кубков — чувство; Отшельник — одинокий свет.'),
    ),
    visualAsset: 'assets/tarot/cards/major/02_high_priestess.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'major_03',
    number: 3,
    arcana: OraclyTarotArcana.major,
    suit: OraclyTarotSuit.none,
    name: L10nTriple('İmparatoriçe', 'The Empress', 'Императрица'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['besleme', 'büyüme', 'beden'],
      en: ['tending', 'growth', 'body'],
      ru: ['забота', 'рост', 'тело'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['boğma', 'tükenme', 'savurganlık'],
      en: ['smothering', 'depletion', 'excess'],
      ru: ['удушение', 'истощение', 'избыток'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Büyümeyi savunan bir şefkat; toprağın yavaş ritmi.', 'Care that defends growth; the slow rhythm of soil.', 'Забота, защищающая рост; медленный ритм почвы.'),
      loveMeaning: L10nTriple('İlişkide besleyici bir sıcaklık belirebilir; sınır olmadan şefkat yorucu olabilir.', 'Nourishing warmth may appear in a bond; care without a boundary can tire.', 'В связи может появиться питающая теплота; забота без границы утомляет.'),
      careerMeaning: L10nTriple('Bir işin filizlenmesi mümkün görünür; aceleye değil bakıma ihtiyaç duyabilir.', 'A piece of work may be sprouting; it may need tending more than speed.', 'Дело может прорастать; ему может быть нужен уход, а не скорость.'),
      moneyMeaning: L10nTriple('Bolluk bir his olarak gelebilir; paylaşım ile savurganlık aynı şey değildir.', 'Abundance may be felt; sharing and wasting are not the same.', 'Может ощущаться изобилие; делиться и растрачивать — не одно и то же.'),
      personalMeaning: L10nTriple('Beden, dinlenme ve yaratma arasında daha nazik bir yer isteyebilir.', 'The body may ask for a kinder place between rest and making.', 'Тело может просить более мягкое место между отдыхом и творчеством.'),
      challengeMeaning: L10nTriple('Bakım, kontrol veya kendini unutmaya kayabilir.', 'Care may slide into control or self-erasure.', 'Забота может стать контролем или самозабвением.'),
      guidanceMeaning: L10nTriple('Bir şeyi büyüt; onu sıkıştırma.', 'Grow something; do not squeeze it.', 'Выращивай; не сжимай.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha verimli, daha yavaş bir bakım.', 'A possible climate: more fertile, slower tending.', 'Возможный климат: более плодородная, более медленная забота.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_04', 'pentacles_03', 'cups_03'],
      note: L10nTriple('İmparator yapı verir; Tılsım ve Kupa üçlüleri büyüme ve bağ izlerini taşır.', 'The Emperor offers structure; Threes of Pentacles and Cups carry growth and bond.', 'Император даёт строй; Тройки Пентаклей и Кубков несут рост и связь.'),
    ),
    visualAsset: 'assets/tarot/cards/major/03_empress.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'major_04',
    number: 4,
    arcana: OraclyTarotArcana.major,
    suit: OraclyTarotSuit.none,
    name: L10nTriple('İmparator', 'The Emperor', 'Император'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['yapı', 'sınır', 'sorumluluk'],
      en: ['structure', 'boundary', 'responsibility'],
      ru: ['строй', 'граница', 'ответственность'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['katılık', 'mesafe', 'baskı'],
      en: ['rigidity', 'distance', 'pressure'],
      ru: ['жёсткость', 'дистанция', 'давление'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Düzeni koruyan bir omurga; sınırın sakin hali.', 'A spine that keeps order; the calm form of a boundary.', 'Хребет, держащий порядок; спокойный вид границы.'),
      loveMeaning: L10nTriple('Bağda netlik ve güven ihtiyacı öne çıkabilir; yumuşaklık unutulmamalıdır.', 'A need for clarity and safety may rise in a bond; softness still belongs.', 'В связи может усилиться нужда в ясности и опоре; мягкость всё же нужна.'),
      careerMeaning: L10nTriple('Rol, kural veya çerçeve konuşulabilir; liderlik dinlemekle de kurulur.', 'Role, rule, or frame may be in question; leadership is also made by listening.', 'Могут встать роль, правило, рамка; лидерство также строится слушанием.'),
      moneyMeaning: L10nTriple('Plan ve sınır, dağınık harcamayı sakinleştirebilir.', 'A plan and a limit may quiet scattered spending.', 'План и предел могут успокоить разброс трат.'),
      personalMeaning: L10nTriple('İçeride bir yetişkin duruşu istenebilir: hem koruyan hem esneyen.', 'An inner adult stance may be wanted: protective and still able to bend.', 'Внутри может быть нужен взрослый стан: и защита, и гибкость.'),
      challengeMeaning: L10nTriple('Düzen, başkalarını küçültmeye dönüşebilir.', 'Order may turn into shrinking others.', 'Порядок может начать уменьшать других.'),
      guidanceMeaning: L10nTriple('Çerçeveyi kur; duvarı putlaştırma.', 'Build a frame; do not worship the wall.', 'Построй раму; не делай стену кумиром.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha duru bir sorumluluk alanı.', 'A possible climate: a clearer field of responsibility.', 'Возможный климат: более ясное поле ответственности.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_03', 'major_11', 'pentacles_04'],
      note: L10nTriple('İmparatoriçe bakım, Adalet ölçü, Tılsım Dördü durağanlık izi taşır.', 'The Empress tends; Justice measures; Four of Pentacles holds stillness.', 'Императрица растит; Справедливость меряет; Четвёрка Пентаклей держит покой.'),
    ),
    visualAsset: 'assets/tarot/cards/major/04_emperor.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'major_05',
    number: 5,
    arcana: OraclyTarotArcana.major,
    suit: OraclyTarotSuit.none,
    name: L10nTriple('Aziz', 'The Hierophant', 'Иерофант'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['öğreti', 'aidiyet', 'ritüel'],
      en: ['teaching', 'belonging', 'ritual'],
      ru: ['учение', 'принадлежность', 'ритуал'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['kör uyum', 'dogma', 'isyan'],
      en: ['blind fit', 'dogma', 'revolt'],
      ru: ['слепое согласие', 'догма', 'бунт'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Paylaşılan bir yol; bir odada birlikte durmanın bilgeliği.', 'A shared path; the wisdom of standing together in a room.', 'Общий путь; мудрость стоять вместе в одной комнате.'),
      loveMeaning: L10nTriple('İlişki bir biçim, söz veya gelenek arıyor olabilir; iç ses de yerini korur.', 'A bond may seek a form, vow, or custom; the inner voice still has a seat.', 'Связь может искать форму, слово, обычай; внутренний голос всё же имеет место.'),
      careerMeaning: L10nTriple('Mentor, kurum veya ortak dil gündeme gelebilir.', 'A mentor, an institution, or a shared language may come forward.', 'Могут выйти наставник, институт или общий язык.'),
      moneyMeaning: L10nTriple('Bilinen yollar güven verebilir; her yeni yol daha doğru değildir.', 'Familiar paths may feel safer; a new path is not always truer.', 'Привычные пути могут казаться спокойнее; новый путь не всегда вернее.'),
      personalMeaning: L10nTriple('Aidiyet ihtiyacı ile kendi yolunun gerilimi belirginleşebilir.', 'The tension between belonging and one\'s own path may sharpen.', 'Напряжение между принадлежностью и своим путём может стать яснее.'),
      challengeMeaning: L10nTriple('Öğreti, düşünmeden tekrar etmeye kayabilir.', 'Teaching may slide into repetition without thought.', 'Учение может стать повторением без мысли.'),
      guidanceMeaning: L10nTriple('Kapıyı çal; anahtarı kimseye teslim etme.', 'Knock at the door; do not hand over the key.', 'Постучи в дверь; не отдавай ключ.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: paylaşılan bir pratik veya öğreti etrafında durmak.', 'A possible climate: standing around a shared practice or teaching.', 'Возможный климат: стояние вокруг общей практики или учения.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_02', 'major_06', 'cups_10'],
      note: L10nTriple('Başrahibe iç oda, Aşıklar seçim, Kupa Onu paylaşılmış masa izidir.', 'Priestess is the inner room; Lovers the choice; Ten of Cups a shared table.', 'Жрица — внутренняя комната; Влюблённые — выбор; Десятка Кубков — общий стол.'),
    ),
    visualAsset: 'assets/tarot/cards/major/05_hierophant.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'major_06',
    number: 6,
    arcana: OraclyTarotArcana.major,
    suit: OraclyTarotSuit.none,
    name: L10nTriple('Aşıklar', 'The Lovers', 'Влюблённые'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['seçim', 'uyum', 'değer'],
      en: ['choice', 'accord', 'value'],
      ru: ['выбор', 'согласие', 'ценность'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['kararsızlık', 'uyumsuzluk', 'kaçınma'],
      en: ['indecision', 'mismatch', 'evasion'],
      ru: ['нерешительность', 'несовпадение', 'уклонение'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Kalp ile değerin aynı anda seçilmesi.', 'Heart and value chosen at the same time.', 'Сердце и ценность выбираются вместе.'),
      loveMeaning: L10nTriple('Bir bağ, dürüst bir seçim isteyebilir; çekim tek başına yeter demek zorunda değildir.', 'A bond may ask for an honest choice; attraction alone need not be called enough.', 'Связь может просить честный выбор; одного влечения не обязательно называть достаточным.'),
      careerMeaning: L10nTriple('İki yol arasında durulabilir; değerlerle uyum, hızdan daha sakin bir ölçü olabilir.', 'One may stand between two work paths; accord with values can be a calmer measure than speed.', 'Можно стоять между двумя путями дела; согласие с ценностями спокойнее скорости.'),
      moneyMeaning: L10nTriple('Harcama bir değer seçimini ele verebilir.', 'Spending may reveal a choice of values.', 'Расход может выявить выбор ценностей.'),
      personalMeaning: L10nTriple('Kendiyle yapılan bir anlaşma gündeme gelebilir.', 'An agreement with oneself may come forward.', 'Может выйти соглашение с самим собой.'),
      challengeMeaning: L10nTriple('Seçmemek de bir seçim gibi ağırlaşabilir.', 'Not choosing may become as heavy as a choice.', 'Не выбирать может стать так же тяжело, как выбор.'),
      guidanceMeaning: L10nTriple('Hangisinin sana ait olduğunu sor; hangisinin parlak göründüğünü değil.', 'Ask which belongs to you, not which merely shines.', 'Спроси, что твоё, а не что просто блестит.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha bilinçli bir birlik veya ayrışma — ikisi de kehanet değildir.', 'A possible climate: a more conscious union or parting — neither is a prophecy.', 'Возможный климат: более сознательный союз или расхождение — ни то ни другое не пророчество.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_11', 'cups_02', 'swords_02'],
      note: L10nTriple('Adalet ölçü getirir; Kupa ve Kılıç ikilileri bağ ile mesafe gerilimini taşır.', 'Justice brings measure; Twos of Cups and Swords hold bond and distance.', 'Справедливость даёт меру; Двойки Кубков и Мечей держат связь и дистанцию.'),
    ),
    visualAsset: 'assets/tarot/cards/major/06_lovers.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'major_07',
    number: 7,
    arcana: OraclyTarotArcana.major,
    suit: OraclyTarotSuit.none,
    name: L10nTriple('Savaş Arabası', 'The Chariot', 'Колесница'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['yön', 'irade', 'hareket'],
      en: ['heading', 'will', 'motion'],
      ru: ['курс', 'воля', 'движение'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['dağılma', 'zorlama', 'yol kaybı'],
      en: ['split', 'forcing', 'lost heading'],
      ru: ['разрыв', 'нажим', 'потеря курса'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Zıt güçleri aynı yöne çağıran irade.', 'Will that calls opposing forces toward one heading.', 'Воля, зовущая противоположные силы к одному курсу.'),
      loveMeaning: L10nTriple('İlişkide ilerleme isteği belirebilir; diğerini sürüklemek ayrı bir konudur.', 'A wish to move forward in a bond may appear; pulling the other is a different matter.', 'Может появиться желание двигать связь вперёд; тащить другого — иное дело.'),
      careerMeaning: L10nTriple('Hedefe doğru toplanmış bir çaba mümkün görünür.', 'A gathered effort toward a goal may be possible.', 'Возможно собранное усилие к цели.'),
      moneyMeaning: L10nTriple('Kararlı bir adım kaynakları hizalayabilir; acele risk ayrı bir sorudur.', 'A firm step may align resources; haste-as-risk is a separate question.', 'Твёрдый шаг может выстроить средства; спешка как риск — отдельный вопрос.'),
      personalMeaning: L10nTriple('Dağınık arzular tek bir yöne çekilebilir.', 'Scattered wants may be drawn into one heading.', 'Разбросанные желания могут собраться в один курс.'),
      challengeMeaning: L10nTriple('İrade, dinlemeyi ezip geçebilir.', 'Will may crush listening.', 'Воля может раздавить слушание.'),
      guidanceMeaning: L10nTriple('Dizgini tut; atları incitme.', 'Hold the reins; do not harm the horses.', 'Держи поводья; не рань коней.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha toplanmış bir hareket.', 'A possible climate: more gathered motion.', 'Возможный климат: более собранное движение.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_08', 'wands_07', 'major_01'],
      note: L10nTriple('Güç yumuşak irade, Değnek Yedilisi duruş, Büyücü el izidir.', 'Strength is gentle will; Seven of Wands stance; Magician the hand.', 'Сила — мягкая воля; Семёрка Жезлов — стойка; Маг — рука.'),
    ),
    visualAsset: 'assets/tarot/cards/major/07_chariot.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'major_08',
    number: 8,
    arcana: OraclyTarotArcana.major,
    suit: OraclyTarotSuit.none,
    name: L10nTriple('Güç', 'Strength', 'Сила'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['yumuşak güç', 'sabır', 'merhamet'],
      en: ['gentle force', 'patience', 'mercy'],
      ru: ['мягкая сила', 'терпение', 'милость'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['bastırma', 'öfke', 'özgüvensizlik'],
      en: ['suppression', 'anger', 'self-doubt'],
      ru: ['подавление', 'гнев', 'неуверенность'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Sertliği ezmeden tutan bir cesaret.', 'Courage that holds heat without crushing it.', 'Смелость, которая держит жар, не раздавливая его.'),
      loveMeaning: L10nTriple('İlişkide sabır ve şefkat öne çıkabilir; suskunluk korku da olabilir.', 'Patience and kindness may come forward in a bond; silence can also be fear.', 'В связи могут выйти терпение и тепло; молчание бывает и страхом.'),
      careerMeaning: L10nTriple('Sakin bir dayanıklılık işe yarayabilir; bağırarak yönetmek gerekmez.', 'Quiet endurance may serve work; shouting is not required to lead.', 'Тихая стойкость может служить делу; криком руководить не обязательно.'),
      moneyMeaning: L10nTriple('Sabırlı bir tutum, panik harcamayı yumuşatabilir.', 'A patient stance may soften panic spending.', 'Терпеливая поза может смягчить панические траты.'),
      personalMeaning: L10nTriple('İçerideki sert hayvan, dokunulmayı bekliyor olabilir.', 'The inner fierce animal may be waiting to be touched, not beaten.', 'Внутренний ярый зверь может ждать прикосновения, не побоев.'),
      challengeMeaning: L10nTriple('Güç, kendini küçümsemeye veya başkasını bastırmaya kayabilir.', 'Strength may slide into self-belittling or pressing others down.', 'Сила может стать самоумалением или давлением на других.'),
      guidanceMeaning: L10nTriple('Yumuşak ol; zayıf olma.', 'Be gentle; do not become faint.', 'Будь мягок; не становись слабым.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha merhametli bir dayanıklılık.', 'A possible climate: more merciful endurance.', 'Возможный климат: более милостивая стойкость.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_15', 'major_07', 'wands_09'],
      note: L10nTriple('Şeytan bağlanma, Savaş Arabası yön, Değnek Dokuzu son ateşi taşır.', 'The Devil holds attachment; the Chariot heading; Nine of Wands last fire.', 'Дьявол — привязанность; Колесница — курс; Девятка Жезлов — последний огонь.'),
    ),
    visualAsset: 'assets/tarot/cards/major/08_strength.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'major_09',
    number: 9,
    arcana: OraclyTarotArcana.major,
    suit: OraclyTarotSuit.none,
    name: L10nTriple('Ermiş', 'The Hermit', 'Отшельник'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['yalnızlık', 'ışık', 'arayış'],
      en: ['solitude', 'lamp', 'search'],
      ru: ['одиночество', 'свет', 'поиск'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['kopuş', 'kaçış', 'soğukluk'],
      en: ['cutoff', 'escape', 'coldness'],
      ru: ['отсечение', 'бегство', 'холод'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Tek bir lamba; kalabalığın dışında duran sual.', 'A single lamp; a question standing outside the crowd.', 'Один светильник; вопрос вне толпы.'),
      loveMeaning: L10nTriple('Mesafe bir ihtiyaç olabilir; yokluk ile yalnızlık aynı şey değildir.', 'Distance may be needed; absence and solitude are not the same.', 'Дистанция может быть нужна; отсутствие и одиночество — не одно.'),
      careerMeaning: L10nTriple('Derinleşme, uzmanlaşma veya geri çekilip bakmak mümkün görünür.', 'Going deeper, specializing, or stepping back to look may be possible.', 'Возможно углубление, специальность или шаг назад, чтобы увидеть.'),
      moneyMeaning: L10nTriple('Sadeleşme, gösterişli harcamadan daha sakin durabilir.', 'Simplifying may sit more calmly than showy spending.', 'Упрощение может быть спокойнее показных трат.'),
      personalMeaning: L10nTriple('Cevap dışarıda değil, eldeki küçük ışıkta aranabilir.', 'The answer may be sought in the small light in hand, not outside.', 'Ответ можно искать в малом свете в руке, не вовне.'),
      challengeMeaning: L10nTriple('Yalnızlık, dünyayı reddetmeye dönüşebilir.', 'Solitude may become a refusal of the world.', 'Одиночество может стать отказом от мира.'),
      guidanceMeaning: L10nTriple('Işığı sönmeden yürü; kimseyi peşinden sürükleme.', 'Walk before the lamp fails; do not drag anyone behind you.', 'Иди, пока свет не погас; никого не тащи за собой.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha içe dönük bir aralık.', 'A possible climate: a more inward interval.', 'Возможный климат: более внутренний промежуток.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_02', 'major_18', 'swords_04'],
      note: L10nTriple('Başrahibe ve Ay iç oda; Kılıç Dördü dinlenme payıdır.', 'Priestess and Moon are the inner room; Four of Swords a share of rest.', 'Жрица и Луна — внутренняя комната; Четвёрка Мечей — доля покоя.'),
    ),
    visualAsset: 'assets/tarot/cards/major/09_hermit.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'major_10',
    number: 10,
    arcana: OraclyTarotArcana.major,
    suit: OraclyTarotSuit.none,
    name: L10nTriple('Kader Çarkı', 'Wheel of Fortune', 'Колесо Фортуны'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['döngü', 'değişim', 'tesadüf'],
      en: ['cycle', 'turn', 'chance'],
      ru: ['цикл', 'поворот', 'случай'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['direnç', 'kurban rolü', 'takıntı'],
      en: ['resistance', 'victim role', 'fixation'],
      ru: ['сопротивление', 'роль жертвы', 'зацикленность'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Dönen bir düzen; elde tutulmayan bir ritim.', 'A turning order; a rhythm that cannot be gripped.', 'Вращающийся строй; ритм, который не удержать.'),
      loveMeaning: L10nTriple('İlişkide bir evre değişebilir; bu, sonsuz mutluluk veya yıkım iddiası değildir.', 'A phase in a bond may turn; this is not a claim of endless joy or ruin.', 'Фаза связи может повернуться; это не утверждение вечной радости или краха.'),
      careerMeaning: L10nTriple('Dış koşullar kayabilir; uyum, panikten daha sakin bir yanıt olabilir.', 'Outer conditions may shift; adapting may be calmer than panic.', 'Внешние условия могут сдвинуться; адаптация спокойнее паники.'),
      moneyMeaning: L10nTriple('Gelgit olabilir; tek bir ana bütün anlamı yüklemek ağırdır.', 'Ebb and flow may appear; loading one moment with all meaning is heavy.', 'Могут быть приливы; вешать на один миг весь смысл — тяжело.'),
      personalMeaning: L10nTriple('Kontrol edilemeyen bir dönüş, alçakgönüllülük isteyebilir.', 'An ungoverned turn may ask for humility.', 'Неуправляемый поворот может просить смирения.'),
      challengeMeaning: L10nTriple('Döngü, kadercilik veya suçlama hikâyesine bağlanabilir.', 'The cycle may be bound into fatalism or blame.', 'Цикл может стать историей рока или вины.'),
      guidanceMeaning: L10nTriple('Çarka tutunma; ritmini fark et.', 'Do not cling to the wheel; notice its rhythm.', 'Не цепляйся за колесо; заметь его ритм.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: koşulların yeniden dizilişi — yönü sen seçersin.', 'A possible climate: conditions rearranging — you still choose heading.', 'Возможный климат: перестановка условий — курс всё же выбираешь ты.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_13', 'major_21', 'wands_10'],
      note: L10nTriple('Ölüm boşaltır, Dünya tamamlar, Değnek Onu yük izidir.', 'Death clears; the World completes; Ten of Wands is the load.', 'Смерть очищает; Мир завершает; Десятка Жезлов — ноша.'),
    ),
    visualAsset: 'assets/tarot/cards/major/10_wheel.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
];
