/// ORACLY Tarot catalogue — structured meanings, TR/EN/RU. No UI.
library;

import '../../../../core/l10n/l10n_triple.dart';
import '../oracly_tarot_card.dart';
import '../oracly_tarot_enums.dart';
import '../oracly_tarot_keywords.dart';
import '../oracly_tarot_meanings.dart';
import '../oracly_tarot_relations.dart';

const kOraclyTarotPentacles = <OraclyTarotCard>[
  OraclyTarotCard(
    id: 'pentacles_01',
    number: 1,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.pentacles,
    name: L10nTriple('Tılsım Ası', 'Ace of Pentacles', 'Туз Пентаклей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['tohum', 'madde', 'el'],
      en: ['seed', 'matter', 'hand'],
      ru: ['семя', 'материя', 'рука'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['fırsat kaçırma korkusu', 'açgöz', 'erteleme'],
      en: ['fear of missed chance', 'greed', 'delay'],
      ru: ['страх упущенного шанса', 'жадность', 'отсрочка'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('İlk tohum; henüz bahçe değil.', 'A first seed; not yet a garden.', 'Первое семя; ещё не сад.'),
      loveMeaning: L10nTriple('Bağda somut bir jest belirebilir.', 'A concrete gesture may appear in a bond.', 'В связи может явиться конкретный жест.'),
      careerMeaning: L10nTriple('İş te somut bir başlangıç mümkün görünür.', 'A concrete work beginning may be possible.', 'Возможно конкретное начало дела.'),
      moneyMeaning: L10nTriple('Küçük bir kaynak kapısı aralanabilir.', 'A small door of means may open a little.', 'Может чуть открыться малая дверь средств.'),
      personalMeaning: L10nTriple('İçeride elde tutulabilir bir değer uyanabilir.', 'A value that can be held in the hand may wake inside.', 'Внутри может проснуться ценность, которую можно держать в руке.'),
      challengeMeaning: L10nTriple('Tohum, hemen servet hikâyesine kayabilir.', 'The seed may slide into an instant-fortune story.', 'Семя может стать историей мгновенного богатства.'),
      guidanceMeaning: L10nTriple('Ekle; henüz hasat sayma.', 'Plant; do not count a harvest yet.', 'Посади; ещё не считай урожай.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: maddi bir başlangıç.', 'A possible climate: a material beginning.', 'Возможный климат: материальное начало.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['wands_01', 'major_01', 'pentacles_03'],
      note: L10nTriple('Değnek Ası kıvılcım, Büyücü el, Tılsım Üçlüsü zanaattır.', 'Ace of Wands spark; Magician hand; Three of Pentacles craft.', 'Туз Жезлов — искра; Маг — рука; Тройка Пентаклей — ремесло.'),
    ),
    visualAsset: 'assets/tarot/cards/pentacles/01_ace.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'pentacles_02',
    number: 2,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.pentacles,
    name: L10nTriple('Tılsım İkilisi', 'Two of Pentacles', 'Двойка Пентаклей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['denge', 'jonglör', 'ritim'],
      en: ['balance', 'juggle', 'rhythm'],
      ru: ['равновесие', 'жонглирование', 'ритм'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['dağılma', 'erteleme', 'iki arada kalma'],
      en: ['scatter', 'delay', 'stuck between'],
      ru: ['рассев', 'отсрочка', 'застревание между'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('İki ağırlık arasında dans eden el.', 'A hand dancing between two weights.', 'Рука, танцующая между двумя тяжестями.'),
      loveMeaning: L10nTriple('Bağda tempo ve pratik denge konuşulabilir.', 'Tempo and practical balance may be spoken in a bond.', 'В связи могут говорить о темпе и практической мере.'),
      careerMeaning: L10nTriple('İş te birden fazla iş ritmi belirebilir.', 'More than one work rhythm may appear.', 'Может явиться больше одного рабочего ритма.'),
      moneyMeaning: L10nTriple('Gelir-gider dansı görünür olabilir.', 'A dance of in-and-out means may be visible.', 'Может быть виден танец прихода и расхода.'),
      personalMeaning: L10nTriple('İçeride düşürmeden tutmaya çalışan bir yer olabilir.', 'A place trying to hold without dropping may live inside.', 'Внутри может жить место, которое старается держать, не роняя.'),
      challengeMeaning: L10nTriple('Denge, hiçbirini seçememeye kayabilir.', 'Balance may slide into choosing none.', 'Равновесие может стать неумением выбрать.'),
      guidanceMeaning: L10nTriple('Ritmi tut; her topu parlatma.', 'Keep the rhythm; do not polish every ball.', 'Держи ритм; не полируй каждый шар.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: pratik bir denge aralığı.', 'A possible climate: a practical interval of balance.', 'Возможный климат: практический промежуток равновесия.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_14', 'wands_02', 'cups_02'],
      note: L10nTriple('Denge harman, Değnek ve Kupa ikilileri ufuk ve bağdır.', 'Temperance blend; Twos of Wands and Cups horizon and bond.', 'Умеренность — смесь; Двойки Жезлов и Кубков — горизонт и связь.'),
    ),
    visualAsset: 'assets/tarot/cards/pentacles/02_two.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'pentacles_03',
    number: 3,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.pentacles,
    name: L10nTriple('Tılsım Üçlüsü', 'Three of Pentacles', 'Тройка Пентаклей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['zanaat', 'işbirliği', 'işlik'],
      en: ['craft', 'collaboration', 'workshop'],
      ru: ['ремесло', 'сотрудничество', 'мастерская'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['kıyas', 'yalnız deha', 'özensizlik'],
      en: ['comparison', 'lone genius', 'carelessness'],
      ru: ['сравнение', 'одинокий гений', 'небрежность'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Birlikte örülen iş; alkış değil.', 'Work woven together; not applause.', 'Работа, сплетённая вместе; не аплодисменты.'),
      loveMeaning: L10nTriple('Bağda ortak bir iş belirebilir.', 'A shared task may appear in a bond.', 'В связи может явиться общее дело.'),
      careerMeaning: L10nTriple('İş te zanaat ve geri bildirim öne çıkabilir.', 'Craft and feedback at work may come forward.', 'На работе могут выйти ремесло и обратная связь.'),
      moneyMeaning: L10nTriple('Emeğin değeri konuşulabilir.', 'The worth of labor may be spoken.', 'Могут говорить о цене труда.'),
      personalMeaning: L10nTriple('İçeride \'biz yaptık\' cümlesi ısınabilir.', 'The sentence \'we made this\' may warm inside.', 'Внутри может согреться фраза «мы это сделали».'),
      challengeMeaning: L10nTriple('Zanaat, kıyasa kayabilir.', 'Craft may slide into comparison.', 'Ремесло может стать сравнением.'),
      guidanceMeaning: L10nTriple('İşi güzel yap; vitrine çevirme.', 'Make the work well; do not turn it into a shop window.', 'Сделай работу хорошо; не превращай её в витрину.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha zanaatkâr bir ara.', 'A possible climate: a more craftsmanlike interval.', 'Возможный климат: более ремесленный промежуток.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['wands_03', 'major_05', 'cups_03'],
      note: L10nTriple('Değnek Üçlüsü ufuk, Aziz aidiyet, Kupa Üçlüsü masadır.', 'Three of Wands horizon; Hierophant belonging; Three of Cups table.', 'Тройка Жезлов — горизонт; Иерофант — принадлежность; Тройка Кубков — стол.'),
    ),
    visualAsset: 'assets/tarot/cards/pentacles/03_three.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'pentacles_04',
    number: 4,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.pentacles,
    name: L10nTriple('Tılsım Dörtlüsü', 'Four of Pentacles', 'Четвёрка Пентаклей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['tutma', 'eşik bekçisi', 'kapalı el'],
      en: ['holding', 'threshold guard', 'closed hand'],
      ru: ['удержание', 'страж порога', 'закрытая рука'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['cimrilik', 'korku kasası', 'paylaşamama'],
      en: ['miserliness', 'fear-vault', 'cannot share'],
      ru: ['скупость', 'сейф страха', 'неумение делиться'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Sıkı tutulan tohum; güvenlik ve sıkışma aynı kapıda durur.', 'A tightly held seed; safety and tightness stand at the same door.', 'Туг держанное семя; безопасность и теснота стоят у одной двери.'),
      loveMeaning: L10nTriple('Bağda kontrol veya tutma belirebilir.', 'Control or holding may appear in a bond.', 'В связи может явиться контроль или удержание.'),
      careerMeaning: L10nTriple('İş te kaynak koruma öne çıkabilir.', 'Protecting resources at work may come forward.', 'На работе может выйти защита ресурсов.'),
      moneyMeaning: L10nTriple('Birikim sakin de boğucu da durabilir.', 'Saving may sit calm or suffocating.', 'Накопление может сидеть спокойно или удушающе.'),
      personalMeaning: L10nTriple('İçeride kaybetme korkusu elini kapatabilir.', 'Fear of losing may close the hand inside.', 'Страх потери может закрыть руку внутри.'),
      challengeMeaning: L10nTriple('Tutma, hayatı durdurmaya kayabilir.', 'Holding may slide into stopping life.', 'Удержание может остановить жизнь.'),
      guidanceMeaning: L10nTriple('Koruma; kilitleme.', 'Protect; do not lock.', 'Храни; не запирай.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha tutucu bir güvenlik.', 'A possible climate: more holding safety.', 'Возможный климат: более удерживающая безопасность.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_15', 'wands_04', 'cups_04'],
      note: L10nTriple('Şeytan bağ, Değnek Dördü mola, Kupa Dördü durgunluktur.', 'Devil bind; Four of Wands pause; Four of Cups stillness.', 'Дьявол — связь; Четвёрка Жезлов — пауза; Четвёрка Кубков — застой.'),
    ),
    visualAsset: 'assets/tarot/cards/pentacles/04_four.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'pentacles_05',
    number: 5,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.pentacles,
    name: L10nTriple('Tılsım Beşlisi', 'Five of Pentacles', 'Пятёрка Пентаклей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['yoksunluk', 'eşik dışı', 'soğuk taş'],
      en: ['lack', 'outside the threshold', 'cold stone'],
      ru: ['нехватка', 'вне порога', 'холодный камень'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['utanç', 'yardım reddi', 'yalnızlık zırhı'],
      en: ['shame', 'refusing help', 'armor of aloneness'],
      ru: ['стыд', 'отказ от помощи', 'броня одиночества'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Kapı dışındaki madde; değer yok olmuş değildir.', 'Matter outside the door; worth is not gone.', 'Материя за дверью; ценность не исчезла.'),
      loveMeaning: L10nTriple('Bağda yoksunluk veya dışarıda kalma hissedilebilir.', 'Lack or being left outside may be felt in a bond.', 'В связи может ощущаться нехватка или остаться вовне.'),
      careerMeaning: L10nTriple('İş te güvencesizlik belirebilir.', 'Insecurity at work may appear.', 'На работе может явиться незащищённость.'),
      moneyMeaning: L10nTriple('Maddi daralma görünür olabilir.', 'A material narrowing may be visible.', 'Может быть видно материальное сужение.'),
      personalMeaning: L10nTriple('İçeride utanan bir yoksulluk hissi olabilir.', 'A ashamed sense of poverty may live inside.', 'Внутри может жить стыдящееся чувство бедности.'),
      challengeMeaning: L10nTriple('Yoksunluk, kimliğe kayabilir.', 'Lack may slide into identity.', 'Нехватка может стать личностью.'),
      guidanceMeaning: L10nTriple('Kapıyı gör; gururla donma.', 'See the door; do not freeze in pride.', 'Увидь дверь; не замёрзни в гордости.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha çıplak bir ihtiyaç.', 'A possible climate: a barer need.', 'Возможный климат: более голая нужда.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['cups_05', 'major_16', 'swords_05'],
      note: L10nTriple('Kupa Beşlisi yas, Kule çatlak, Kılıç Beşlisi boş zaferdir.', 'Five of Cups mourning; Tower crack; Five of Swords hollow win.', 'Пятёрка Кубков — траур; Башня — трещина; Пятёрка Мечей — пустая победа.'),
    ),
    visualAsset: 'assets/tarot/cards/pentacles/05_five.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'pentacles_06',
    number: 6,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.pentacles,
    name: L10nTriple('Tılsım Altılısı', 'Six of Pentacles', 'Шестёрка Пентаклей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['pay', 'veriş', 'terazi'],
      en: ['share', 'giving', 'scales'],
      ru: ['доля', 'даяние', 'весы'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['üstten bakış', 'borçlandırma', 'dengesiz cömertlik'],
      en: ['looking down', 'indebting', 'uneven generosity'],
      ru: ['взгляд сверху', 'одалживание виной', 'неровная щедрость'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Verilen ve alınan madde; merhamet vitrini değil.', 'Matter given and received; not a display of mercy.', 'Материя данная и принятая; не витрина милости.'),
      loveMeaning: L10nTriple('Bağda alma-verme ritmi konuşulabilir.', 'A rhythm of giving and receiving may be spoken in a bond.', 'В связи могут говорить о ритме давать и принимать.'),
      careerMeaning: L10nTriple('İş te adil pay gündeme gelebilir.', 'A fair share at work may come forward.', 'На работе может выйти справедливая доля.'),
      moneyMeaning: L10nTriple('Yardım ve borç aynı şey değildir.', 'Help and debt are not the same.', 'Помощь и долг — не одно.'),
      personalMeaning: L10nTriple('İçeride hem veren hem alan bir el olabilir.', 'A hand both giving and receiving may live inside.', 'Внутри может жить рука и дающая, и принимающая.'),
      challengeMeaning: L10nTriple('Pay, güç oyununa kayabilir.', 'Share may slide into a power game.', 'Доля может стать игрой силы.'),
      guidanceMeaning: L10nTriple('Ver; küçük düşürme.', 'Give; do not diminish.', 'Дай; не унижай.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha ölçülü bir paylaşım.', 'A possible climate: more measured sharing.', 'Возможный климат: более мерное разделение.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_11', 'cups_06', 'wands_06'],
      note: L10nTriple('Adalet ölçü, Kupa Altılısı hatıra, Değnek Altılısı geçiştir.', 'Justice measure; Six of Cups memory; Six of Wands crossing.', 'Справедливость — мера; Шестёрка Кубков — память; Шестёрка Жезлов — переход.'),
    ),
    visualAsset: 'assets/tarot/cards/pentacles/06_six.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'pentacles_07',
    number: 7,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.pentacles,
    name: L10nTriple('Tılsım Yedilisi', 'Seven of Pentacles', 'Семёрка Пентаклей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['bekleyiş', 'ekim', 'sabır'],
      en: ['waiting', 'sowing', 'patience'],
      ru: ['ожидание', 'посев', 'терпение'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['sabırsızlık', 'emeği küçümseme', 'erken hasat'],
      en: ['impatience', 'scorning labor', 'early harvest'],
      ru: ['нетерпение', 'пренебрежение трудом', 'ранний урожай'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Henüz olgunlaşmamış bahçe.', 'A garden not yet ripe.', 'Сад, ещё не зрелый.'),
      loveMeaning: L10nTriple('Bağda emek ve zaman konuşulabilir.', 'Labor and time may be spoken in a bond.', 'В связи могут говорить о труде и времени.'),
      careerMeaning: L10nTriple('İş te sonuç beklemek yorucu olabilir.', 'Waiting for a work result may tire.', 'На работе ожидание результата может утомить.'),
      moneyMeaning: L10nTriple('Yatırım henüz meyve vermemiş görünebilir.', 'An investment may look unripe.', 'Вложение может казаться незрелым.'),
      personalMeaning: L10nTriple('İçeride sabır isteyen bir çiftçi olabilir.', 'A farmer asking for patience may live inside.', 'Внутри может жить земледелец, просящий терпения.'),
      challengeMeaning: L10nTriple('Bekleyiş, pişmanlığa kayabilir.', 'Waiting may slide into regret.', 'Ожидание может стать сожалением.'),
      guidanceMeaning: L10nTriple('Bahçeyi izle; sökme.', 'Watch the garden; do not pull it up.', 'Смотри сад; не вырывай.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha sabırlı bir emek.', 'A possible climate: more patient labor.', 'Возможный климат: более терпеливый труд.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_14', 'wands_07', 'swords_07'],
      note: L10nTriple('Denge tempo, Değnek Yedilisi duruş, Kılıç Yedilisi kayıştır.', 'Temperance pacing; Seven of Wands stance; Seven of Swords slip.', 'Умеренность — темп; Семёрка Жезлов — стойка; Семёрка Мечей — скольжение.'),
    ),
    visualAsset: 'assets/tarot/cards/pentacles/07_seven.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'pentacles_08',
    number: 8,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.pentacles,
    name: L10nTriple('Tılsım Sekizlisi', 'Eight of Pentacles', 'Восьмёрка Пентаклей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['ustalık', 'tekrar', 'işlik disiplini'],
      en: ['mastery', 'repetition', 'workshop discipline'],
      ru: ['мастерство', 'повторение', 'дисциплина мастерской'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['mekaniklik', 'tükenme', 'anlamsız tekrar'],
      en: ['mechanics', 'depletion', 'empty repetition'],
      ru: ['механика', 'истощение', 'пустое повторение'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Tekrarlanan el; sanatın sessiz hali.', 'The repeating hand; the quiet form of art.', 'Повторяющаяся рука; тихий вид искусства.'),
      loveMeaning: L10nTriple('Bağda emekle kurulan güven belirebilir.', 'Trust built by labor may appear in a bond.', 'В связи может явиться доверие, построенное трудом.'),
      careerMeaning: L10nTriple('İş te ustalık yolu öne çıkabilir.', 'A path of mastery at work may come forward.', 'На работе может выйти путь мастерства.'),
      moneyMeaning: L10nTriple('Düzenli emek, spekülasyondan ayrı durur.', 'Regular labor sits apart from speculation.', 'Регулярный труд стоит отдельно от догадки.'),
      personalMeaning: L10nTriple('İçeride çalışan sessiz bir zanaatkâr olabilir.', 'A quiet craftsperson at work may live inside.', 'Внутри может жить тихий ремесленник за работой.'),
      challengeMeaning: L10nTriple('Disiplin, hayatı işe indirgeyebilir.', 'Discipline may reduce life to work.', 'Дисциплина может свести жизнь к работе.'),
      guidanceMeaning: L10nTriple('Tekrar et; kendini yok etme.', 'Repeat; do not erase yourself.', 'Повторяй; не стирай себя.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha ustaca bir emek.', 'A possible climate: more masterful labor.', 'Возможный климат: более мастерский труд.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_01', 'wands_08', 'pentacles_03'],
      note: L10nTriple('Büyücü el, Değnek Sekizlisi hız, Tılsım Üçlüsü işliktir.', 'Magician hand; Eight of Wands speed; Three of Pentacles workshop.', 'Маг — рука; Восьмёрка Жезлов — скорость; Тройка Пентаклей — мастерская.'),
    ),
    visualAsset: 'assets/tarot/cards/pentacles/08_eight.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'pentacles_09',
    number: 9,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.pentacles,
    name: L10nTriple('Tılsım Dokuzlusu', 'Nine of Pentacles', 'Девятка Пентаклей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['yeterlilik', 'bahçe', 'kendi emeği'],
      en: ['enough-ness', 'garden', 'one\'s own labor'],
      ru: ['достаточность', 'сад', 'свой труд'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['yalnız refah', 'gösteriş', 'kapalı bahçe'],
      en: ['lone plenty', 'display', 'closed garden'],
      ru: ['одинокое изобилие', 'показ', 'закрытый сад'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Kendi emeğinin bahçesi; vitrin değil.', 'The garden of one\'s labor; not a shop window.', 'Сад своего труда; не витрина.'),
      loveMeaning: L10nTriple('Bağda bağımsız bir olgunluk belirebilir.', 'An independent maturity may appear in a bond.', 'В связи может явиться независимая зрелость.'),
      careerMeaning: L10nTriple('İş te kişisel yeterlilik hissedilebilir.', 'Personal enough-ness at work may be felt.', 'На работе может ощущаться личная достаточность.'),
      moneyMeaning: L10nTriple('Kazancın sakin hali mümkün görünür.', 'The calm form of earning may be possible.', 'Возможен спокойный вид заработка.'),
      personalMeaning: L10nTriple('İçeride \'ben yaptım\' diyen sakin bir gurur olabilir.', 'A calm pride saying \'I made this\' may live inside.', 'Внутри может жить спокойная гордость «я это сделал».'),
      challengeMeaning: L10nTriple('Bahçe, başkasını dışarıda bırakmaya kayabilir.', 'The garden may slide into leaving others out.', 'Сад может начать оставлять других вовне.'),
      guidanceMeaning: L10nTriple('Bahçede dur; kapıyı kilitleme.', 'Stand in the garden; do not lock the gate.', 'Стой в саду; не запирай калитку.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha kendi emeğine yaslanan bir ara.', 'A possible climate: an interval leaning on one\'s own labor.', 'Возможный климат: промежуток с опорой на свой труд.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['cups_09', 'major_17', 'wands_09'],
      note: L10nTriple('Kupa Dokuzu iç doyum, Yıldız sakin ışık, Değnek Dokuzu nöbettir.', 'Nine of Cups inner enough; Star quiet light; Nine of Wands watch.', 'Девятка Кубков — внутренняя достаточность; Звезда — тихий свет; Девятка Жезлов — дозор.'),
    ),
    visualAsset: 'assets/tarot/cards/pentacles/09_nine.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'pentacles_10',
    number: 10,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.pentacles,
    name: L10nTriple('Tılsım Onlusu', 'Ten of Pentacles', 'Десятка Пентаклей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['soy', 'kalıcı masa', 'kök varlık'],
      en: ['lineage', 'lasting table', 'rooted means'],
      ru: ['род', 'долгий стол', 'укоренённые средства'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['miras baskısı', 'vitrin aile', 'kapanmayan hesap'],
      en: ['heritage pressure', 'display family', 'unclosed account'],
      ru: ['давление наследия', 'витринная семья', 'незакрытый счёт'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Zamanın içindeki madde; bir ömürlük vitrin değil.', 'Matter inside time; not a lifelong shop window.', 'Материя внутри времени; не пожизненная витрина.'),
      loveMeaning: L10nTriple('Bağda kök ve gelecek kuşak konuşulabilir.', 'Roots and a coming generation may be spoken in a bond.', 'В связи могут говорить о корнях и грядущем поколении.'),
      careerMeaning: L10nTriple('İş te kalıcı bir yapı belirebilir.', 'A lasting structure at work may appear.', 'На работе может явиться долгий строй.'),
      moneyMeaning: L10nTriple('Kalıcı varlık, gösterişten ayrı durur.', 'Lasting means sit apart from display.', 'Долгие средства стоят отдельно от показа.'),
      personalMeaning: L10nTriple('İçeride bir soya ait olma ısınabilir.', 'Belonging to a lineage may warm inside.', 'Внутри может согреться принадлежность к роду.'),
      challengeMeaning: L10nTriple('Soy, kişiyi ezmeye kayabilir.', 'Lineage may slide into crushing the person.', 'Род может начать давить человека.'),
      guidanceMeaning: L10nTriple('Kökünü gör; tapınağa çevirme.', 'See your root; do not turn it into a temple.', 'Увидь корень; не превращай его в храм.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha köklü bir maddi duruş.', 'A possible climate: a more rooted material stance.', 'Возможный климат: более укоренённая материальная поза.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['cups_10', 'major_21', 'wands_10'],
      note: L10nTriple('Kupa Onu masa, Dünya tamamlanma, Değnek Onu yük izidir.', 'Ten of Cups table; World completion; Ten of Wands load.', 'Десятка Кубков — стол; Мир — завершение; Десятка Жезлов — ноша.'),
    ),
    visualAsset: 'assets/tarot/cards/pentacles/10_ten.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'pentacles_11',
    number: 11,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.pentacles,
    name: L10nTriple('Tılsım Habercisi', 'Page of Pentacles', 'Паж Пентаклей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['öğrenci el', 'pratik merak', 'tohum haberi'],
      en: ['student hand', 'practical curiosity', 'seed-news'],
      ru: ['рука ученика', 'практическое любопытство', 'весть семени'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['savurgan çırak', 'öğrenmeme', 'acele ustalık'],
      en: ['wasteful apprentice', 'not learning', 'hasty mastery'],
      ru: ['расточительный ученик', 'не учиться', 'поспешное мастерство'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Maddenin habercisi; tüccar değil.', 'Messenger of matter; not a merchant.', 'Вестник материи; не купец.'),
      loveMeaning: L10nTriple('Bağda pratik bir öğrenme belirebilir.', 'Practical learning may appear in a bond.', 'В связи может явиться практическое учение.'),
      careerMeaning: L10nTriple('İş te çıraklık kapısı aralanabilir.', 'A door of apprenticeship at work may open a little.', 'На работе может чуть открыться дверь ученичества.'),
      moneyMeaning: L10nTriple('Küçük bir maddi ders gelebilir.', 'A small material lesson may come.', 'Может прийти малый материальный урок.'),
      personalMeaning: L10nTriple('İçeride elini işe sürmek isteyen bir yer olabilir.', 'A place wanting to put the hand to work may live inside.', 'Внутри может жить место, желающее приложить руку к делу.'),
      challengeMeaning: L10nTriple('Öğrenci, her şeyi spekülasyona kaydırabilir.', 'The student may slide everything into speculation.', 'Ученик может всё сдвинуть в догадку.'),
      guidanceMeaning: L10nTriple('Elle öğren; zengin numarası yapma.', 'Learn by hand; do not perform wealth.', 'Учись рукой; не играй богатство.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha pratik bir merak.', 'A possible climate: more practical curiosity.', 'Возможный климат: более практическое любопытство.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['wands_11', 'cups_11', 'swords_11'],
      note: L10nTriple('Üç Haberci ateş, su ve havadır; bu el topraktadır.', 'The three Pages are fire, water, air; this hand is in earth.', 'Три Пажа — огонь, вода, воздух; эта рука в земле.'),
    ),
    visualAsset: 'assets/tarot/cards/pentacles/11_page.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'pentacles_12',
    number: 12,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.pentacles,
    name: L10nTriple('Tılsım Şövalyesi', 'Knight of Pentacles', 'Рыцарь Пентаклей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['yavaş yol', 'sürülmüş tarla', 'sebat'],
      en: ['slow road', 'ploughed field', 'steadfastness'],
      ru: ['медленная дорога', 'вспаханное поле', 'стойкость'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['inat', 'hareketsizlik', 'fırsat körlüğü'],
      en: ['stubbornness', 'immobility', 'blind to opening'],
      ru: ['упрямство', 'неподвижность', 'слепота к отверстию'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Tarla temposunda giden madde.', 'Matter traveling at field-tempo.', 'Материя, идущая темпом поля.'),
      loveMeaning: L10nTriple('Bağda yavaş ve sadık bir ritim belirebilir.', 'A slow faithful rhythm may appear in a bond.', 'В связи может явиться медленный верный ритм.'),
      careerMeaning: L10nTriple('İş te sebat, hızdan daha sakin durabilir.', 'Steadfastness at work may sit calmer than speed.', 'На работе стойкость может сидеть спокойнее скорости.'),
      moneyMeaning: L10nTriple('Yavaş birikim mümkün görünür.', 'Slow accumulation may be possible.', 'Возможно медленное накопление.'),
      personalMeaning: L10nTriple('İçeride acele etmeyen bir öküz olabilir.', 'An ox that does not hurry may live inside.', 'Внутри может жить вол, который не спешит.'),
      challengeMeaning: L10nTriple('Sebat, donmaya kayabilir.', 'Steadfastness may slide into freeze.', 'Стойкость может стать заморозкой.'),
      guidanceMeaning: L10nTriple('Sür; yarış atı olma.', 'Plough; do not become a racehorse.', 'Паши; не становись скакуном.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha yavaş bir madde yolu.', 'A possible climate: a slower road of matter.', 'Возможный климат: более медленная дорога материи.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_14', 'wands_12', 'cups_12'],
      note: L10nTriple('Denge tempo, Değnek ve Kupa Şövalyeleri ateş ve su yoludur.', 'Temperance pacing; Knights of Wands and Cups fire- and water-roads.', 'Умеренность — темп; Рыцари Жезлов и Кубков — дороги огня и воды.'),
    ),
    visualAsset: 'assets/tarot/cards/pentacles/12_knight.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'pentacles_13',
    number: 13,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.pentacles,
    name: L10nTriple('Tılsım Kraliçesi', 'Queen of Pentacles', 'Королева Пентаклей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['bereketli ev', 'pratik şefkat', 'bahçe hanımı'],
      en: ['fertile house', 'practical care', 'garden host'],
      ru: ['плодородный дом', 'практическая забота', 'хозяйка сада'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['kontrol ev', 'cimrilik', 'gösteriş bakımı'],
      en: ['control-house', 'miserliness', 'display care'],
      ru: ['дом-контроль', 'скупость', 'показная забота'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Evi madden tutan olgun el.', 'A mature hand that holds a house in matter.', 'Зрелая рука, держащая дом в материи.'),
      loveMeaning: L10nTriple('Bağda pratik bakım belirebilir.', 'Practical care may appear in a bond.', 'В связи может явиться практическая забота.'),
      careerMeaning: L10nTriple('İş te kaynak yönetimi sakin durabilir.', 'Resource stewardship at work may sit calmly.', 'На работе управление ресурсами может сидеть спокойно.'),
      moneyMeaning: L10nTriple('Ev ekonomisi konuşulabilir.', 'A household economy may be spoken.', 'Могут говорить о домашнем хозяйстве.'),
      personalMeaning: L10nTriple('İçeride hem cömert hem ölçülü bir ev sahibi olabilir.', 'A host both generous and measured may live inside.', 'Внутри может жить хозяин и щедрый, и мерный.'),
      challengeMeaning: L10nTriple('Bakım, kontrol evine kayabilir.', 'Care may slide into a house of control.', 'Забота может стать домом контроля.'),
      guidanceMeaning: L10nTriple('Evi tut; kilitleme.', 'Hold the house; do not lock it.', 'Держи дом; не запирай.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha bereketli bir pratik.', 'A possible climate: a more fertile practice.', 'Возможный климат: более плодородная практика.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_03', 'cups_13', 'pentacles_14'],
      note: L10nTriple('İmparatoriçe bakım, Kupa Kraliçesi deniz, Tılsım Kralı madde yönüdür.', 'Empress care; Queen of Cups sea; King of Pentacles matter-heading.', 'Императрица — забота; Королева Кубков — море; Король Пентаклей — курс материи.'),
    ),
    visualAsset: 'assets/tarot/cards/pentacles/13_queen.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'pentacles_14',
    number: 14,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.pentacles,
    name: L10nTriple('Tılsım Kralı', 'King of Pentacles', 'Король Пентаклей'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['köklü varlık', 'sorumlu madde', 'bahçe kralı'],
      en: ['rooted means', 'responsible matter', 'garden king'],
      ru: ['укоренённые средства', 'ответственная материя', 'король сада'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['statü putu', 'katılık', 'cömert olmayan zenginlik'],
      en: ['idol of status', 'rigidity', 'ungenerous wealth'],
      ru: ['кумир статуса', 'жёсткость', 'нещедрое богатство'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Maddeyi sorumlu tutan duruş.', 'A stance that holds matter responsibly.', 'Поза, ответственно держащая материю.'),
      loveMeaning: L10nTriple('Bağda güvenlik ve olgunluk öne çıkabilir.', 'Safety and maturity may come forward in a bond.', 'В связи могут выйти безопасность и зрелость.'),
      careerMeaning: L10nTriple('İş te kalıcı sorumluluk konuşulabilir.', 'Lasting responsibility at work may be spoken.', 'На работе могут говорить о долгой ответственности.'),
      moneyMeaning: L10nTriple('Varlık, vitrin olmadan durabilir.', 'Means may stand without a shop window.', 'Средства могут стоять без витрины.'),
      personalMeaning: L10nTriple('İçeride hem cömert hem sağlam bir yetişkin olabilir.', 'An adult both generous and solid may live inside.', 'Внутри может жить взрослый и щедрый, и крепкий.'),
      challengeMeaning: L10nTriple('Varlık, insanı ezmeye kayabilir.', 'Means may slide into crushing a person.', 'Средства могут начать давить человека.'),
      guidanceMeaning: L10nTriple('Kökle; tahtı putlaştırma.', 'Take root; do not worship the throne.', 'Укоренись; не делай трон кумиром.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha sorumlu bir madde.', 'A possible climate: more responsible matter.', 'Возможный климат: более ответственная материя.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_04', 'wands_14', 'cups_14'],
      note: L10nTriple('İмparator yapı, Değnek ve Kupa Kralları ateş ve su yönüdür.', 'Emperor structure; Kings of Wands and Cups fire and water heading.', 'Император — строй; Короли Жезлов и Кубков — курс огня и воды.'),
    ),
    visualAsset: 'assets/tarot/cards/pentacles/14_king.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
];
