/// ORACLY Tarot catalogue — structured meanings, TR/EN/RU. No UI.
library;

import '../../../../core/l10n/l10n_triple.dart';
import '../oracly_tarot_card.dart';
import '../oracly_tarot_enums.dart';
import '../oracly_tarot_keywords.dart';
import '../oracly_tarot_meanings.dart';
import '../oracly_tarot_relations.dart';

const kOraclyTarotWands = <OraclyTarotCard>[
  OraclyTarotCard(
    id: 'wands_01',
    number: 1,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.wands,
    name: L10nTriple('Değnek Ası', 'Ace of Wands', 'Туз Жезлов'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['kıvılcım', 'niyet', 'hareket'],
      en: ['spark', 'intent', 'motion'],
      ru: ['искра', 'намерение', 'движение'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['sönme', 'dağılma', 'erte'],
      en: ['dulling', 'scatter', 'defer'],
      ru: ['угасание', 'рассев', 'откладывание'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('İlk kıvılcım; henüz biçim almamış irade.', 'A first spark; will not yet shaped.', 'Первая искра; воля ещё без формы.'),
      loveMeaning: L10nTriple('Bağda taze bir cesaret belirebilir; alevi dayatmak gerekmez.', 'Fresh courage may appear in a bond; the flame need not be forced.', 'В связи может явиться свежая смелость; пламя не нужно навязывать.'),
      careerMeaning: L10nTriple('Yeni bir iş kıvılcımı mümkün görünür.', 'A new spark of work may be possible.', 'Возможна новая искра дела.'),
      moneyMeaning: L10nTriple('Küçük bir yatırım niyeti uyanabilir; tüm kaynağı yakmak değildir.', 'A small intent to invest may stir; this is not burning the whole store.', 'Может проснуться малое намерение вложить; это не сжечь весь запас.'),
      personalMeaning: L10nTriple('İçeride \'şimdi\' diyen bir ısı hissedilebilir.', 'An inner heat that says \'now\' may be felt.', 'Внутри может ощущаться жар, говорящий «сейчас».'),
      challengeMeaning: L10nTriple('Kıvılcım, plansız yangına kayabilir.', 'The spark may slide into a fire without a plan.', 'Искра может стать пожаром без плана.'),
      guidanceMeaning: L10nTriple('Küçük tut; söndürme, savurma.', 'Keep it small; do not snuff it, do not fling it.', 'Держи малым; не гаси и не разбрасывай.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: bir başlangıç ısısı.', 'A possible climate: the heat of a beginning.', 'Возможный климат: тепло начала.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_00', 'major_01', 'cups_01'],
      note: L10nTriple('Deli eşik, Büyücü el, Kupa Ası duygu kıvılcımıdır.', 'Fool is threshold; Magician the hand; Ace of Cups a spark of feeling.', 'Шут — порог; Маг — рука; Туз Кубков — искра чувства.'),
    ),
    visualAsset: 'assets/tarot/cards/wands/01_ace.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'wands_02',
    number: 2,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.wands,
    name: L10nTriple('Değnek İkilisi', 'Two of Wands', 'Двойка Жезлов'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['iki yol', 'bekleme', 'ufuk'],
      en: ['two paths', 'waiting', 'horizon'],
      ru: ['два пути', 'ожидание', 'горизонт'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['kararsızlık', 'acele seçim', 'kayıtsızlık'],
      en: ['indecision', 'hasty pick', 'apathy'],
      ru: ['нерешительность', 'поспешный выбор', 'апатия'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('İki ufuk arasında duran ateş; henüz adım değil.', 'Fire standing between two horizons; not yet a step.', 'Огонь между двумя горизонтами; ещё не шаг.'),
      loveMeaning: L10nTriple('İlişkide iki tempo çatışabilir; birini ezmek gerekmez.', 'Two tempos may clash in a bond; one need not crush the other.', 'В связи могут столкнуться два темпа; один не обязан давить другой.'),
      careerMeaning: L10nTriple('İki iş yolu görünüyor olabilir; seçim henüz zorunlu değildir.', 'Two work paths may be in view; a choice is not yet required.', 'Могут быть видны два пути дела; выбор ещё не обязателен.'),
      moneyMeaning: L10nTriple('İki harcama yönü belirebilir; ikisini birden kovalamak yorucu olabilir.', 'Two spending headings may appear; chasing both can tire.', 'Могут явиться два курса трат; гнаться за обоими утомляет.'),
      personalMeaning: L10nTriple('İçeride bekleyen bir irade, manzarayı izliyor olabilir.', 'A waiting will inside may be watching the view.', 'Внутри ждущая воля может смотреть на вид.'),
      challengeMeaning: L10nTriple('Bekleyiş, kaçış gibi giyinebilir.', 'Waiting may dress as escape.', 'Ожидание может одеться бегством.'),
      guidanceMeaning: L10nTriple('Ufka bak; henüz atlama.', 'Look at the horizon; do not leap yet.', 'Смотри на горизонт; ещё не прыгай.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: seçimden önceki duruş.', 'A possible climate: a stance before choosing.', 'Возможный климат: поза до выбора.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_06', 'swords_02', 'pentacles_02'],
      note: L10nTriple('Aşıklar değer seçer; Kılıç ve Tılsım ikilileri mesafe ve denge izidir.', 'Lovers choose value; Twos of Swords and Pentacles hold distance and balance.', 'Влюблённые выбирают ценность; Двойки Мечей и Пентаклей — дистанция и равновесие.'),
    ),
    visualAsset: 'assets/tarot/cards/wands/02_two.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'wands_03',
    number: 3,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.wands,
    name: L10nTriple('Değnek Üçlüsü', 'Three of Wands', 'Тройка Жезлов'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['büyüme', 'ufuk', 'ilk meyve'],
      en: ['growth', 'horizon', 'first fruit'],
      ru: ['рост', 'горизонт', 'первый плод'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['sabırsızlık', 'dağılma', 'övünç'],
      en: ['impatience', 'scatter', 'boast'],
      ru: ['нетерпение', 'рассев', 'похвальба'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('İlk görünür büyüme; henüz hasat değil.', 'First visible growth; not yet a harvest.', 'Первый видимый рост; ещё не урожай.'),
      loveMeaning: L10nTriple('Bağda küçük bir ilerleme hissedilebilir.', 'A small advance in a bond may be felt.', 'В связи может ощущаться малое продвижение.'),
      careerMeaning: L10nTriple('Emeğin ilk işareti işte belirebilir.', 'The first sign of effort may appear at work.', 'На работе может явиться первый знак усилия.'),
      moneyMeaning: L10nTriple('Küçük bir kazanç umudu belirebilir; şişirme değildir.', 'A small hope of gain may appear; it is not inflation.', 'Может явиться малая надежда на прибыль; это не раздувание.'),
      personalMeaning: L10nTriple('İçeride bu işliyor diyen sessiz bir ısı olabilir.', 'A quiet heat that says this is working may live inside.', 'Внутри может жить тихий жар, что это работает.'),
      challengeMeaning: L10nTriple('Büyüme, acele zafer hikâyesine kayabilir.', 'Growth may slide into a hasty victory story.', 'Рост может стать историей поспешной победы.'),
      guidanceMeaning: L10nTriple('Ufka bak; henüz taç giyme.', 'Look to the horizon; do not crown yourself yet.', 'Смотри на горизонт; ещё не коронуй себя.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: görünür bir genişleme.', 'A possible climate: a visible widening.', 'Возможный климат: видимое расширение.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['wands_01', 'pentacles_03', 'major_07'],
      note: L10nTriple('As kıvılcım, Tılsım Üçlüsü zanaat, Savaş Arabası yön izidir.', 'Ace is spark; Three of Pentacles craft; Chariot heading.', 'Туз — искра; Тройка Пентаклей — ремесло; Колесница — курс.'),
    ),
    visualAsset: 'assets/tarot/cards/wands/03_three.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'wands_04',
    number: 4,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.wands,
    name: L10nTriple('Değnek Dörtlüsü', 'Four of Wands', 'Четвёрка Жезлов'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['eşik kutlaması', 'kök', 'mola'],
      en: ['threshold feast', 'root', 'pause'],
      ru: ['праздник порога', 'корень', 'пауза'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['erken kutlama', 'dağılma', 'yerleşememe'],
      en: ['early feast', 'scatter', 'unsettled'],
      ru: ['ранний праздник', 'рассев', 'неустроенность'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Ateşin ev eşiğinde durması; bir ara nefes.', 'Fire pausing at a household threshold; an interval of breath.', 'Огонь у порога дома; промежуток дыхания.'),
      loveMeaning: L10nTriple('Bağda sakin bir paylaşım belirebilir.', 'A calm sharing may appear in a bond.', 'В связи может явиться спокойное разделение.'),
      careerMeaning: L10nTriple('Bir aşamanın tanınması mümkün görünür.', 'Recognition of a stage may be possible.', 'Возможно признание этапа.'),
      moneyMeaning: L10nTriple('Kaynakları bir masada tutmak sakinleştirir; savurmak değil.', 'Holding resources at one table steadies; scattering them does not.', 'Держать средства за одним столом спокойнее, чем разбрасывать.'),
      personalMeaning: L10nTriple('İçeride burada durabilirim hissi uyanabilir.', 'An inner sense of I can rest here may stir.', 'Внутри может проснуться чувство, что здесь можно стоять.'),
      challengeMeaning: L10nTriple('Mola, durağanlığa kayabilir.', 'The pause may slide into stagnation.', 'Пауза может стать застоем.'),
      guidanceMeaning: L10nTriple('Kutla; henüz yol bitti deme.', 'Mark the moment; do not say the road is finished.', 'Отметь миг; не говори, что путь кончен.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: köklenen bir ara.', 'A possible climate: a rooted interval.', 'Возможный климат: укоренённый промежуток.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['cups_04', 'major_21', 'pentacles_04'],
      note: L10nTriple('Kupa Dördü durgunluk, Dünya tamamlanma, Tılsım Dördü tutma izidir.', 'Four of Cups stillness; World completion; Four of Pentacles holding.', 'Четвёрка Кубков — застой; Мир — завершение; Четвёрка Пентаклей — удержание.'),
    ),
    visualAsset: 'assets/tarot/cards/wands/04_four.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'wands_05',
    number: 5,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.wands,
    name: L10nTriple('Değnek Beşlisi', 'Five of Wands', 'Пятёрка Жезлов'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['sınav', 'sürtünme', 'onur'],
      en: ['trial', 'friction', 'honor'],
      ru: ['испытание', 'трение', 'честь'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['yenilgi hikâyesi', 'öfke', 'vazgeçiş'],
      en: ['defeat-story', 'anger', 'giving up'],
      ru: ['история поражения', 'гнев', 'сдача'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Kıvılcımın sınandığı yer; kaybolmuş değildir.', 'Where the spark is tested; it is not gone.', 'Место испытания искры; она не исчезла.'),
      loveMeaning: L10nTriple('Bağda bir gerilim onur meselesine dönebilir.', 'Tension in a bond may turn into a matter of honor.', 'Напряжение в связи может стать делом чести.'),
      careerMeaning: L10nTriple('İş yerinde bir direnç hissedilebilir.', 'Resistance at work may be felt.', 'На работе может ощущаться сопротивление.'),
      moneyMeaning: L10nTriple('Kaynak gerilimi, savaş gibi okunmamalıdır.', 'A resource strain need not be read as a war.', 'Натяжение средств не обязательно читать как войну.'),
      personalMeaning: L10nTriple('İçeride \'hâlâ ayaktayım\' diyen bir ateş olabilir.', 'An inner fire saying \'I am still standing\' may be present.', 'Внутри может быть огонь «я ещё стою».'),
      challengeMeaning: L10nTriple('Sınav, düşman hikâyesine kayabilir.', 'The trial may slide into an enemy story.', 'Испытание может стать историей врага.'),
      guidanceMeaning: L10nTriple('Onurunu koru; kimseyi yakma.', 'Keep your honor; do not burn anyone.', 'Храни честь; никого не сжигай.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: sürtünmeli bir ara.', 'A possible climate: an interval of friction.', 'Возможный климат: промежуток трения.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['swords_05', 'major_08', 'wands_07'],
      note: L10nTriple('Kılıç Beşlisi zihin çatışması, Güç merhamet, Değnek Yedilisi duruştur.', 'Five of Swords is mental clash; Strength mercy; Seven of Wands stance.', 'Пятёрка Мечей — умственный спор; Сила — милость; Семёрка Жезлов — стойка.'),
    ),
    visualAsset: 'assets/tarot/cards/wands/05_five.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'wands_06',
    number: 6,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.wands,
    name: L10nTriple('Değnek Altılısı', 'Six of Wands', 'Шестёрка Жезлов'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['geçiş', 'tanıma', 'nefes'],
      en: ['crossing', 'notice', 'breath'],
      ru: ['переход', 'признание', 'дыхание'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['övünç', 'geçmişe takılma', 'sahne'],
      en: ['boast', 'stuck in past', 'stage'],
      ru: ['похвальба', 'застрять в прошлом', 'сцена'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Bir eşiği geçmiş ateş; henüz sonsuz zafer değil.', 'Fire that has crossed a threshold; not endless triumph.', 'Огонь, перешедший порог; не вечная победа.'),
      loveMeaning: L10nTriple('Bağda bir yumuşama veya görünürlük belirebilir.', 'Softening or visibility may appear in a bond.', 'В связи может явиться смягчение или видимость.'),
      careerMeaning: L10nTriple('Emeğin fark edilmesi mümkün görünür.', 'Effort being noticed may be possible.', 'Возможно, усилие заметят.'),
      moneyMeaning: L10nTriple('Küçük bir rahatlama hissi gelebilir.', 'A small ease around means may arrive.', 'Может прийти малое облегчение вокруг средств.'),
      personalMeaning: L10nTriple('İçeride omuzların inmesi hissedilebilir.', 'Shoulders dropping may be felt inside.', 'Внутри может ощущаться, как опускаются плечи.'),
      challengeMeaning: L10nTriple('Geçiş, sahne alkışına bağlanabilir.', 'The crossing may be bound to staged applause.', 'Переход может привязаться к сценическим аплодисментам.'),
      guidanceMeaning: L10nTriple('Geçtiğini fark et; taht kurma.', 'Notice that you crossed; do not build a throne.', 'Заметь, что перешёл; не строй трон.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha açık bir geçit.', 'A possible climate: a clearer passage.', 'Возможный климат: более ясный проход.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['cups_06', 'major_19', 'pentacles_06'],
      note: L10nTriple('Kupa Altılısı hatıra, Güneş görünürlük, Tılsım Altılısı paylaşım izidir.', 'Six of Cups memory; Sun visibility; Six of Pentacles sharing.', 'Шестёрка Кубков — память; Солнце — видимость; Шестёрка Пентаклей — делёж.'),
    ),
    visualAsset: 'assets/tarot/cards/wands/06_six.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'wands_07',
    number: 7,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.wands,
    name: L10nTriple('Değnek Yedilisi', 'Seven of Wands', 'Семёрка Жезлов'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['duruş', 'sınır', 'tek başına ateş'],
      en: ['stance', 'boundary', 'fire alone'],
      ru: ['стойка', 'граница', 'огонь в одиночку'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['kuşatma hissi', 'sertlik', 'izolasyon'],
      en: ['siege-feeling', 'harshness', 'isolation'],
      ru: ['ощущение осады', 'жёсткость', 'изоляция'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Tek noktadan korunan kıvılcım.', 'A spark guarded from one point.', 'Искра, охраняемая с одной точки.'),
      loveMeaning: L10nTriple('İlişkide kendini anlatma ihtiyacı artabilir.', 'A need to speak for oneself may rise in a bond.', 'В связи может усилиться нужда говорить за себя.'),
      careerMeaning: L10nTriple('İş ideallerini korumak gündeme gelebilir.', 'Protecting work ideals may come forward.', 'Может выйти защита рабочих идеалов.'),
      moneyMeaning: L10nTriple('Kaynağı savurmadan tutmak sakin duruştur.', 'Holding a resource without scattering it is a calm stance.', 'Держать ресурс, не разбрасывая, — спокойная поза.'),
      personalMeaning: L10nTriple('İçeride \'ben buradayım\' diyen bir omurga olabilir.', 'A spine saying \'I am here\' may live inside.', 'Внутри может жить хребет «я здесь».'),
      challengeMeaning: L10nTriple('Duruş, herkese karşı savaş gibi okunabilir.', 'Stance may be read as war against everyone.', 'Стойка может читаться как война со всеми.'),
      guidanceMeaning: L10nTriple('Yerini tut; düşman üretme.', 'Hold your ground; do not manufacture enemies.', 'Держи место; не производи врагов.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha net bir sınır.', 'A possible climate: a clearer boundary.', 'Возможный климат: более ясная граница.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_04', 'swords_07', 'wands_09'],
      note: L10nTriple('İmparator yapı, Kılıç Yedilisi kayış, Değnek Dokuzu son ateştir.', 'Emperor structure; Seven of Swords slip; Nine of Wands last fire.', 'Император — строй; Семёрка Мечей — ускользание; Девятка Жезлов — последний огонь.'),
    ),
    visualAsset: 'assets/tarot/cards/wands/07_seven.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'wands_08',
    number: 8,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.wands,
    name: L10nTriple('Değnek Sekizlisi', 'Eight of Wands', 'Восьмёрка Жезлов'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['hız', 'haber', 'akış'],
      en: ['speed', 'news', 'flow'],
      ru: ['скорость', 'весть', 'поток'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['acele', 'dağılma', 'sabırsızlık'],
      en: ['haste', 'scatter', 'impatience'],
      ru: ['спешка', 'рассев', 'нетерпение'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Havada giden oklar; henüz varış değil.', 'Arrows in air; not yet arrival.', 'Стрелы в воздухе; ещё не прибытие.'),
      loveMeaning: L10nTriple('İlişkide tempo artabilir; her hız yakınlık değildir.', 'Tempo in a bond may rise; not every speed is closeness.', 'Темп связи может вырасти; не всякая скорость — близость.'),
      careerMeaning: L10nTriple('Haber, teslim, hareket işte yoğunlaşabilir.', 'News, delivery, or motion at work may thicken.', 'На работе могут сгуститься вести, сдача, движение.'),
      moneyMeaning: L10nTriple('Hızlı bir kaynak hareketi görülebilir; spekülasyon şart değildir.', 'A fast move of means may be seen; speculation is not required.', 'Может быть видно быстрое движение средств; спекуляция не обязательна.'),
      personalMeaning: L10nTriple('İçeride acele bir rüzgâr esebilir.', 'A hurried wind may blow inside.', 'Внутри может дуть торопливый ветер.'),
      challengeMeaning: L10nTriple('Hız, kaçırmış gibi hissettirebilir.', 'Speed may make one feel already late.', 'Скорость может заставить чувствовать себя опоздавшим.'),
      guidanceMeaning: L10nTriple('Akışa izin ver; her oku kovala ma.', 'Allow the flow; do not chase every arrow.', 'Позволь потоку; не гонись за каждой стрелой.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha hızlı bir ara.', 'A possible climate: a quicker interval.', 'Возможный климат: более быстрый промежуток.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['swords_08', 'major_10', 'cups_08'],
      note: L10nTriple('Kılıç Sekizlisi sıkışma, Çark dönüş, Kupa Sekizlisi ayrılış izidir.', 'Eight of Swords tightness; Wheel a turn; Eight of Cups leaving.', 'Восьмёрка Мечей — теснота; Колесо — поворот; Восьмёрка Кубков — уход.'),
    ),
    visualAsset: 'assets/tarot/cards/wands/08_eight.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'wands_09',
    number: 9,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.wands,
    name: L10nTriple('Değnek Dokuzlusu', 'Nine of Wands', 'Девятка Жезлов'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['son ateş', 'nöbet', 'dayanıklılık'],
      en: ['last fire', 'watch', 'endurance'],
      ru: ['последний огонь', 'дозор', 'стойкость'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['tükenmişlik', 'şüphe', 'yalnız savaş'],
      en: ['exhaustion', 'doubt', 'lone war'],
      ru: ['истощение', 'сомнение', 'одинокая война'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Korunan son kıvılcım; bitmiş değildir.', 'The last guarded spark; it is not finished.', 'Последняя охраняемая искра; это не конец.'),
      loveMeaning: L10nTriple('Bağda yorgun bir sadakat belirebilir.', 'Tired loyalty may appear in a bond.', 'В связи может явиться усталая верность.'),
      careerMeaning: L10nTriple('Uzun bir eforun son dilimi işte hissedilebilir.', 'The last stretch of a long effort may be felt at work.', 'На работе может ощущаться последний отрезок долгого усилия.'),
      moneyMeaning: L10nTriple('Kaynak az görünse de tamamen yok olmayabilir.', 'Means may look thin without being gone.', 'Средства могут казаться тонкими, не исчезнув.'),
      personalMeaning: L10nTriple('İçeride nöbet tutan bir yorgunluk olabilir.', 'A fatigue on watch may live inside.', 'Внутри может жить усталость на дозоре.'),
      challengeMeaning: L10nTriple('Nöbet, kimseye güvenmemeye kayabilir.', 'The watch may slide into trusting no one.', 'Дозор может стать недоверием ко всем.'),
      guidanceMeaning: L10nTriple('Dinlen; kalkanı bırakmak zorunda değilsin.', 'Rest; you do not have to drop the shield.', 'Отдохни; не обязательно бросать щит.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: dayanıklılığın sessiz hali.', 'A possible climate: the quiet form of endurance.', 'Возможный климат: тихий вид стойкости.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_08', 'wands_10', 'pentacles_09'],
      note: L10nTriple('Güç merhamet, Değnek Onu yük, Tılsım Dokuzu yeterlilik izidir.', 'Strength mercy; Ten of Wands load; Nine of Pentacles enough-ness.', 'Сила — милость; Десятка Жезлов — ноша; Девятка Пентаклей — достаточность.'),
    ),
    visualAsset: 'assets/tarot/cards/wands/09_nine.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'wands_10',
    number: 10,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.wands,
    name: L10nTriple('Değnek Onlusu', 'Ten of Wands', 'Десятка Жезлов'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['yük', 'fazla ateş', 'sorumluluk'],
      en: ['load', 'too much fire', 'duty'],
      ru: ['ноша', 'слишком много огня', 'долг'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['kahramanlık oyunu', 'çöküş korkusu', 'delege edememe'],
      en: ['hero-play', 'collapse-fear', 'cannot delegate'],
      ru: ['игра героя', 'страх обвала', 'неумение поручить'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Çok fazla değnek; omuzların dili.', 'Too many wands; the language of shoulders.', 'Слишком много жезлов; язык плеч.'),
      loveMeaning: L10nTriple('İlişkide tek kişinin taşıması yorucu olabilir.', 'One person carrying a bond may tire.', 'Когда связь несёт один, это утомляет.'),
      careerMeaning: L10nTriple('İş yükü görünür olabilir; kahraman olmak şart değildir.', 'Work load may be visible; being the hero is not required.', 'Нагрузка дела может быть видна; быть героем не обязательно.'),
      moneyMeaning: L10nTriple('Çok iş, kaynağı da dağıtabilir.', 'Too many tasks may also scatter means.', 'Слишком много дел может рассеять и средства.'),
      personalMeaning: L10nTriple('İçeride \'hepsini ben\' cümlesi duruyor olabilir.', 'The sentence \'I will take it all\' may be standing inside.', 'Внутри может стоять фраза «я возьму всё».'),
      challengeMeaning: L10nTriple('Yük, kimliğe dönüşebilir.', 'The load may become identity.', 'Ноша может стать личностью.'),
      guidanceMeaning: L10nTriple('Bir değneği bırak; hepsini düşürme.', 'Set one wand down; do not drop them all.', 'Опусти один жезл; не бросай все.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: paylaşılmayı bekleyen bir ağırlık.', 'A possible climate: a weight waiting to be shared.', 'Возможный климат: тяжесть, ждущая разделения.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_10', 'pentacles_10', 'cups_10'],
      note: L10nTriple('Çark döngü, Tılsım ve Kupa Onu masa ve bağ izidir.', 'Wheel is cycle; Tens of Pentacles and Cups are table and bond.', 'Колесо — цикл; Десятки Пентаклей и Кубков — стол и связь.'),
    ),
    visualAsset: 'assets/tarot/cards/wands/10_ten.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'wands_11',
    number: 11,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.wands,
    name: L10nTriple('Değnek Habercisi', 'Page of Wands', 'Паж Жезлов'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['haber', 'öğrenci ateşi', 'merak'],
      en: ['message', 'student fire', 'curiosity'],
      ru: ['весть', 'огонь ученика', 'любопытство'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['dağınık heves', 'övünç', 'dinlememe'],
      en: ['scattered zeal', 'boast', 'not listening'],
      ru: ['рассеянный пыл', 'похвальба', 'неслушание'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Yeni bir ateşin habercisi; usta değil.', 'Messenger of a new fire; not yet a master.', 'Вестник нового огня; ещё не мастер.'),
      loveMeaning: L10nTriple('Bağda taze, biraz acemi bir sıcaklık belirebilir.', 'A fresh, slightly unripe warmth may appear in a bond.', 'В связи может явиться свежая, чуть незрелая теплота.'),
      careerMeaning: L10nTriple('Öğrenilecek bir zanaat kapısı aralanabilir.', 'A door into a craft to be learned may open a little.', 'Дверь в ремесло, которому учатся, может чуть открыться.'),
      moneyMeaning: L10nTriple('Küçük bir fırsat haberi gelebilir; servet değildir.', 'News of a small opening may come; it is not a fortune.', 'Может прийти весть о малом отверстии; это не состояние.'),
      personalMeaning: L10nTriple('İçeride öğrenci meraka dönüşebilir.', 'The inner student may turn into curiosity.', 'Внутренний ученик может стать любопытством.'),
      challengeMeaning: L10nTriple('Haberci, her yerde kıvılcım aramaya kayabilir.', 'The messenger may slide into hunting sparks everywhere.', 'Вестник может начать искать искры всюду.'),
      guidanceMeaning: L10nTriple('Sor; bilmişlik yapma.', 'Ask; do not perform knowingness.', 'Спроси; не играй всезнайку.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: öğrenmeye açık bir ateş.', 'A possible climate: fire open to learning.', 'Возможный климат: огонь, открытый учению.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['cups_11', 'swords_11', 'major_01'],
      note: L10nTriple('Kupa ve Kılıç Habercileri duygu ve dil; Büyücü el izidir.', 'Pages of Cups and Swords are feeling and speech; Magician the hand.', 'Пажи Кубков и Мечей — чувство и речь; Маг — рука.'),
    ),
    visualAsset: 'assets/tarot/cards/wands/11_page.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'wands_12',
    number: 12,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.wands,
    name: L10nTriple('Değnek Şövalyesi', 'Knight of Wands', 'Рыцарь Жезлов'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['yolculuk', 'tutku', 'ileri ateş'],
      en: ['journey', 'passion', 'forward fire'],
      ru: ['путь', 'страсть', 'огонь вперёд'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['acele', 'dağınık tutku', 'savaş arayışı'],
      en: ['haste', 'scattered passion', 'seeking battle'],
      ru: ['спешка', 'рассеянная страсть', 'поиск битвы'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Hareket halindeki ateş; varış noktası henüz ev değildir.', 'Fire in motion; the destination is not yet home.', 'Огонь в движении; место прибытия ещё не дом.'),
      loveMeaning: L10nTriple('İlişkide coşku belirebilir; köklenme ayrı bir iştir.', 'Ardor may appear in a bond; taking root is another task.', 'В связи может явиться пыл; укоренение — другое дело.'),
      careerMeaning: L10nTriple('İş için yola çıkmak mümkün görünür.', 'Setting out for work may be possible.', 'Возможно выйти в путь ради дела.'),
      moneyMeaning: L10nTriple('Hareket, harcamayı da hızlandırabilir.', 'Motion may also speed spending.', 'Движение может ускорить и траты.'),
      personalMeaning: L10nTriple('İçeride duramayan bir at olabilir.', 'A horse that cannot stand still may live inside.', 'Внутри может жить конь, который не стоит.'),
      challengeMeaning: L10nTriple('Yol, kaçış olabilir.', 'The road may be escape.', 'Дорога может быть бегством.'),
      guidanceMeaning: L10nTriple('İlerle; yakarak geçme.', 'Go forward; do not pass by burning.', 'Иди вперёд; не проходи сжигая.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha hareketli bir tutku.', 'A possible climate: more mobile passion.', 'Возможный климат: более подвижная страсть.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['cups_12', 'major_07', 'pentacles_12'],
      note: L10nTriple('Kupa Şövalyesi duygu yolculuğu, Savaş Arabası yön, Tılsım Şövalyesi madde yoludur.', 'Knight of Cups is feeling-travel; Chariot heading; Knight of Pentacles matter-road.', 'Рыцарь Кубков — путь чувства; Колесница — курс; Рыцарь Пентаклей — дорога материи.'),
    ),
    visualAsset: 'assets/tarot/cards/wands/12_knight.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'wands_13',
    number: 13,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.wands,
    name: L10nTriple('Değnek Kraliçesi', 'Queen of Wands', 'Королева Жезлов'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['sıcak ev', 'olgun ateş', 'davet'],
      en: ['warm house', 'mature fire', 'invitation'],
      ru: ['тёплый дом', 'зрелый огонь', 'приглашение'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['kontrol', 'kıskançlık', 'sönükleşme'],
      en: ['control', 'envy', 'dimming'],
      ru: ['контроль', 'зависть', 'угасание'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Evin içindeki ateş; sahne ateşi değil.', 'Fire inside a house; not stage-fire.', 'Огонь внутри дома; не сценический огонь.'),
      loveMeaning: L10nTriple('Bağda olgun bir sıcaklık barınabilir.', 'A mature warmth may dwell in a bond.', 'В связи может жить зрелая теплота.'),
      careerMeaning: L10nTriple('İş ortamını ısıtmak, yakmadan mümkün görünebilir.', 'Warming a work climate without scorching may look possible.', 'Согреть рабочий климат, не обжигая, может казаться возможным.'),
      moneyMeaning: L10nTriple('Kaynakları cömert ve ölçülü tutmak sakin duruştur.', 'Holding means generously and in measure is a calm stance.', 'Держать средства щедро и в мере — спокойная поза.'),
      personalMeaning: L10nTriple('İçeride başkalarını ısıtabilen bir yetişkin ateş olabilir.', 'An adult fire able to warm others may live inside.', 'Внутри может жить взрослый огонь, способный греть других.'),
      challengeMeaning: L10nTriple('Sıcaklık, sahiplenmeye kayabilir.', 'Warmth may slide into possessing.', 'Теплота может стать присвоением.'),
      guidanceMeaning: L10nTriple('Ocağı canlı tut; kimseyi içine kapatma.', 'Keep the hearth alive; do not shut anyone inside it.', 'Держи очаг живым; никого в него не запирай.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha ev gibi bir irade.', 'A possible climate: a more household will.', 'Возможный климат: более домашняя воля.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['cups_13', 'major_03', 'wands_14'],
      note: L10nTriple('Kupa Kraliçesi duygu ev, İmparatoriçe bakım, Değnek Kralı yöndür.', 'Queen of Cups is feeling-house; Empress care; King of Wands heading.', 'Королева Кубков — дом чувства; Императрица — забота; Король Жезлов — курс.'),
    ),
    visualAsset: 'assets/tarot/cards/wands/13_queen.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
  OraclyTarotCard(
    id: 'wands_14',
    number: 14,
    arcana: OraclyTarotArcana.minor,
    suit: OraclyTarotSuit.wands,
    name: L10nTriple('Değnek Kralı', 'King of Wands', 'Король Жезлов'),
    uprightKeywords: OraclyTarotKeywords(
      tr: ['yön veren ateş', 'sorumlu kıvılcım', 'vizyon'],
      en: ['directing fire', 'responsible spark', 'vision'],
      ru: ['направляющий огонь', 'ответственная искра', 'видение'],
    ),
    reversedKeywords: OraclyTarotKeywords(
      tr: ['baskı', 'ego', 'dinlememe'],
      en: ['pressure', 'ego', 'not listening'],
      ru: ['давление', 'эго', 'неслушание'],
    ),
    meanings: OraclyTarotMeanings(
      symbolicMeaning: L10nTriple('Ateşi bir yöne çağıran duruş.', 'A stance that calls fire into a heading.', 'Поза, зовущая огонь в курс.'),
      loveMeaning: L10nTriple('İlişkide net bir yön teklifi belirebilir; dayatma ayrıdır.', 'A clear heading may be offered in a bond; imposing it is another matter.', 'В связи может быть предложен ясный курс; навязывать его — иное.'),
      careerMeaning: L10nTriple('İş için vizyon ve sorumluluk konuşulabilir.', 'Vision and responsibility at work may be spoken.', 'На работе могут говорить о видении и ответственности.'),
      moneyMeaning: L10nTriple('Kaynakları bir niyete bağlamak mümkün görünür.', 'Binding means to an intent may be possible.', 'Возможно связать средства с намерением.'),
      personalMeaning: L10nTriple('İçeride hem lider hem dinleyen bir ateş istenebilir.', 'A fire that both leads and listens may be wanted inside.', 'Внутри может быть нужен огонь, который и ведёт, и слушает.'),
      challengeMeaning: L10nTriple('Yön, başkalarının ateşini söndürmeye kayabilir.', 'Heading may slide into putting out others\' fire.', 'Курс может начать гасить чужой огонь.'),
      guidanceMeaning: L10nTriple('Yön ver; yakarak yönetme.', 'Give heading; do not rule by burning.', 'Дай курс; не правь сжигая.'),
      futureDirectionMeaning: L10nTriple('Olası iklim: daha sorumlu bir irade.', 'A possible climate: more responsible will.', 'Возможный климат: более ответственная воля.'),
    ),
    relationshipWithOtherCards: OraclyTarotRelations(
      relatedIds: ['major_04', 'swords_14', 'wands_13'],
      note: L10nTriple('İmparator yapı, Kılıç Kralı zihin yönü, Değnek Kraliçesi ev ateşidir.', 'Emperor is structure; King of Swords mental heading; Queen of Wands household fire.', 'Император — строй; Король Мечей — умственный курс; Королева Жезлов — домашний огонь.'),
    ),
    visualAsset: 'assets/tarot/cards/wands/14_king.webp',
    cardBackAsset: 'assets/tarot/card_back/oracly_tarot_back_portrait.svg',
  ),
];
