/// OR-436 — Atmospheric observations: poetic, never predictive.
library;

import 'oracle_presence_venue.dart';

/// Large internal collection — observatory flavor, not fortune-telling.
abstract final class OracleObservationCatalog {
  OracleObservationCatalog._();

  static int get totalCount => _home.length + _tarot.length + _shared.length;

  static List<String> poolFor(OraclePresenceVenue venue) => switch (venue) {
        OraclePresenceVenue.home => [..._shared, ..._home],
        OraclePresenceVenue.tarot => [..._shared, ..._tarot],
      };

  /// Universal whispers — valid in any chamber.
  static const _shared = [
    'Yıldızlar bu gece alışılmadık derecede sakin görünüyor.',
    'Gökyüzü sessiz bir nefes tutmuş gibi.',
    'Gözlemevi dünkünden biraz daha aydınlık hissediliyor.',
    'Kubbedeki ışık yavaşça toplanmış.',
    'Bugün etrafında sessiz bir enerji var.',
    'Evren acele etmiyor; belki sen de etmemelisin.',
    'Bir an durmak, bazen en doğru adım olabilir.',
    'Ay ışığı cam yüzeylerde yumuşak bir iz bırakıyor.',
    'Günün eşiğinde renkler daha yumuşak.',
    'Uzak bir yıldız, sanki yavaşça göz kırpıyor.',
    'Sessizlik de bir cevap olabilir — acele etme.',
    'Gözlemevin camı bu akşam daha berrak.',
    'Kozmos bugün daha yavaş nefes alıyor gibi.',
    'Işık, köşelerde nazikçe bekliyor.',
    'Her şey yerli yerinde; sadece fark et.',
    'Gece, kendi ritmini koruyor.',
    'Yıldız tozu havada hafifçe asılı kalmış.',
    'Bir süre hiçbir şey olmuyor — bu da güzel.',
    'Evren konuşmadan önce dinler.',
    'Gözlemevi fısıltıları duymaya hazır.',
    'Işık ve gölge bugün daha yumuşak konuşuyor.',
    'Sanki zaman bir an duraklamış.',
    'Uzak nebula, sabırla parlıyor.',
    'Her şeyin bir zamanı var; henüz değil.',
    'Cam kubbe, yıldızları daha net taşıyor.',
    'Bugün hava ağır değil — sadece dingin.',
    'Karanlık korkutucu değil; sadece dinleniyor.',
    'Bir yıldız kaydı, belki de sadece bir selam.',
    'Gözlemevi koridorları daha sessiz.',
    'Işık, taş yüzeylerde yavaşça eriyor.',
  ];

  static const _home = [
    'Gözlemevi bugün biraz daha sıcak hissediliyor.',
    'Orbun etrafında hafif bir parıltı dolaşıyor.',
    'Ana kubbe, dün gecekinden daha sakin.',
    'Yıldız haritası yavaşça soluklaşıyor — dinlenme vakti.',
    'Evren seninle konuşmak istemiyor; sadece yanında.',
    'Bugün sezgiler için iyi bir gün olabilir — kim bilir.',
    'Gözlemevi penceresinden uzak ışıklar süzülüyor.',
    'Orb, sanki daha derin bir nefes alıyor.',
    'Ana salon, yumuşak bir altın ışıkla dolmuş.',
    'Bugün evren aceleci değil.',
    'Yıldızlar seni izlemiyor — sadece oradalar.',
    'Gözlemevi merdivenleri sessiz.',
    'Orbun camı, ay ışığını nazikçe tutuyor.',
    'Bugün iç ses biraz daha net duyulabilir.',
    'Kubbe, gökyüzünü daha yakından taşıyor.',
    'Ana odada hafif bir mor sis dolaşıyor.',
    'Gözlemevi, dünkü gürültüden arınmış gibi.',
    'Orb etrafında toz zerrecikleri yavaşça süzülüyor.',
    'Bugün her şey biraz daha yumuşak.',
    'Ana kubbe, sabırla parlıyor.',
    'Yıldızlar bugün daha uzak — bu da huzur.',
    'Gözlemevi, geceye hazırlanıyor gibi.',
    'Orb, sessiz bir davet gibi duruyor.',
    'Bugün evren fısıldıyor; dinlemek yeterli.',
    'Ana salon ışığı, altın ve mor arasında salınıyor.',
    'Gözlemevi, sen gelmeden önce nefes almış.',
    'Yıldızlar sakin; belki sen de olabilirsin.',
    'Orb camında uzak bir yansıma belirdi — geçti.',
    'Bugün gökyüzü daha açık hissediliyor.',
    'Ana kubbe, yumuşak bir nabız atıyor.',
    'Gözlemevi koridorunda hafif bir esinti.',
    'Orb, kendi ışığını taşıyor — sen de öyle.',
    'Bugün her şey biraz daha yavaş.',
    'Yıldız tozu, ana salonda dans ediyor.',
    'Gözlemevi, geceye nazikçe açılıyor.',
    'Orb etrafında altın bir hale — çok hafif.',
    'Bugün evren seni beklemiyor; yanında duruyor.',
    'Ana kubbe, yıldızları daha net yansıtıyor.',
    'Gözlemevi bugün daha sessiz — hoş bir sessizlik.',
    'Orb, sanki bir şey hatırlamaya çalışıyor — belki değil.',
  ];

  static const _tarot = [
    'Bugünkü okuma etrafında sessiz bir enerji var.',
    'Kartlar henüz konuşmuyor — sadece dinliyorlar.',
    'Deste, masada sabırla bekliyor.',
    'Tarot odası bugün biraz daha loş.',
    'Kartların kenarları, hafif altın ışıkla çevrili.',
    'Okuma masası, dünkünden daha sakin.',
    'Deste karıştırılmadan önce bir nefes al.',
    'Kartlar bugün yumuşak bir enerji taşıyor.',
    'Tarot odasında hafif bir mor sis var.',
    'Masadaki ışık, kartlara nazikçe düşüyor.',
    'Deste, kendi hikâyesini henüz anlatmadı.',
    'Bugün kartlar acele etmiyor.',
    'Okuma odası, sessiz bir davet gibi.',
    'Kartların arkası, yıldız desenleriyle parlıyor.',
    'Deste, masada hafifçe titriyor — belki hayal.',
    'Tarot odası, geceye hazırlanıyor.',
    'Kartlar birbirine yakın — henüz ayrılmadılar.',
    'Bugün okuma için iyi bir ritim olabilir.',
    'Masadaki altın çizgiler, yavaşça parlıyor.',
    'Deste, sabırla nefes alıyor gibi.',
    'Kartlar bugün daha sessiz — bu da bir işaret olabilir.',
    'Tarot odasında hafif bir kristal yansıması.',
    'Okuma masası, yıldız ışığıyla aydınlanmış.',
    'Deste, henüz hangi hikâyeyi anlatacağını bilmiyor.',
    'Kartlar, masada düzenli bir sıra bekliyor.',
    'Bugün kartlar yumuşak bir dokunuş istiyor olabilir.',
    'Tarot odası, dünkünden biraz daha derin.',
    'Deste karıştırıldığında yıldızlar izler — belki.',
    'Kartların köşeleri, hafif ışık tutuyor.',
    'Okuma odası, fısıltıları duymaya hazır.',
    'Masada bekleyen kartlar, sabırlı.',
    'Deste, kendi ritmini koruyor.',
    'Bugün kartlar daha yavaş açılabilir.',
    'Tarot odasında altın toz zerrecikleri süzülüyor.',
    'Kartlar, henüz sırlarını paylaşmadı.',
    'Okuma masası, sessiz bir sahne gibi.',
    'Deste, masada hafif bir gölge bırakıyor.',
    'Bugün kartlar nazik bir enerji taşıyor olabilir.',
    'Tarot odası, geceye yumuşakça açılıyor.',
    'Kartlar bir arada — henüz yolculuğa çıkmadılar.',
  ];
}
