"""Cups 2–14, Swords, Pentacles."""

from oracly_tarot_minors_base import C

CUPS_REST = [
    C("cups", 2, ("karşılıklılık|kadeh|bağ", "reciprocity|cup|bond", "взаимность|чаша|связь"),
      ("dengesizlik|yansıtma|acele birlik", "imbalance|projection|hasty union", "дисбаланс|проекция|поспешный союз"),
      ("İki kadehin buluşması; henüz evlilik kehaneti değil.", "Two cups meeting; not a marriage prophecy.", "Встреча двух чаш; не пророчество брака."),
      ("Bağda karşılıklılık konuşulabilir.", "Reciprocity in a bond may be spoken.", "В связи могут говорить о взаимности."),
      ("İş ortaklığı insani bir ton alabilir.", "A work partnership may take a human tone.", "Рабочее партнёрство может принять человеческий тон."),
      ("Paylaşım, hesap kitap olmadan da düşünülebilir.", "Sharing may be thought without a ledger.", "Делёж можно мыслить и без книги счетов."),
      ("İçeride 'sen ve ben' cümlesi yumuşak durabilir.", "The phrase 'you and I' may sit softly inside.", "Внутри мягко может стоять фраза «ты и я»."),
      ("Birlik, kendini kaybetmeye kayabilir.", "Union may slide into losing oneself.", "Союз может стать потерей себя."),
      ("Uzanan kadehi gör; henüz içmek zorunda değilsin.", "See the offered cup; you do not have to drink yet.", "Увидь протянутую чашу; ещё не обязательно пить."),
      ("Olası iklim: daha karşılıklı bir bağ.", "A possible climate: a more reciprocal bond.", "Возможный климат: более взаимная связь."),
      ["major_06", "wands_02", "swords_02"],
      ("Aşıklar seçim, Değnek ve Kılıç ikilileri tempo ve mesafedir.", "Lovers are choice; Twos of Wands and Swords tempo and distance.", "Влюблённые — выбор; Двойки Жезлов и Мечей — темп и дистанция.")),
    C("cups", 3, ("paylaşım|kutlama|dostluk", "sharing|marking|friendship", "деление|отмечание|дружба"),
      ("yüzeysellik|dışlanma|fazla gürültü", "surface|exclusion|too much noise", "поверхность|исключение|слишком много шума"),
      ("Üç kadehin masası; yalnızlığın karşıtı, evliliğin değil.", "A table of three cups; opposite of solitude, not of marriage.", "Стол трёх чаш; противоположность одиночеству, не браку."),
      ("Bağ çevresinde dostluk belirginleşebilir.", "Friendship around a bond may become clearer.", "Вокруг связи может проясниться дружба."),
      ("İş te işbirliği neşesi belirebilir.", "The joy of collaboration may appear at work.", "На работе может явиться радость сотрудничества."),
      ("Paylaşılan bir masanın maliyeti de vardır.", "A shared table also has a cost.", "У общего стола тоже есть цена."),
      ("İçeride 'biz' kelimesi ısınabilir.", "The word 'we' may warm inside.", "Внутри может согреться слово «мы»."),
      ("Kutlama, içi boş gürültüye kayabilir.", "Marking may slide into empty noise.", "Отмечание может стать пустым шумом."),
      ("Masaya otur; her kadehi bitirmek zorunda değilsin.", "Sit at the table; you do not have to empty every cup.", "Сядь за стол; не обязательно опустошать каждую чашу."),
      ("Olası iklim: daha paylaşılmış bir neşe.", "A possible climate: more shared gladness.", "Возможный климат: более разделённая радость."),
      ["wands_03", "major_03", "pentacles_03"],
      ("Değnek Üçlüsü büyüme, İmparatoriçe bakım, Tılsım Üçlüsü zanaattır.", "Three of Wands growth; Empress care; Three of Pentacles craft.", "Тройка Жезлов — рост; Императрица — забота; Тройка Пентаклей — ремесло.")),
    C("cups", 4, ("durgunluk|doyum|içeri bakış", "stillness|enough|inward look", "застой|достаточность|взгляд внутрь"),
      ("nankörlük|kaçış|duygu körlüğü", "ingratitude|escape|feeling-blind", "неблагодарность|бегство|слепота чувства"),
      ("Öndeki kadeh; bakılmayan su.", "The cup in front; water not looked at.", "Чаша перед тобой; вода, на которую не смотрят."),
      ("İlişkide bıkkınlık, yokluk anlamına gelmez.", "Weariness in a bond does not mean absence.", "Усталость в связи не значит отсутствие."),
      ("İşin anlamı soluk görünebilir.", "The meaning of work may look pale.", "Смысл дела может казаться бледным."),
      ("Yetmez hissi, gerçek yokluktan ayrı durabilir.", "A sense of not-enough may sit apart from real lack.", "Чувство «мало» может стоять отдельно от настоящей нехватки."),
      ("İçeride doymuş ama susuz bir yer olabilir.", "A place full yet thirsty may live inside.", "Внутри может жить место сытое и всё же жаждущее."),
      ("Durgunluk, küçümsemeye kayabilir.", "Stillness may slide into disdain.", "Застой может стать пренебрежением."),
      ("Öndeki kadehe bak; yeni bir tane istemeden önce.", "Look at the cup in front before wanting a new one.", "Посмотри на чашу перед собой, прежде чем хотеть новую."),
      ("Olası iklim: duygusal bir ara duruş.", "A possible climate: an emotional pause.", "Возможный климат: эмоциональная пауза."),
      ["wands_04", "major_12", "swords_04"],
      ("Değnek Dördü mola, Asılan Adam açı, Kılıç Dördü dinlenmedir.", "Four of Wands pause; Hanged Man angle; Four of Swords rest.", "Четвёрка Жезлов — пауза; Повешенный — ракурс; Четвёрка Мечей — отдых.")),
    C("cups", 5, ("kayıp|yas|dökülen su", "loss|mourning|spilled water", "потеря|траур|пролитая вода"),
      ("sadece kayba bakmak|umutsuzluk|inkâr", "seeing only loss|despair|denial", "видеть только потерю|отчаяние|отрицание"),
      ("Dökülen kadehler; ayakta duranlar da vardır.", "Spilled cups; some still stand.", "Пролитые чаши; некоторые ещё стоят."),
      ("Bağda bir yas katmanı belirebilir.", "A layer of mourning may appear in a bond.", "В связи может явиться слой траура."),
      ("Bir iş kaybı hissedilebilir; kimlik bitişi değildir.", "A work loss may be felt; it is not the end of identity.", "Может ощущаться потеря в деле; это не конец личности."),
      ("Maddi bir dökülme fark edilebilir.", "A material spill may be noticed.", "Может быть заметен материальный пролив."),
      ("İçeride ağlayan ve hâlâ bakan iki yer olabilir.", "Two places may live inside: one weeping, one still looking.", "Внутри могут жить два места: одно плачет, другое всё ещё смотрит."),
      ("Yas, her şey bitti hikâyesine bağlanabilir.", "Mourning may bind to a story that all is over.", "Траур может привязаться к истории, что всё кончено."),
      ("Döküleni gör; ayaktakini de say.", "See what spilled; count what still stands.", "Увидь пролитое; сочти и то, что стоит."),
      ("Olası iklim: daha dürüst bir keder.", "A possible climate: more honest grief.", "Возможный климат: более честная печаль."),
      ["major_13", "swords_05", "pentacles_05"],
      ("Ölüm kapanış, Kılıç ve Tılsım Beşlisi çatışma ve yoksunluk izidir.", "Death is closing; Fives of Swords and Pentacles clash and lack.", "Смерть — закрытие; Пятёрки Мечей и Пентаклей — спор и нехватка.")),
    C("cups", 6, ("hatıra|sadelik|geçmiş su", "memory|simplicity|past water", "память|простота|прошлая вода"),
      ("geçmişe kilit|çocuk rolü|şimdiyi kaçırma", "lock to past|child role|missing now", "замок на прошлом|роль ребёнка|пропуск сейчас"),
      ("Eski bir kadeh; bugünün masasında durabilir.", "An old cup; it may sit on today's table.", "Старая чаша; она может стоять на сегодняшнем столе."),
      ("Bağda hatırlanan bir yumuşaklık belirebilir.", "A remembered softness may appear in a bond.", "В связи может явиться вспомненная мягкость."),
      ("Eski bir iş bağı veya sade bir yöntem hatırlanabilir.", "An old work tie or a simple method may be remembered.", "Может вспомниться старая рабочая связь или простой метод."),
      ("Geçmiş bir güvenlik hissi kaynaklara da değebilir.", "A past sense of safety may also touch means.", "Прошлое чувство безопасности может коснуться и средств."),
      ("İçeride çocuk bir yer ısınabilir.", "A child-place may warm inside.", "Внутри может согреться детское место."),
      ("Hatıra, şimdiyi durdurabilir.", "Memory may stop the present.", "Память может остановить настоящее."),
      ("Hatırla; orada kalma.", "Remember; do not remain there.", "Вспомни; не оставайся там."),
      ("Olası iklim: daha sade bir duygu.", "A possible climate: a simpler feeling.", "Возможный климат: более простое чувство."),
      ["wands_06", "major_19", "cups_10"],
      ("Değnek Altılısı geçiş, Güneş açıklık, Kupa Onu paylaşılmış masadır.", "Six of Wands crossing; Sun openness; Ten of Cups a shared table.", "Шестёрка Жезлов — переход; Солнце — открытость; Десятка Кубков — общий стол.")),
    C("cups", 7, ("seçenek|hayal|sisli kadeh", "options|dream|misty cup", "варианты|мечта|туманная чаша"),
      ("kaçış hayali|kararsızlık|gerçekten kopma", "escape-dream|indecision|split from real", "мечта-бегство|нерешительность|отрыв от реального"),
      ("Birçok kadeh; hepsi su değildir.", "Many cups; not all hold water.", "Много чаш; не во всех вода."),
      ("İlişkide birkaç imge çatışabilir.", "Several images may clash in a bond.", "В связи могут столкнуться несколько образов."),
      ("İş te çok seçenek dağınık durabilir.", "Many work options may sit scattered.", "Много рабочих вариантов могут лежать вразброс."),
      ("Hayali kazanç, duru hesaptan ayrıdır.", "Imagined gain sits apart from a clear account.", "Воображаемая прибыль стоит отдельно от ясного счёта."),
      ("İçeride sisli bir istek korosu olabilir.", "A choir of misty wants may live inside.", "Внутри может жить хор туманных желаний."),
      ("Hayal, seçmemenin bahanesi olabilir.", "Dreaming may become an excuse not to choose.", "Мечта может стать отговоркой не выбирать."),
      ("Kadehlerden birine dokun; hepsini seyretme.", "Touch one cup; do not only watch them all.", "Дотронься до одной чаши; не только смотри на все."),
      ("Olası iklim: seçenek sisli bir ara.", "A possible climate: a misty interval of options.", "Возможный климат: туманный промежуток вариантов."),
      ["major_18", "swords_07", "wands_07"],
      ("Ay belirsizlik, Kılıç Yedilisi kayış, Değnek Yedilisi duruştur.", "Moon unclearness; Seven of Swords slip; Seven of Wands stance.", "Луна — неясность; Семёрка Мечей — ускользание; Семёрка Жезлов — стойка.")),
    C("cups", 8, ("ayrılış|daha derin su|sırt", "leaving|deeper water|back turned", "уход|более глубокая вода|спина"),
      ("kaçış|pişmanlık|yarım bırakma", "escape|regret|leaving half", "бегство|сожаление|бросать наполовину"),
      ("Bırakılan kadeh; daha derin bir arayış.", "A cup left behind; a deeper search.", "Оставленная чаша; более глубокий поиск."),
      ("Bağda bir uzaklaşma ihtiyacı belirebilir.", "A need to step away may appear in a bond.", "В связи может явиться нужда отойти."),
      ("Bir işi bırakmak anlam arayışı olabilir.", "Leaving a job may be a search for meaning.", "Уход с дела может быть поиском смысла."),
      ("Maddi konfor, iç boşluğu doldurmayabilir.", "Material comfort may not fill an inner vacancy.", "Материальный уют может не заполнить внутреннюю пустоту."),
      ("İçeride 'bu kadar değil' cümlesi duruyor olabilir.", "The sentence 'this is not enough' may be standing inside.", "Внутри может стоять фраза «этого мало»."),
      ("Ayrılış, küçümseme olabilir.", "Leaving may be disdain.", "Уход может быть пренебрежением."),
      ("Sırtını dön; yakarak gitme.", "Turn your back; do not leave by burning.", "Повернись спиной; не уходи сжигая."),
      ("Olası iklim: daha derin bir arayış aralığı.", "A possible climate: an interval of deeper search.", "Возможный климат: промежуток более глубокого поиска."),
      ["major_09", "wands_08", "swords_08"],
      ("Ermiş yalnız ışık, Değnek Sekizlisi hız, Kılıç Sekizlisi sıkışmadır.", "Hermit solitary light; Eight of Wands speed; Eight of Swords tightness.", "Отшельник — одинокий свет; Восьмёрка Жезлов — скорость; Восьмёрка Мечей — теснота.")),
    C("cups", 9, ("iç doyum|dilek|sakin su", "inner enough|wish|calm water", "внутренняя достаточность|желание|спокойная вода"),
      ("şişirme|yalnız zafer|doyumsuzluk", "inflation|lone victory|never enough", "раздувание|одинокая победа|никогда не довольно"),
      ("Dolu bir kadeh; sahne mutluluğu değil.", "A full cup; not staged happiness.", "Полная чаша; не сценическое счастье."),
      ("Bağda yeterlilik hissedilebilir.", "Enough-ness may be felt in a bond.", "В связи может ощущаться достаточность."),
      ("İş te kişisel bir tatmin belirebilir.", "A personal enough at work may appear.", "На работе может явиться личная достаточность."),
      ("İstek ile ihtiyaç ayrılabilir.", "Wish and need may separate.", "Желание и нужда могут разделиться."),
      ("İçeride 'yeter' diyebilen bir yer olabilir.", "A place able to say 'enough' may live inside.", "Внутри может жить место, способное сказать «довольно»."),
      ("Doyum, başkasını dışarıda bırakmaya kayabilir.", "Enough-ness may slide into leaving others out.", "Достаточность может начать оставлять других вовне."),
      ("Kadehi tadına bak; vitrine koyma.", "Taste the cup; do not put it in a shop window.", "Вкуси чашу; не ставь её в витрину."),
      ("Olası iklim: daha sakin bir yeterlilik.", "A possible climate: quieter enough-ness.", "Возможный климат: более тихая достаточность."),
      ["major_17", "pentacles_09", "cups_10"],
      ("Yıldız sakin umut, Tılsım Dokuzu yeter, Kupa Onu masadır.", "Star quiet hope; Nine of Pentacles enough; Ten of Cups the table.", "Звезда — тихая надежда; Девятка Пентаклей — довольно; Десятка Кубков — стол.")),
    C("cups", 10, ("paylaşılan masa|aile suyu|çember", "shared table|family water|circle", "общий стол|семейная вода|круг"),
      ("ideal sahne|baskı mutluluk|çatlak gizleme", "ideal stage|forced joy|hiding cracks", "идеальная сцена|навязанная радость|скрытие трещин"),
      ("Dolu masanın sakin hali; sonsuzluk iddiası yok.", "The calm form of a full table; no claim of forever.", "Спокойный вид полного стола; нет утверждения навсегда."),
      ("Bağda aidiyet ve paylaşım öne çıkabilir.", "Belonging and sharing may come forward in a bond.", "В связи могут выйти принадлежность и делёж."),
      ("İş te bir ekip duygusu belirebilir.", "A sense of team at work may appear.", "На работе может явиться чувство команды."),
      ("Paylaşılan refah, vitrin refahından ayrıdır.", "Shared plenty sits apart from display plenty.", "Общее изобилие стоит отдельно от витринного."),
      ("İçeride ev gibi bir daire ısınabilir.", "A household circle may warm inside.", "Внутри может согреться домашний круг."),
      ("Çember, dışarıdakini suçlamaya kayabilir.", "The circle may slide into blaming the outsider.", "Круг может начать винить внешнего."),
      ("Masayı kur; sahne dekoru yapma.", "Set the table; do not build stage scenery.", "Накрой стол; не строй сценические декорации."),
      ("Olası iklim: daha paylaşılmış bir duruş.", "A possible climate: a more shared stance.", "Возможный климат: более общая поза."),
      ["wands_10", "pentacles_10", "major_21"],
      ("Değnek Onu yük, Tılsım Onu soy, Dünya tamamlanmadır.", "Ten of Wands load; Ten of Pentacles lineage; World completion.", "Десятка Жезлов — ноша; Десятка Пентаклей — род; Мир — завершение.")),
    C("cups", 11, ("duygu haberi|yumuşak merak|rüya kadehi", "feeling-news|soft curiosity|dream cup", "весть чувства|мягкое любопытство|чаша сна"),
      ("aşırı duyarlılık|kaçış hayali|alınma", "over-sensitivity|escape-dream|taking offense", "сверхчувствительность|мечта-бегство|обида"),
      ("Suyun habercisi; henüz derin deniz değil.", "Messenger of water; not yet the deep sea.", "Вестник воды; ещё не глубокое море."),
      ("Bağda utangaç bir açıklık belirebilir.", "A shy openness may appear in a bond.", "В связи может явиться застенчивая открытость."),
      ("İş te insani bir sezgi kapısı aralanabilir.", "A door of human sensing at work may open a little.", "На работе может чуть открыться дверь человеческого чутья."),
      ("Küçük bir gönül hareketi kaynaklara da değebilir.", "A small heart-move may also touch means.", "Малое движение сердца может коснуться и средств."),
      ("İçeride şiir gibi bir yer uyanabilir.", "A place like a poem may wake inside.", "Внутри может проснуться место, похожее на стихотворение."),
      ("Haberci, her şeyi işaret okumaya kayabilir.", "The messenger may slide into reading omens in everything.", "Вестник может начать читать приметы во всём."),
      ("Hisset; her duyguyu kehanet yapma.", "Feel; do not make every feeling an oracle.", "Чувствуй; не делай из каждого чувства оракула."),
      ("Olası iklim: daha yumuşak bir merak.", "A possible climate: softer curiosity.", "Возможный климат: более мягкое любопытство."),
      ["wands_11", "major_18", "cups_12"],
      ("Değnek Habercisi kıvılcım, Ay sis, Kupa Şövalyesi yolculuktur.", "Page of Wands spark; Moon mist; Knight of Cups journey.", "Паж Жезлов — искра; Луна — туман; Рыцарь Кубков — путь.")),
    C("cups", 12, ("duygu yolculuğu|teklif|akış", "feeling-journey|offer|flow", "путь чувства|предложение|поток"),
      ("dağıtılmış gönül|kaçış romantizmi|sözde derinlik", "scattered heart|escape-romance|seeming depth", "рассеянное сердце|романтика бегства|кажущаяся глубина"),
      ("Kadehle yola çıkan duruş.", "A stance that takes the cup on the road.", "Поза, берущая чашу в дорогу."),
      ("Bağda bir teklif veya yumuşak takip belirebilir.", "An offer or a gentle following may appear in a bond.", "В связи может явиться предложение или мягкое следование."),
      ("İş te anlam arayan bir hareket mümkün görünür.", "A motion seeking meaning at work may be possible.", "На работе возможно движение в поиске смысла."),
      ("Gönül ile hesap ayrı durabilir.", "Heart and account may sit apart.", "Сердце и счёт могут стоять отдельно."),
      ("İçeride akan ve duramayan bir su olabilir.", "Water that flows and cannot stay may live inside.", "Внутри может жить вода, которая течёт и не стоит."),
      ("Yolculuk, bağlanamamaya kayabilir.", "The journey may slide into inability to bind.", "Путь может стать неумением связываться."),
      ("Teklifi götür; her kapıyı çalma.", "Carry the offer; do not knock every door.", "Неси предложение; не стучи в каждую дверь."),
      ("Olası iklim: daha akışkan bir gönül.", "A possible climate: a more fluid heart.", "Возможный климат: более текучее сердце."),
      ["wands_12", "major_14", "swords_12"],
      ("Değnek Şövalyesi ateş yol, Denge harman, Kılıç Şövalyesi zihin yoludur.", "Knight of Wands fire-road; Temperance blend; Knight of Swords mind-road.", "Рыцарь Жезлов — огненная дорога; Умеренность — смесь; Рыцарь Мечей — дорога ума.")),
    C("cups", 13, ("derin kadeh|şefkat|iç deniz", "deep cup|compassion|inner sea", "глубокая чаша|сострадание|внутреннее море"),
      ("taşma|sınır yokluğu|kurtarıcılık", "overflow|no boundary|rescuing", "перелив|нет границы|спасательство"),
      ("Duyguyu tutan olgun kap.", "A mature vessel that holds feeling.", "Зрелый сосуд, держащий чувство."),
      ("Bağda derin şefkat belirebilir; erime ayrıdır.", "Deep compassion may appear in a bond; melting away is another matter.", "В связи может явиться глубокое сострадание; раствориться — иное."),
      ("İş te duygusal zekâ sakin durabilir.", "Emotional intelligence at work may sit calmly.", "На работе эмоциональный ум может сидеть спокойно."),
      ("Cömertlik, kendini yok etmeden durabilir.", "Generosity may stand without self-erasure.", "Щедрость может стоять без самозабвения."),
      ("İçeride başkasını dinleyebilen bir deniz olabilir.", "A sea able to listen to another may live inside.", "Внутри может жить море, способное слушать другого."),
      ("Şefkat, sınır kaybına kayabilir.", "Compassion may slide into lost boundary.", "Сострадание может стать потерей границы."),
      ("Tut; boğulma.", "Hold; do not drown.", "Держи; не тони."),
      ("Olası iklim: daha derin bir şefkat.", "A possible climate: deeper compassion.", "Возможный климат: более глубокое сострадание."),
      ["major_03", "wands_13", "cups_14"],
      ("İmparatoriçe bakım, Değnek Kraliçesi ev ateşi, Kupa Kralı ölçü sudur.", "Empress care; Queen of Wands household fire; King of Cups measured water.", "Императрица — забота; Королева Жезлов — домашний огонь; Король Кубков — мерная вода.")),
    C("cups", 14, ("ölçülü su|sakin kaptan|duygu yönü", "measured water|calm captain|feeling-heading", "мерная вода|спокойный капитан|курс чувства"),
      ("soğukluk|bastırma|duygu yokmuş gibi", "coldness|suppression|as if no feeling", "холод|подавление|будто нет чувства"),
      ("Suyu yönlendiren sakin duruş.", "A calm stance that steers water.", "Спокойная поза, ведущая воду."),
      ("Bağda olgun bir duygusal netlik belirebilir.", "Mature emotional clarity may appear in a bond.", "В связи может явиться зрелая эмоциональная ясность."),
      ("İş te sakin bir insan yönetimi mümkün görünür.", "Calm people-stewardship at work may be possible.", "На работе возможно спокойное управление людьми."),
      ("Duygu ile hesabı aynı masada tutmak sakinleştirir.", "Holding feeling and account at the same table steadies.", "Держать чувство и счёт за одним столом успокаивает."),
      ("İçeride hem derin hem ölçülü bir kaptan olabilir.", "A captain both deep and measured may live inside.", "Внутри может жить капитан и глубокий, и мерный."),
      ("Ölçü, duygusuzluğa kayabilir.", "Measure may slide into feelinglessness.", "Мера может стать бесчувственностью."),
      ("Yön ver; donma.", "Steer; do not freeze.", "Веди; не замерзай."),
      ("Olası iklim: daha olgun bir duygu yönü.", "A possible climate: a more mature heading of feeling.", "Возможный климат: более зрелый курс чувства."),
      ["major_14", "swords_14", "pentacles_14"],
      ("Denge harman, Kılıç ve Tılsım Kralları zihin ve madde yönüdür.", "Temperance blend; Kings of Swords and Pentacles mind and matter heading.", "Умеренность — смесь; Короли Мечей и Пентаклей — курс ума и материи.")),
]
