"""Major Arcana 11–21."""

from oracly_tarot_majors import M

MAJORS_END = [
    M(11, ("Adalet", "Justice", "Справедливость"),
        (["ölçü", "dürüstlük", "denge"], ["measure", "honesty", "balance"], ["мера", "честность", "равновесие"]),
        (["kaçınma", "yargı", "çarpıtma"], ["evasion", "verdict", "distort"], ["уклонение", "приговор", "искажение"]),
        {
            "symbolic": ("Terazinin sakin duruşu; her yanın görünmesi.", "The calm stance of the scales; each side being seen.", "Спокойная поза весов; каждая сторона видна."),
            "love": ("İlişkide adil bir konuşma gerekebilir; haklı çıkmak ayrı bir arzudur.", "A fair conversation may be needed in a bond; being right is a separate wish.", "В связи может быть нужен честный разговор; быть правым — отдельное желание."),
            "career": ("Karar, sözleşme veya sorumluluk netleşebilir.", "A decision, contract, or duty may become clearer.", "Решение, договор или обязанность могут проясниться."),
            "money": ("Hesap ve denge, bulanık harcamayı sakinleştirebilir.", "Accounts and proportion may quiet muddy spending.", "Счёт и мера могут успокоить мутные траты."),
            "personal": ("Kendine karşı dürüstlük, başkasını yargılamaktan daha ağır olabilir.", "Honesty toward oneself may weigh more than judging another.", "Честность к себе может быть тяжелее суда над другим."),
            "challenge": ("Adalet, soğuk bir hüküm giysisine bürünebilir.", "Justice may put on the coat of a cold verdict.", "Справедливость может надеть плащ холодного приговора."),
            "guidance": ("Ölç; cezalandırma.", "Measure; do not punish.", "Меруй; не карай."),
            "future": ("Olası iklim: daha duru bir hesaplaşma — tehdit değil.", "A possible climate: a clearer reckoning — not a threat.", "Возможный климат: более ясный разбор — не угроза."),
        },
        ["major_20", "swords_11", "major_06"],
        ("Mahkeme çağrı, Kılıç Habercisi dil, Aşıklar değer seçimidir.", "Judgement is a call; Page of Swords speech; Lovers a value choice.", "Суд — зов; Паж Мечей — речь; Влюблённые — выбор ценности."),
    ),
    M(12, ("Asılan Adam", "The Hanged Man", "Повешенный"),
        (["askı", "perspektif", "teslim"], ["suspension", "angle", "yielding"], ["подвешенность", "ракурс", "уступка"]),
        (["kurban", "inat", "boşa bekleyiş"], ["martyr", "stubbornness", "empty wait"], ["жертва", "упрямство", "пустое ожидание"]),
        {
            "symbolic": ("Ters çevrilmiş bir bakış; acele etmeyen bir ara.", "An inverted gaze; an interval that does not hurry.", "Перевёрнутый взгляд; промежуток без спешки."),
            "love": ("İlişkide durak, yeni bir açı verebilir; kendini feda etmek ayrı bir hikâyedir.", "A pause in a bond may offer a new angle; self-sacrifice is a different story.", "Пауза в связи может дать новый ракурс; самопожертвование — другая история."),
            "career": ("Beklemek strateji olabilir; felç olmak değil.", "Waiting may be strategy; it is not the same as paralysis.", "Ожидание может быть стратегией; это не паралич."),
            "money": ("Erteleme bir ferahlık da bir kaçış da olabilir; hangisi olduğunu sormak gerekir.", "Delay may be relief or escape; it is worth asking which.", "Отсрочка может быть облегчением или бегством; стоит спросить, чем именно."),
            "personal": ("Kontrolü bir an bırakmak, yeni bir anlam açabilir.", "Releasing control for a moment may open another meaning.", "Отпустить контроль на миг может открыть другой смысл."),
            "challenge": ("Askıda kalmak, hayatın yerine geçebilir.", "Hanging in wait may replace living.", "Висение в ожидании может заменить жизнь."),
            "guidance": ("Açıyı değiştir; kendini cezalandırma.", "Change the angle; do not punish yourself.", "Смени ракурс; не наказывай себя."),
            "future": ("Olası iklim: daha yavaş, daha tersine çevrilmiş bir idrak.", "A possible climate: slower, inverted understanding.", "Возможный климат: более медленное, перевёрнутое понимание."),
        },
        ["major_13", "cups_12", "swords_12"],
        ("Ölüm ardından boşluk; Kupa ve Kılıç Şövalyeleri hareketin iki yüzüdür.", "Death follows with space; Knights of Cups and Swords are two faces of motion.", "За Смертью — пространство; Рыцари Кубков и Мечей — два лица движения."),
    ),
    M(13, ("Ölüm", "Death", "Смерть"),
        (["bitiş", "boşalma", "yeniden diziliş"], ["ending", "clearing", "re-ordering"], ["конец", "очищение", "перестановка"]),
        (["tutunma", "inkâr", "korku"], ["clinging", "denial", "dread"], ["цепляние", "отрицание", "страх"]),
        {
            "symbolic": ("Bir biçimin sonu; yer açan bir kapanış. Bedenin sonu değildir.", "The end of a form; a closing that makes room. Not the end of a body.", "Конец формы; закрытие, которое освобождает место. Не конец тела."),
            "love": ("Bir bağın evresi kapanabilir; bu, nefret veya kehanet değildir.", "A phase of a bond may close; this is not hatred or a prophecy.", "Фаза связи может закрыться; это не ненависть и не пророчество."),
            "career": ("Bir rol veya proje tamamlanmak isteyebilir.", "A role or project may want completion.", "Роль или проект могут хотеть завершения."),
            "money": ("Eski bir düzen çözülebilir; yeni düzen henüz vaat değildir.", "An old arrangement may dissolve; the new one is not yet a promise.", "Старый порядок может распасться; новый ещё не обещание."),
            "personal": ("Eski bir kimlik ağır gelebilir; bırakmak yas da ister.", "An old identity may feel heavy; letting go also asks for mourning.", "Старая личность может стать тяжёлой; отпускание просит и траура."),
            "challenge": ("Korku, bitişi felaket gibi okuyabilir.", "Fear may read an ending as catastrophe.", "Страх может прочесть конец как катастрофу."),
            "guidance": ("Bitene teşekkür et; cesedi taşıma.", "Thank what is ending; do not carry the corpse.", "Поблагодари то, что кончается; не неси труп."),
            "future": ("Olası iklim: bir boşluk — içi henüz doldurulmamış.", "A possible climate: a vacancy — not yet filled.", "Возможный климат: пустота — ещё не заполненная."),
        },
        ["major_16", "major_20", "cups_05"],
        ("Kule sarsar, Mahkeme çağırır, Kupa Beşlisi kaybın yasını taşır.", "The Tower shakes; Judgement calls; Five of Cups holds mourning of loss.", "Башня трясёт; Суд зовёт; Пятёрка Кубков держит траур потери."),
    ),
    M(14, ("Denge", "Temperance", "Умеренность"),
        (["harman", "tempo", "orta yol"], ["blend", "pacing", "middle"], ["смешение", "темп", "середина"]),
        (["aşırılık", "acele", "kopukluk"], ["excess", "rush", "disconnect"], ["избыток", "спешка", "разрыв"]),
        {
            "symbolic": ("İki akışın sabırla karışması.", "Two streams mixed with patience.", "Два потока, смешанные с терпением."),
            "love": ("İlişkide doz ve ritim konuşulabilir; ya hep ya hiç yorucudur.", "Dose and rhythm may be spoken in a bond; all-or-nothing tires.", "В связи могут говорить о мере и ритме; всё или ничего утомляет."),
            "career": ("İşbirliği ve tempo ayarı mümkün görünür.", "Collaboration and a tempo adjustment may be possible.", "Возможны сотрудничество и настройка темпа."),
            "money": ("Orta yol bütçe, savurganlık ile kısma arasında durabilir.", "A middle budget may sit between waste and austerity.", "Средний бюджет может стоять между растратой и урезкой."),
            "personal": ("Zıt yanlar aynı kapta durmayı öğrenebilir.", "Opposite sides may learn to rest in one vessel.", "Противоположные стороны могут учиться быть в одном сосуде."),
            "challenge": ("Denge, kararsızlık veya kendini yok sayma olabilir.", "Balance may become indecision or self-erasure.", "Баланс может стать нерешительностью или самозабвением."),
            "guidance": ("Biraz şunu, biraz bunu; hepsini bir anda değil.", "A little of this, a little of that; not everything at once.", "Немного того, немного этого; не всё сразу."),
            "future": ("Olası iklim: daha karışık, daha yumuşak bir ritim.", "A possible climate: a more mixed, softer rhythm.", "Возможный климат: более смешанный, более мягкий ритм."),
        },
        ["major_08", "cups_14", "pentacles_14"],
        ("Güç yumuşaklık, Kupa ve Tılsım Kralları ölçü ve maddeyi taşır.", "Strength is gentleness; Kings of Cups and Pentacles hold measure and matter.", "Сила — мягкость; Короли Кубков и Пентаклей держат меру и материю."),
    ),
    M(15, ("Şeytan", "The Devil", "Дьявол"),
        (["bağlanma", "gölge", "döngü"], ["attachment", "shadow", "loop"], ["привязанность", "тень", "петля"]),
        (["inkâr", "utanç", "suçlama"], ["denial", "shame", "blame"], ["отрицание", "стыд", "вина"]),
        {
            "symbolic": ("Seçilmiş gibi duran bir zincir; henüz bakılmamış bir arzu.", "A chain that looks chosen; a desire not yet looked at.", "Цепь, похожая на выбор; желание, на которое ещё не взглянули."),
            "love": ("Bağda bağımlılık veya oyun belirebilir; fark etmek ilk adımdır, mahkûm etmek değil.", "Attachment or a game may appear in a bond; noticing is a first step, not a sentence.", "В связи могут явиться зависимость или игра; заметить — первый шаг, не приговор."),
            "career": ("Tükenene kadar süren bir tempo veya toksik bir düzen fark edilebilir.", "A pace that runs to depletion, or a toxic arrangement, may be noticed.", "Может быть замечен темп до истощения или токсичный порядок."),
            "money": ("Alışkanlık harcaması veya statü oyunu görülebilir.", "Habit spending or a status game may be seen.", "Могут быть видны привычные траты или игра статуса."),
            "personal": ("Gölge, utandırılmadan bakılmayı isteyebilir.", "The shadow may want to be looked at without being shamed.", "Тень может хотеть взгляда без стыда."),
            "challenge": ("Zincir, 'ben böyleyim' hikâyesine kilitlenebilir.", "The chain may lock into an 'this is just who I am' story.", "Цепь может замкнуться в истории «я такой»."),
            "guidance": ("Bağı isimlendir; henüz kırmak zorunda değilsin, görmek yeter bir adım.", "Name the bond; you do not have to break it yet — seeing is already a step.", "Назови связь; ещё не обязательно рвать — увидеть уже шаг."),
            "future": ("Olası iklim: bir alışkanlığın daha görünür olması.", "A possible climate: a habit becoming more visible.", "Возможный климат: привычка становится виднее."),
        },
        ["major_08", "major_16", "pentacles_05"],
        ("Güç merhamet, Kule çatlak, Tılsım Beşlisi yoksunluk izidir.", "Strength is mercy; the Tower a crack; Five of Pentacles a trace of lack.", "Сила — милость; Башня — трещина; Пятёрка Пентаклей — след нехватки."),
    ),
    M(16, ("Kule", "The Tower", "Башня"),
        (["çatlak", "sarsıntı", "açığa çıkış"], ["crack", "shake", "uncovering"], ["трещина", "сотрясение", "обнажение"]),
        (["inkâr", "erteleme", "enkaz korkusu"], ["denial", "delay", "wreck-fear"], ["отрицание", "отсрочка", "страх обломков"]),
        {
            "symbolic": ("Sahte bir yapının sarsılması; ışığın içeri sızması.", "A false structure shaking; light leaking in.", "Ложный строй трясётся; свет просачивается внутрь."),
            "love": ("İlişkide bir gerçek görünür olabilir; bu, son kehaneti değildir.", "A truth in a bond may become visible; this is not a prophecy of the end.", "В связи может стать видна правда; это не пророчество конца."),
            "career": ("Bir plan veya unvan sarsılabilir; enkazın yanında neyin durduğuna bakılır.", "A plan or title may shake; one looks at what still stands beside the rubble.", "План или титул могут тряхнуть; смотрят, что ещё стоит у обломков."),
            "money": ("Beklenmedik bir kırılma fark edilebilir; panik tek yanıt olmak zorunda değildir.", "An unexpected break may be noticed; panic need not be the only reply.", "Может быть замечен неожиданный разрыв; паника не обязана быть единственным ответом."),
            "personal": ("Ego kalesi çatladığında nefes de girebilir.", "When the ego-fortress cracks, breath can enter too.", "Когда крепость эго трескается, может войти и дыхание."),
            "challenge": ("Sarsıntı, her şey bitti hikâyesine bağlanabilir.", "The shake may be bound into a story that everything is over.", "Сотрясение может стать историей, что всё кончено."),
            "guidance": ("Yıkılanı say; ayakta kalanı da say.", "Count what fell; count what still stands.", "Сочти упавшее; сочти и то, что ещё стоит."),
            "future": ("Olası iklim: daha çıplak bir gerçeklik — felaket ilanı değil.", "A possible climate: a barer reality — not a declaration of disaster.", "Возможный климат: более голая реальность — не объявление бедствия."),
        },
        ["major_13", "major_17", "swords_10"],
        ("Ölüm kapatır, Yıldız sakinleşir, Kılıç Onu zihinsel yük izidir.", "Death closes; the Star calms; Ten of Swords is a trace of mental load.", "Смерть закрывает; Звезда успокаивает; Десятка Мечей — след умственной ноши."),
    ),
    M(17, ("Yıldız", "The Star", "Звезда"),
        (["umut", "arınma", "sakin ışık"], ["hope", "rinsing", "quiet light"], ["надежда", "омовение", "тихий свет"]),
        (["sönükleşme", "erteleme", "inanmama"], ["dimming", "delay", "disbelief"], ["угасание", "отсрочка", "неверие"]),
        {
            "symbolic": ("Fırtınadan sonra duru bir ışık; vaat değil, nefes.", "Clear light after weather; not a vow, a breath.", "Чистый свет после погоды; не обет, дыхание."),
            "love": ("İlişkide yumuşak bir onarım mümkün görünebilir; acele mutluluk dayatması sakin değildir.", "Gentle repair in a bond may look possible; forcing quick happiness is not calm.", "В связи возможен мягкий ремонт; навязывать быстрое счастье не спокойно."),
            "career": ("Uzun vadeli bir yön, gürültüsüzce belirebilir.", "A longer heading may appear without noise.", "Более дальний курс может явиться без шума."),
            "money": ("Sade bir umut, abartılı kazanç hayalinden daha duru durabilir.", "A simple hope may sit more clearly than a inflated gain-fantasy.", "Простая надежда может быть яснее раздутой фантазии выигрыша."),
            "personal": ("İçeride yıkanmış bir açıklık hissedilebilir.", "A rinsed openness may be felt inside.", "Внутри может ощущаться промытая открытость."),
            "challenge": ("Umut, eylemden kopuk bir rüyaya kayabilir.", "Hope may slide into a dream unhooked from action.", "Надежда может стать сном без действия."),
            "guidance": ("Işığı küçük tut; sahne ışığı yapmak zorunda değilsin.", "Keep the light small; it does not have to be a spotlight.", "Держи свет малым; ему не обязательно быть прожектором."),
            "future": ("Olası iklim: daha sakin bir güven — garanti değil.", "A possible climate: quieter trust — not a guarantee.", "Возможный климат: более тихое доверие — не гарантия."),
        },
        ["major_00", "major_19", "cups_09"],
        ("Deli eşik, Güneş görünürlük, Kupa Dokuzu iç doyum izidir.", "The Fool is threshold; the Sun visibility; Nine of Cups inner enough-ness.", "Шут — порог; Солнце — видимость; Девятка Кубков — внутренняя достаточность."),
    ),
    M(18, ("Ay", "The Moon", "Луна"),
        (["belirsizlik", "rüya", "gölge yol"], ["unclearness", "dream", "shadow path"], ["неясность", "сон", "теневая тропа"]),
        (["korku", "yanılsama", "şüphe fırtınası"], ["fear", "illusion", "storm of doubt"], ["страх", "иллюзия", "буря сомнения"]),
        {
            "symbolic": ("Net olmayan bir yol; ay ışığında seçilen adım.", "A path not fully clear; a step chosen in moonlight.", "Путь не до конца ясный; шаг, выбранный при луне."),
            "love": ("Duygular bulanık olabilir; her gölge ihanet demek değildir.", "Feelings may be cloudy; not every shadow means betrayal.", "Чувства могут быть мутными; не каждая тень — измена."),
            "career": ("Belirsiz bir ortamda sezgi ile doğrulama birlikte yürüyebilir.", "In an unclear setting, sensing and checking may walk together.", "В неясной обстановке чутьё и проверка могут идти вместе."),
            "money": ("Bulanık bilgiyle karar vermek yorucu olabilir; beklemek de bir seçenektir.", "Deciding on cloudy information may tire; waiting is also an option.", "Решать по мутным сведениям утомляет; ждать — тоже выбор."),
            "personal": ("Korku, gerçekten büyük olmayabilir; yine de hissedilir.", "Fear may not be as large as it feels; it is still felt.", "Страх может быть не так велик, как кажется; его всё же чувствуют."),
            "challenge": ("Belirsizlik, her şeyi tehdit gibi okumaya kayabilir.", "Unclearness may slide into reading everything as threat.", "Неясность может стать чтением всего как угрозы."),
            "guidance": ("Yavaş yürü; her sese inanmak zorunda değilsin.", "Walk slowly; you do not have to believe every sound.", "Иди медленно; не обязательно верить каждому звуку."),
            "future": ("Olası iklim: daha sisli bir ara — sonsuza dek sürecek diye bir iddia yok.", "A possible climate: a foggier interval — no claim that it lasts forever.", "Возможный климат: более туманный промежуток — нет утверждения, что он вечен."),
        },
        ["major_02", "major_19", "swords_07"],
        ("Başrahibe giz, Güneş açıklık, Kılıç Yedilisi kaçış izidir.", "Priestess is the hidden; the Sun the open; Seven of Swords a trace of slipping away.", "Жрица — скрытое; Солнце — открытое; Семёрка Мечей — след ускользания."),
    ),
    M(19, ("Güneş", "The Sun", "Солнце"),
        (["aydınlık", "görünürlük", "canlılık"], ["clarity", "visibility", "aliveness"], ["ясность", "видимость", "живость"]),
        (["gösteriş", "yanılsama neşe", "körlük"], ["display", "false cheer", "blindness"], ["показ", "ложная радость", "слепота"]),
        {
            "symbolic": ("Gölgesiz kalan bir açıklık; ısının paylaşılması.", "An openness left without shade; warmth being shared.", "Открытость без тени; тепло, которым делятся."),
            "love": ("İlişkide neşe ve sadelik belirebilir; sahne neşesi ayrıdır.", "Joy and simplicity may appear in a bond; staged cheer is another thing.", "В связи могут явиться радость и простота; сценическая весёлость — иное."),
            "career": ("Emeğin görünür olması mümkün görünür.", "Work becoming visible may be possible.", "Возможно, труд станет видимым."),
            "money": ("Daha duru bir bolluk hissi gelebilir; şişkin vaat değildir.", "A clearer sense of enough may arrive; it is not an inflated promise.", "Может прийти более ясное чувство достаточности; это не раздутое обещание."),
            "personal": ("Kendini gizlemeden durmak hafifleyebilir.", "Standing without hiding oneself may feel lighter.", "Стоять, не прячась, может стать легче."),
            "challenge": ("Işık, başkasının gölgesini yok saymaya kayabilir.", "Light may slide into ignoring another’s shade.", "Свет может начать не замечать чужую тень."),
            "guidance": ("Parla; yakma.", "Shine; do not scorch.", "Свети; не обжигай."),
            "future": ("Olası iklim: daha görünür, daha sıcak bir ara.", "A possible climate: a more visible, warmer interval.", "Возможный климат: более видимый, более тёплый промежуток."),
        },
        ["major_17", "wands_03", "cups_06"],
        ("Yıldız sakin umut, Değnek Üçlüsü büyüme, Kupa Altılısı hatırlanan bağdır.", "The Star is quiet hope; Three of Wands growth; Six of Cups a remembered bond.", "Звезда — тихая надежда; Тройка Жезлов — рост; Шестёрка Кубков — вспомненная связь."),
    ),
    M(20, ("Mahkeme", "Judgement", "Суд"),
        (["çağrı", "gözden geçirme", "uyanış"], ["call", "review", "waking"], ["зов", "пересмотр", "пробуждение"]),
        (["kaçınma", "ağır yargı", "erteleme"], ["avoidance", "harsh verdict", "delay"], ["избегание", "суровый приговор", "отсрочка"]),
        {
            "symbolic": ("İsmiyle çağrılmak; geçmişi dinleyip ayağa kalkmak.", "Being called by name; hearing the past and standing up.", "Зов по имени; услышать прошлое и встать."),
            "love": ("Eski bir bağ veya söz yeniden duyulabilir; bu, geri dön kehaneti değildir.", "An old bond or word may be heard again; this is not a prophecy of return.", "Старая связь или слово могут быть услышаны снова; это не пророчество возврата."),
            "career": ("Bir çağrı, meslek veya hesaplaşma konuşulabilir.", "A calling, a vocation, or a reckoning may be spoken.", "Могут говорить о призвании, ремесле или разборе."),
            "money": ("Eski bir hesap yeniden açılabilir; utanç tek dil olmak zorunda değildir.", "An old account may reopen; shame need not be the only language.", "Старый счёт может открыться снова; стыд не обязан быть единственным языком."),
            "personal": ("Kendini yeniden adlandırmak mümkün görünebilir.", "Renaming oneself may look possible.", "Переименовать себя может казаться возможным."),
            "challenge": ("Çağrı, acımasız bir mahkemeye dönüşebilir.", "The call may become a merciless court.", "Зов может стать беспощадным судом."),
            "guidance": ("Duy; hemen hüküm verme.", "Hear; do not pass sentence at once.", "Услышь; не выноси приговор сразу."),
            "future": ("Olası iklim: bir uyanış aralığı — yeni hayat garantisi değil.", "A possible climate: an interval of waking — not a guarantee of a new life.", "Возможный климат: промежуток пробуждения — не гарантия новой жизни."),
        },
        ["major_11", "major_13", "major_21"],
        ("Adalet ölçü, Ölüm kapanış, Dünya tamamlanmadır.", "Justice is measure; Death a closing; the World completion.", "Справедливость — мера; Смерть — закрытие; Мир — завершение."),
    ),
    M(21, ("Dünya", "The World", "Мир"),
        (["tamamlanma", "bütünlük", "eşik sonu"], ["completion", "wholeness", "end of a threshold"], ["завершение", "целостность", "конец порога"]),
        (["eksik iş", "dağılma", "kapanmama"], ["unfinished work", "scatter", "unclosed"], ["недоделанное", "рассев", "незакрытость"]),
        {
            "symbolic": ("Bir çemberin kapanışı; dansın sakin hali.", "A circle closing; the calm form of a dance.", "Круг закрывается; спокойный вид танца."),
            "love": ("Bir bağ olgun bir duruşa gelebilir; sonsuzluk iddiası taşımaz.", "A bond may arrive at a mature stance; it carries no claim of forever.", "Связь может прийти к зрелой позе; в ней нет утверждения навсегда."),
            "career": ("Bir evre tamamlanmak isteyebilir; alkış şart değildir.", "A phase of work may want completion; applause is not required.", "Фаза дела может хотеть завершения; аплодисменты не обязательны."),
            "money": ("Bir döngünün hesabı kapanabilir; yeni döngü henüz yazılmamıştır.", "An account of a cycle may close; the next cycle is not yet written.", "Счёт цикла может закрыться; следующий цикл ещё не написан."),
            "personal": ("Parçaların bir arada durduğu bir an hissedilebilir.", "A moment may be felt when the pieces stand together.", "Может быть миг, когда части стоят вместе."),
            "challenge": ("Tamamlanma, durağanlığa veya yeni bir şeye korkuya kayabilir.", "Completion may slide into stagnation or fear of the next thing.", "Завершение может стать застоем или страхом следующего."),
            "guidance": ("Çemberi kapat; hemen yeni bir circusa atlama.", "Close the circle; do not leap into a new circus at once.", "Закрой круг; не прыгай сразу в новый цирк."),
            "future": ("Olası iklim: bir eşiğin sonu ve henüz isimsiz bir sonrası.", "A possible climate: the end of a threshold and a not-yet-named after.", "Возможный климат: конец порога и ещё не названное после."),
        },
        ["major_00", "major_10", "major_17"],
        ("Deli yeni eşik, Çark dönüş, Yıldız sakin ışıktır.", "The Fool is a new threshold; the Wheel a turn; the Star quiet light.", "Шут — новый порог; Колесо — поворот; Звезда — тихий свет."),
    ),
]
