"""Wands 5–14 and Cups 1–14."""

from oracly_tarot_minors_base import C

WANDS_REST = [
    C("wands", 5, ("sınav|sürtünme|onur", "trial|friction|honor", "испытание|трение|честь"),
      ("yenilgi hikâyesi|öfke|vazgeçiş", "defeat-story|anger|giving up", "история поражения|гнев|сдача"),
      ("Kıvılcımın sınandığı yer; kaybolmuş değildir.", "Where the spark is tested; it is not gone.", "Место испытания искры; она не исчезла."),
      ("Bağda bir gerilim onur meselesine dönebilir.", "Tension in a bond may turn into a matter of honor.", "Напряжение в связи может стать делом чести."),
      ("İş yerinde bir direnç hissedilebilir.", "Resistance at work may be felt.", "На работе может ощущаться сопротивление."),
      ("Kaynak gerilimi, savaş gibi okunmamalıdır.", "A resource strain need not be read as a war.", "Натяжение средств не обязательно читать как войну."),
      ("İçeride 'hâlâ ayaktayım' diyen bir ateş olabilir.", "An inner fire saying 'I am still standing' may be present.", "Внутри может быть огонь «я ещё стою»."),
      ("Sınav, düşman hikâyesine kayabilir.", "The trial may slide into an enemy story.", "Испытание может стать историей врага."),
      ("Onurunu koru; kimseyi yakma.", "Keep your honor; do not burn anyone.", "Храни честь; никого не сжигай."),
      ("Olası iklim: sürtünmeli bir ara.", "A possible climate: an interval of friction.", "Возможный климат: промежуток трения."),
      ["swords_05", "major_08", "wands_07"],
      ("Kılıç Beşlisi zihin çatışması, Güç merhamet, Değnek Yedilisi duruştur.", "Five of Swords is mental clash; Strength mercy; Seven of Wands stance.", "Пятёрка Мечей — умственный спор; Сила — милость; Семёрка Жезлов — стойка.")),
    C("wands", 6, ("geçiş|tanıma|nefes", "crossing|notice|breath", "переход|признание|дыхание"),
      ("övünç|geçmişe takılma|sahne", "boast|stuck in past|stage", "похвальба|застрять в прошлом|сцена"),
      ("Bir eşiği geçmiş ateş; henüz sonsuz zafer değil.", "Fire that has crossed a threshold; not endless triumph.", "Огонь, перешедший порог; не вечная победа."),
      ("Bağda bir yumuşama veya görünürlük belirebilir.", "Softening or visibility may appear in a bond.", "В связи может явиться смягчение или видимость."),
      ("Emeğin fark edilmesi mümkün görünür.", "Effort being noticed may be possible.", "Возможно, усилие заметят."),
      ("Küçük bir rahatlama hissi gelebilir.", "A small ease around means may arrive.", "Может прийти малое облегчение вокруг средств."),
      ("İçeride omuzların inmesi hissedilebilir.", "Shoulders dropping may be felt inside.", "Внутри может ощущаться, как опускаются плечи."),
      ("Geçiş, sahne alkışına bağlanabilir.", "The crossing may be bound to staged applause.", "Переход может привязаться к сценическим аплодисментам."),
      ("Geçtiğini fark et; taht kurma.", "Notice that you crossed; do not build a throne.", "Заметь, что перешёл; не строй трон."),
      ("Olası iklim: daha açık bir geçit.", "A possible climate: a clearer passage.", "Возможный климат: более ясный проход."),
      ["cups_06", "major_19", "pentacles_06"],
      ("Kupa Altılısı hatıra, Güneş görünürlük, Tılsım Altılısı paylaşım izidir.", "Six of Cups memory; Sun visibility; Six of Pentacles sharing.", "Шестёрка Кубков — память; Солнце — видимость; Шестёрка Пентаклей — делёж.")),
    C("wands", 7, ("duruş|sınır|tek başına ateş", "stance|boundary|fire alone", "стойка|граница|огонь в одиночку"),
      ("kuşatma hissi|sertlik|izolasyon", "siege-feeling|harshness|isolation", "ощущение осады|жёсткость|изоляция"),
      ("Tek noktadan korunan kıvılcım.", "A spark guarded from one point.", "Искра, охраняемая с одной точки."),
      ("İlişkide kendini anlatma ihtiyacı artabilir.", "A need to speak for oneself may rise in a bond.", "В связи может усилиться нужда говорить за себя."),
      ("İş ideallerini korumak gündeme gelebilir.", "Protecting work ideals may come forward.", "Может выйти защита рабочих идеалов."),
      ("Kaynağı savurmadan tutmak sakin duruştur.", "Holding a resource without scattering it is a calm stance.", "Держать ресурс, не разбрасывая, — спокойная поза."),
      ("İçeride 'ben buradayım' diyen bir omurga olabilir.", "A spine saying 'I am here' may live inside.", "Внутри может жить хребет «я здесь»."),
      ("Duruş, herkese karşı savaş gibi okunabilir.", "Stance may be read as war against everyone.", "Стойка может читаться как война со всеми."),
      ("Yerini tut; düşman üretme.", "Hold your ground; do not manufacture enemies.", "Держи место; не производи врагов."),
      ("Olası iklim: daha net bir sınır.", "A possible climate: a clearer boundary.", "Возможный климат: более ясная граница."),
      ["major_04", "swords_07", "wands_09"],
      ("İmparator yapı, Kılıç Yedilisi kayış, Değnek Dokuzu son ateştir.", "Emperor structure; Seven of Swords slip; Nine of Wands last fire.", "Император — строй; Семёрка Мечей — ускользание; Девятка Жезлов — последний огонь.")),
    C("wands", 8, ("hız|haber|akış", "speed|news|flow", "скорость|весть|поток"),
      ("acele|dağılma|sabırsızlık", "haste|scatter|impatience", "спешка|рассев|нетерпение"),
      ("Havada giden oklar; henüz varış değil.", "Arrows in air; not yet arrival.", "Стрелы в воздухе; ещё не прибытие."),
      ("İlişkide tempo artabilir; her hız yakınlık değildir.", "Tempo in a bond may rise; not every speed is closeness.", "Темп связи может вырасти; не всякая скорость — близость."),
      ("Haber, teslim, hareket işte yoğunlaşabilir.", "News, delivery, or motion at work may thicken.", "На работе могут сгуститься вести, сдача, движение."),
      ("Hızlı bir kaynak hareketi görülebilir; spekülasyon şart değildir.", "A fast move of means may be seen; speculation is not required.", "Может быть видно быстрое движение средств; спекуляция не обязательна."),
      ("İçeride acele bir rüzgâr esebilir.", "A hurried wind may blow inside.", "Внутри может дуть торопливый ветер."),
      ("Hız, kaçırmış gibi hissettirebilir.", "Speed may make one feel already late.", "Скорость может заставить чувствовать себя опоздавшим."),
      ("Akışa izin ver; her oku kovala ma.", "Allow the flow; do not chase every arrow.", "Позволь потоку; не гонись за каждой стрелой."),
      ("Olası iklim: daha hızlı bir ara.", "A possible climate: a quicker interval.", "Возможный климат: более быстрый промежуток."),
      ["swords_08", "major_10", "cups_08"],
      ("Kılıç Sekizlisi sıkışma, Çark dönüş, Kupa Sekizlisi ayrılış izidir.", "Eight of Swords tightness; Wheel a turn; Eight of Cups leaving.", "Восьмёрка Мечей — теснота; Колесо — поворот; Восьмёрка Кубков — уход.")),
    C("wands", 9, ("son ateş|nöbet|dayanıklılık", "last fire|watch|endurance", "последний огонь|дозор|стойкость"),
      ("tükenmişlik|şüphe|yalnız savaş", "exhaustion|doubt|lone war", "истощение|сомнение|одинокая война"),
      ("Korunan son kıvılcım; bitmiş değildir.", "The last guarded spark; it is not finished.", "Последняя охраняемая искра; это не конец."),
      ("Bağda yorgun bir sadakat belirebilir.", "Tired loyalty may appear in a bond.", "В связи может явиться усталая верность."),
      ("Uzun bir eforun son dilimi işte hissedilebilir.", "The last stretch of a long effort may be felt at work.", "На работе может ощущаться последний отрезок долгого усилия."),
      ("Kaynak az görünse de tamamen yok olmayabilir.", "Means may look thin without being gone.", "Средства могут казаться тонкими, не исчезнув."),
      ("İçeride nöbet tutan bir yorgunluk olabilir.", "A fatigue on watch may live inside.", "Внутри может жить усталость на дозоре."),
      ("Nöbet, kimseye güvenmemeye kayabilir.", "The watch may slide into trusting no one.", "Дозор может стать недоверием ко всем."),
      ("Dinlen; kalkanı bırakmak zorunda değilsin.", "Rest; you do not have to drop the shield.", "Отдохни; не обязательно бросать щит."),
      ("Olası iklim: dayanıklılığın sessiz hali.", "A possible climate: the quiet form of endurance.", "Возможный климат: тихий вид стойкости."),
      ["major_08", "wands_10", "pentacles_09"],
      ("Güç merhamet, Değnek Onu yük, Tılsım Dokuzu yeterlilik izidir.", "Strength mercy; Ten of Wands load; Nine of Pentacles enough-ness.", "Сила — милость; Десятка Жезлов — ноша; Девятка Пентаклей — достаточность.")),
    C("wands", 10, ("yük|fazla ateş|sorumluluk", "load|too much fire|duty", "ноша|слишком много огня|долг"),
      ("kahramanlık oyunu|çöküş korkusu|delege edememe", "hero-play|collapse-fear|cannot delegate", "игра героя|страх обвала|неумение поручить"),
      ("Çok fazla değnek; omuzların dili.", "Too many wands; the language of shoulders.", "Слишком много жезлов; язык плеч."),
      ("İlişkide tek kişinin taşıması yorucu olabilir.", "One person carrying a bond may tire.", "Когда связь несёт один, это утомляет."),
      ("İş yükü görünür olabilir; kahraman olmak şart değildir.", "Work load may be visible; being the hero is not required.", "Нагрузка дела может быть видна; быть героем не обязательно."),
      ("Çok iş, kaynağı da dağıtabilir.", "Too many tasks may also scatter means.", "Слишком много дел может рассеять и средства."),
      ("İçeride 'hepsini ben' cümlesi duruyor olabilir.", "The sentence 'I will take it all' may be standing inside.", "Внутри может стоять фраза «я возьму всё»."),
      ("Yük, kimliğe dönüşebilir.", "The load may become identity.", "Ноша может стать личностью."),
      ("Bir değneği bırak; hepsini düşürme.", "Set one wand down; do not drop them all.", "Опусти один жезл; не бросай все."),
      ("Olası iklim: paylaşılmayı bekleyen bir ağırlık.", "A possible climate: a weight waiting to be shared.", "Возможный климат: тяжесть, ждущая разделения."),
      ["major_10", "pentacles_10", "cups_10"],
      ("Çark döngü, Tılsım ve Kupa Onu masa ve bağ izidir.", "Wheel is cycle; Tens of Pentacles and Cups are table and bond.", "Колесо — цикл; Десятки Пентаклей и Кубков — стол и связь.")),
    C("wands", 11, ("haber|öğrenci ateşi|merak", "message|student fire|curiosity", "весть|огонь ученика|любопытство"),
      ("dağınık heves|övünç|dinlememe", "scattered zeal|boast|not listening", "рассеянный пыл|похвальба|неслушание"),
      ("Yeni bir ateşin habercisi; usta değil.", "Messenger of a new fire; not yet a master.", "Вестник нового огня; ещё не мастер."),
      ("Bağda taze, biraz acemi bir sıcaklık belirebilir.", "A fresh, slightly unripe warmth may appear in a bond.", "В связи может явиться свежая, чуть незрелая теплота."),
      ("Öğrenilecek bir zanaat kapısı aralanabilir.", "A door into a craft to be learned may open a little.", "Дверь в ремесло, которому учатся, может чуть открыться."),
      ("Küçük bir fırsat haberi gelebilir; servet değildir.", "News of a small opening may come; it is not a fortune.", "Может прийти весть о малом отверстии; это не состояние."),
      ("İçeride öğrenci meraka dönüşebilir.", "The inner student may turn into curiosity.", "Внутренний ученик может стать любопытством."),
      ("Haberci, her yerde kıvılcım aramaya kayabilir.", "The messenger may slide into hunting sparks everywhere.", "Вестник может начать искать искры всюду."),
      ("Sor; bilmişlik yapma.", "Ask; do not perform knowingness.", "Спроси; не играй всезнайку."),
      ("Olası iklim: öğrenmeye açık bir ateş.", "A possible climate: fire open to learning.", "Возможный климат: огонь, открытый учению."),
      ["cups_11", "swords_11", "major_01"],
      ("Kupa ve Kılıç Habercileri duygu ve dil; Büyücü el izidir.", "Pages of Cups and Swords are feeling and speech; Magician the hand.", "Пажи Кубков и Мечей — чувство и речь; Маг — рука.")),
    C("wands", 12, ("yolculuk|tutku|ileri ateş", "journey|passion|forward fire", "путь|страсть|огонь вперёд"),
      ("acele|dağınık tutku|savaş arayışı", "haste|scattered passion|seeking battle", "спешка|рассеянная страсть|поиск битвы"),
      ("Hareket halindeki ateş; varış noktası henüz ev değildir.", "Fire in motion; the destination is not yet home.", "Огонь в движении; место прибытия ещё не дом."),
      ("İlişkide coşku belirebilir; köklenme ayrı bir iştir.", "Ardor may appear in a bond; taking root is another task.", "В связи может явиться пыл; укоренение — другое дело."),
      ("İş için yola çıkmak mümkün görünür.", "Setting out for work may be possible.", "Возможно выйти в путь ради дела."),
      ("Hareket, harcamayı da hızlandırabilir.", "Motion may also speed spending.", "Движение может ускорить и траты."),
      ("İçeride duramayan bir at olabilir.", "A horse that cannot stand still may live inside.", "Внутри может жить конь, который не стоит."),
      ("Yol, kaçış olabilir.", "The road may be escape.", "Дорога может быть бегством."),
      ("İlerle; yakarak geçme.", "Go forward; do not pass by burning.", "Иди вперёд; не проходи сжигая."),
      ("Olası iklim: daha hareketli bir tutku.", "A possible climate: more mobile passion.", "Возможный климат: более подвижная страсть."),
      ["cups_12", "major_07", "pentacles_12"],
      ("Kupa Şövalyesi duygu yolculuğu, Savaş Arabası yön, Tılsım Şövalyesi madde yoludur.", "Knight of Cups is feeling-travel; Chariot heading; Knight of Pentacles matter-road.", "Рыцарь Кубков — путь чувства; Колесница — курс; Рыцарь Пентаклей — дорога материи.")),
    C("wands", 13, ("sıcak ev|olgun ateş|davet", "warm house|mature fire|invitation", "тёплый дом|зрелый огонь|приглашение"),
      ("kontrol|kıskançlık|sönükleşme", "control|envy|dimming", "контроль|зависть|угасание"),
      ("Evin içindeki ateş; sahne ateşi değil.", "Fire inside a house; not stage-fire.", "Огонь внутри дома; не сценический огонь."),
      ("Bağda olgun bir sıcaklık barınabilir.", "A mature warmth may dwell in a bond.", "В связи может жить зрелая теплота."),
      ("İş ortamını ısıtmak, yakmadan mümkün görünebilir.", "Warming a work climate without scorching may look possible.", "Согреть рабочий климат, не обжигая, может казаться возможным."),
      ("Kaynakları cömert ve ölçülü tutmak sakin duruştur.", "Holding means generously and in measure is a calm stance.", "Держать средства щедро и в мере — спокойная поза."),
      ("İçeride başkalarını ısıtabilen bir yetişkin ateş olabilir.", "An adult fire able to warm others may live inside.", "Внутри может жить взрослый огонь, способный греть других."),
      ("Sıcaklık, sahiplenmeye kayabilir.", "Warmth may slide into possessing.", "Теплота может стать присвоением."),
      ("Ocağı canlı tut; kimseyi içine kapatma.", "Keep the hearth alive; do not shut anyone inside it.", "Держи очаг живым; никого в него не запирай."),
      ("Olası iklim: daha ev gibi bir irade.", "A possible climate: a more household will.", "Возможный климат: более домашняя воля."),
      ["cups_13", "major_03", "wands_14"],
      ("Kupa Kraliçesi duygu ev, İmparatoriçe bakım, Değnek Kralı yöndür.", "Queen of Cups is feeling-house; Empress care; King of Wands heading.", "Королева Кубков — дом чувства; Императрица — забота; Король Жезлов — курс.")),
    C("wands", 14, ("yön veren ateş|sorumlu kıvılcım|vizyon", "directing fire|responsible spark|vision", "направляющий огонь|ответственная искра|видение"),
      ("baskı|ego|dinlememe", "pressure|ego|not listening", "давление|эго|неслушание"),
      ("Ateşi bir yöne çağıran duruş.", "A stance that calls fire into a heading.", "Поза, зовущая огонь в курс."),
      ("İlişkide net bir yön teklifi belirebilir; dayatma ayrıdır.", "A clear heading may be offered in a bond; imposing it is another matter.", "В связи может быть предложен ясный курс; навязывать его — иное."),
      ("İş için vizyon ve sorumluluk konuşulabilir.", "Vision and responsibility at work may be spoken.", "На работе могут говорить о видении и ответственности."),
      ("Kaynakları bir niyete bağlamak mümkün görünür.", "Binding means to an intent may be possible.", "Возможно связать средства с намерением."),
      ("İçeride hem lider hem dinleyen bir ateş istenebilir.", "A fire that both leads and listens may be wanted inside.", "Внутри может быть нужен огонь, который и ведёт, и слушает."),
      ("Yön, başkalarının ateşini söndürmeye kayabilir.", "Heading may slide into putting out others' fire.", "Курс может начать гасить чужой огонь."),
      ("Yön ver; yakarak yönetme.", "Give heading; do not rule by burning.", "Дай курс; не правь сжигая."),
      ("Olası iklim: daha sorumlu bir irade.", "A possible climate: more responsible will.", "Возможный климат: более ответственная воля."),
      ["major_04", "swords_14", "wands_13"],
      ("İmparator yapı, Kılıç Kralı zihin yönü, Değnek Kraliçesi ev ateşidir.", "Emperor is structure; King of Swords mental heading; Queen of Wands household fire.", "Император — строй; Король Мечей — умственный курс; Королева Жезлов — домашний огонь.")),
]

CUPS = [
    C("cups", 1, ("açılış|duygu|kadeh", "opening|feeling|cup", "открытие|чувство|чаша"),
      ("taşma|kapanma|duygu korkusu", "overflow|closing|fear of feeling", "перелив|закрытие|страх чувства"),
      ("İlk su; henüz hikâye olmayan bir duygu.", "First water; a feeling not yet a story.", "Первая вода; чувство, ещё не ставшее историей."),
      ("Bağda taze bir açıklık belirebilir.", "A fresh openness may appear in a bond.", "В связи может явиться свежая открытость."),
      ("İşin insani yanı hatırlanabilir.", "The human side of work may be remembered.", "Может вспомниться человеческая сторона дела."),
      ("Cömertlik ile savurganlık karışmamalıdır.", "Generosity and waste should not be mixed.", "Щедрость и растрата не должны смешиваться."),
      ("İçeride yumuşak bir kap uyanabilir.", "A soft vessel may wake inside.", "Внутри может проснуться мягкий сосуд."),
      ("Duygu, taşmaya kayabilir.", "Feeling may slide into overflow.", "Чувство может стать переливом."),
      ("Kadehi tut; herkese dökmek zorunda değilsin.", "Hold the cup; you do not have to pour it for everyone.", "Держи чашу; не обязательно лить её всем."),
      ("Olası iklim: duygusal bir açıklık.", "A possible climate: an emotional opening.", "Возможный климат: эмоциональное открытие."),
      ["wands_01", "major_02", "cups_02"],
      ("Değnek Ası irade, Başrahibe giz, Kupa İkilisi bağ izidir.", "Ace of Wands is will; Priestess the hidden; Two of Cups a bond.", "Туз Жезлов — воля; Жрица — скрытое; Двойка Кубков — связь.")),
]
