"""Major Arcana 3–21."""

from oracly_tarot_majors import M

MAJORS_REST = [
    M(3, ("İmparatoriçe", "The Empress", "Императрица"),
        (["besleme", "büyüme", "beden"], ["tending", "growth", "body"], ["забота", "рост", "тело"]),
        (["boğma", "tükenme", "savurganlık"], ["smothering", "depletion", "excess"], ["удушение", "истощение", "избыток"]),
        {
            "symbolic": ("Büyümeyi savunan bir şefkat; toprağın yavaş ritmi.", "Care that defends growth; the slow rhythm of soil.", "Забота, защищающая рост; медленный ритм почвы."),
            "love": ("İlişkide besleyici bir sıcaklık belirebilir; sınır olmadan şefkat yorucu olabilir.", "Nourishing warmth may appear in a bond; care without a boundary can tire.", "В связи может появиться питающая теплота; забота без границы утомляет."),
            "career": ("Bir işin filizlenmesi mümkün görünür; aceleye değil bakıma ihtiyaç duyabilir.", "A piece of work may be sprouting; it may need tending more than speed.", "Дело может прорастать; ему может быть нужен уход, а не скорость."),
            "money": ("Bolluk bir his olarak gelebilir; paylaşım ile savurganlık aynı şey değildir.", "Abundance may be felt; sharing and wasting are not the same.", "Может ощущаться изобилие; делиться и растрачивать — не одно и то же."),
            "personal": ("Beden, dinlenme ve yaratma arasında daha nazik bir yer isteyebilir.", "The body may ask for a kinder place between rest and making.", "Тело может просить более мягкое место между отдыхом и творчеством."),
            "challenge": ("Bakım, kontrol veya kendini unutmaya kayabilir.", "Care may slide into control or self-erasure.", "Забота может стать контролем или самозабвением."),
            "guidance": ("Bir şeyi büyüt; onu sıkıştırma.", "Grow something; do not squeeze it.", "Выращивай; не сжимай."),
            "future": ("Olası iklim: daha verimli, daha yavaş bir bakım.", "A possible climate: more fertile, slower tending.", "Возможный климат: более плодородная, более медленная забота."),
        },
        ["major_04", "pentacles_03", "cups_03"],
        ("İmparator yapı verir; Tılsım ve Kupa üçlüleri büyüme ve bağ izlerini taşır.", "The Emperor offers structure; Threes of Pentacles and Cups carry growth and bond.", "Император даёт строй; Тройки Пентаклей и Кубков несут рост и связь."),
    ),
    M(4, ("İmparator", "The Emperor", "Император"),
        (["yapı", "sınır", "sorumluluk"], ["structure", "boundary", "responsibility"], ["строй", "граница", "ответственность"]),
        (["katılık", "mesafe", "baskı"], ["rigidity", "distance", "pressure"], ["жёсткость", "дистанция", "давление"]),
        {
            "symbolic": ("Düzeni koruyan bir omurga; sınırın sakin hali.", "A spine that keeps order; the calm form of a boundary.", "Хребет, держащий порядок; спокойный вид границы."),
            "love": ("Bağda netlik ve güven ihtiyacı öne çıkabilir; yumuşaklık unutulmamalıdır.", "A need for clarity and safety may rise in a bond; softness still belongs.", "В связи может усилиться нужда в ясности и опоре; мягкость всё же нужна."),
            "career": ("Rol, kural veya çerçeve konuşulabilir; liderlik dinlemekle de kurulur.", "Role, rule, or frame may be in question; leadership is also made by listening.", "Могут встать роль, правило, рамка; лидерство также строится слушанием."),
            "money": ("Plan ve sınır, dağınık harcamayı sakinleştirebilir.", "A plan and a limit may quiet scattered spending.", "План и предел могут успокоить разброс трат."),
            "personal": ("İçeride bir yetişkin duruşu istenebilir: hem koruyan hem esneyen.", "An inner adult stance may be wanted: protective and still able to bend.", "Внутри может быть нужен взрослый стан: и защита, и гибкость."),
            "challenge": ("Düzen, başkalarını küçültmeye dönüşebilir.", "Order may turn into shrinking others.", "Порядок может начать уменьшать других."),
            "guidance": ("Çerçeveyi kur; duvarı putlaştırma.", "Build a frame; do not worship the wall.", "Построй раму; не делай стену кумиром."),
            "future": ("Olası iklim: daha duru bir sorumluluk alanı.", "A possible climate: a clearer field of responsibility.", "Возможный климат: более ясное поле ответственности."),
        },
        ["major_03", "major_11", "pentacles_04"],
        ("İmparatoriçe bakım, Adalet ölçü, Tılsım Dördü durağanlık izi taşır.", "The Empress tends; Justice measures; Four of Pentacles holds stillness.", "Императрица растит; Справедливость меряет; Четвёрка Пентаклей держит покой."),
    ),
    M(5, ("Aziz", "The Hierophant", "Иерофант"),
        (["öğreti", "aidiyet", "ritüel"], ["teaching", "belonging", "ritual"], ["учение", "принадлежность", "ритуал"]),
        (["kör uyum", "dogma", "isyan"], ["blind fit", "dogma", "revolt"], ["слепое согласие", "догма", "бунт"]),
        {
            "symbolic": ("Paylaşılan bir yol; bir odada birlikte durmanın bilgeliği.", "A shared path; the wisdom of standing together in a room.", "Общий путь; мудрость стоять вместе в одной комнате."),
            "love": ("İlişki bir biçim, söz veya gelenek arıyor olabilir; iç ses de yerini korur.", "A bond may seek a form, vow, or custom; the inner voice still has a seat.", "Связь может искать форму, слово, обычай; внутренний голос всё же имеет место."),
            "career": ("Mentor, kurum veya ortak dil gündeme gelebilir.", "A mentor, an institution, or a shared language may come forward.", "Могут выйти наставник, институт или общий язык."),
            "money": ("Bilinen yollar güven verebilir; her yeni yol daha doğru değildir.", "Familiar paths may feel safer; a new path is not always truer.", "Привычные пути могут казаться спокойнее; новый путь не всегда вернее."),
            "personal": ("Aidiyet ihtiyacı ile kendi yolunun gerilimi belirginleşebilir.", "The tension between belonging and one's own path may sharpen.", "Напряжение между принадлежностью и своим путём может стать яснее."),
            "challenge": ("Öğreti, düşünmeden tekrar etmeye kayabilir.", "Teaching may slide into repetition without thought.", "Учение может стать повторением без мысли."),
            "guidance": ("Kapıyı çal; anahtarı kimseye teslim etme.", "Knock at the door; do not hand over the key.", "Постучи в дверь; не отдавай ключ."),
            "future": ("Olası iklim: paylaşılan bir pratik veya öğreti etrafında durmak.", "A possible climate: standing around a shared practice or teaching.", "Возможный климат: стояние вокруг общей практики или учения."),
        },
        ["major_02", "major_06", "cups_10"],
        ("Başrahibe iç oda, Aşıklar seçim, Kupa Onu paylaşılmış masa izidir.", "Priestess is the inner room; Lovers the choice; Ten of Cups a shared table.", "Жрица — внутренняя комната; Влюблённые — выбор; Десятка Кубков — общий стол."),
    ),
    M(6, ("Aşıklar", "The Lovers", "Влюблённые"),
        (["seçim", "uyum", "değer"], ["choice", "accord", "value"], ["выбор", "согласие", "ценность"]),
        (["kararsızlık", "uyumsuzluk", "kaçınma"], ["indecision", "mismatch", "evasion"], ["нерешительность", "несовпадение", "уклонение"]),
        {
            "symbolic": ("Kalp ile değerin aynı anda seçilmesi.", "Heart and value chosen at the same time.", "Сердце и ценность выбираются вместе."),
            "love": ("Bir bağ, dürüst bir seçim isteyebilir; çekim tek başına yeter demek zorunda değildir.", "A bond may ask for an honest choice; attraction alone need not be called enough.", "Связь может просить честный выбор; одного влечения не обязательно называть достаточным."),
            "career": ("İki yol arasında durulabilir; değerlerle uyum, hızdan daha sakin bir ölçü olabilir.", "One may stand between two work paths; accord with values can be a calmer measure than speed.", "Можно стоять между двумя путями дела; согласие с ценностями спокойнее скорости."),
            "money": ("Harcama bir değer seçimini ele verebilir.", "Spending may reveal a choice of values.", "Расход может выявить выбор ценностей."),
            "personal": ("Kendiyle yapılan bir anlaşma gündeme gelebilir.", "An agreement with oneself may come forward.", "Может выйти соглашение с самим собой."),
            "challenge": ("Seçmemek de bir seçim gibi ağırlaşabilir.", "Not choosing may become as heavy as a choice.", "Не выбирать может стать так же тяжело, как выбор."),
            "guidance": ("Hangisinin sana ait olduğunu sor; hangisinin parlak göründüğünü değil.", "Ask which belongs to you, not which merely shines.", "Спроси, что твоё, а не что просто блестит."),
            "future": ("Olası iklim: daha bilinçli bir birlik veya ayrışma — ikisi de kehanet değildir.", "A possible climate: a more conscious union or parting — neither is a prophecy.", "Возможный климат: более сознательный союз или расхождение — ни то ни другое не пророчество."),
        },
        ["major_11", "cups_02", "swords_02"],
        ("Adalet ölçü getirir; Kupa ve Kılıç ikilileri bağ ile mesafe gerilimini taşır.", "Justice brings measure; Twos of Cups and Swords hold bond and distance.", "Справедливость даёт меру; Двойки Кубков и Мечей держат связь и дистанцию."),
    ),
    M(7, ("Savaş Arabası", "The Chariot", "Колесница"),
        (["yön", "irade", "hareket"], ["heading", "will", "motion"], ["курс", "воля", "движение"]),
        (["dağılma", "zorlama", "yol kaybı"], ["split", "forcing", "lost heading"], ["разрыв", "нажим", "потеря курса"]),
        {
            "symbolic": ("Zıt güçleri aynı yöne çağıran irade.", "Will that calls opposing forces toward one heading.", "Воля, зовущая противоположные силы к одному курсу."),
            "love": ("İlişkide ilerleme isteği belirebilir; diğerini sürüklemek ayrı bir konudur.", "A wish to move forward in a bond may appear; pulling the other is a different matter.", "Может появиться желание двигать связь вперёд; тащить другого — иное дело."),
            "career": ("Hedefe doğru toplanmış bir çaba mümkün görünür.", "A gathered effort toward a goal may be possible.", "Возможно собранное усилие к цели."),
            "money": ("Kararlı bir adım kaynakları hizalayabilir; acele risk ayrı bir sorudur.", "A firm step may align resources; haste-as-risk is a separate question.", "Твёрдый шаг может выстроить средства; спешка как риск — отдельный вопрос."),
            "personal": ("Dağınık arzular tek bir yöne çekilebilir.", "Scattered wants may be drawn into one heading.", "Разбросанные желания могут собраться в один курс."),
            "challenge": ("İrade, dinlemeyi ezip geçebilir.", "Will may crush listening.", "Воля может раздавить слушание."),
            "guidance": ("Dizgini tut; atları incitme.", "Hold the reins; do not harm the horses.", "Держи поводья; не рань коней."),
            "future": ("Olası iklim: daha toplanmış bir hareket.", "A possible climate: more gathered motion.", "Возможный климат: более собранное движение."),
        },
        ["major_08", "wands_07", "major_01"],
        ("Güç yumuşak irade, Değnek Yedilisi duruş, Büyücü el izidir.", "Strength is gentle will; Seven of Wands stance; Magician the hand.", "Сила — мягкая воля; Семёрка Жезлов — стойка; Маг — рука."),
    ),
    M(8, ("Güç", "Strength", "Сила"),
        (["yumuşak güç", "sabır", "merhamet"], ["gentle force", "patience", "mercy"], ["мягкая сила", "терпение", "милость"]),
        (["bastırma", "öfke", "özgüvensizlik"], ["suppression", "anger", "self-doubt"], ["подавление", "гнев", "неуверенность"]),
        {
            "symbolic": ("Sertliği ezmeden tutan bir cesaret.", "Courage that holds heat without crushing it.", "Смелость, которая держит жар, не раздавливая его."),
            "love": ("İlişkide sabır ve şefkat öne çıkabilir; suskunluk korku da olabilir.", "Patience and kindness may come forward in a bond; silence can also be fear.", "В связи могут выйти терпение и тепло; молчание бывает и страхом."),
            "career": ("Sakin bir dayanıklılık işe yarayabilir; bağırarak yönetmek gerekmez.", "Quiet endurance may serve work; shouting is not required to lead.", "Тихая стойкость может служить делу; криком руководить не обязательно."),
            "money": ("Sabırlı bir tutum, panik harcamayı yumuşatabilir.", "A patient stance may soften panic spending.", "Терпеливая поза может смягчить панические траты."),
            "personal": ("İçerideki sert hayvan, dokunulmayı bekliyor olabilir.", "The inner fierce animal may be waiting to be touched, not beaten.", "Внутренний ярый зверь может ждать прикосновения, не побоев."),
            "challenge": ("Güç, kendini küçümsemeye veya başkasını bastırmaya kayabilir.", "Strength may slide into self-belittling or pressing others down.", "Сила может стать самоумалением или давлением на других."),
            "guidance": ("Yumuşak ol; zayıf olma.", "Be gentle; do not become faint.", "Будь мягок; не становись слабым."),
            "future": ("Olası iklim: daha merhametli bir dayanıklılık.", "A possible climate: more merciful endurance.", "Возможный климат: более милостивая стойкость."),
        },
        ["major_15", "major_07", "wands_09"],
        ("Şeytan bağlanma, Savaş Arabası yön, Değnek Dokuzu son ateşi taşır.", "The Devil holds attachment; the Chariot heading; Nine of Wands last fire.", "Дьявол — привязанность; Колесница — курс; Девятка Жезлов — последний огонь."),
    ),
    M(9, ("Ermiş", "The Hermit", "Отшельник"),
        (["yalnızlık", "ışık", "arayış"], ["solitude", "lamp", "search"], ["одиночество", "свет", "поиск"]),
        (["kopuş", "kaçış", "soğukluk"], ["cutoff", "escape", "coldness"], ["отсечение", "бегство", "холод"]),
        {
            "symbolic": ("Tek bir lamba; kalabalığın dışında duran sual.", "A single lamp; a question standing outside the crowd.", "Один светильник; вопрос вне толпы."),
            "love": ("Mesafe bir ihtiyaç olabilir; yokluk ile yalnızlık aynı şey değildir.", "Distance may be needed; absence and solitude are not the same.", "Дистанция может быть нужна; отсутствие и одиночество — не одно."),
            "career": ("Derinleşme, uzmanlaşma veya geri çekilip bakmak mümkün görünür.", "Going deeper, specializing, or stepping back to look may be possible.", "Возможно углубление, специальность или шаг назад, чтобы увидеть."),
            "money": ("Sadeleşme, gösterişli harcamadan daha sakin durabilir.", "Simplifying may sit more calmly than showy spending.", "Упрощение может быть спокойнее показных трат."),
            "personal": ("Cevap dışarıda değil, eldeki küçük ışıkta aranabilir.", "The answer may be sought in the small light in hand, not outside.", "Ответ можно искать в малом свете в руке, не вовне."),
            "challenge": ("Yalnızlık, dünyayı reddetmeye dönüşebilir.", "Solitude may become a refusal of the world.", "Одиночество может стать отказом от мира."),
            "guidance": ("Işığı sönmeden yürü; kimseyi peşinden sürükleme.", "Walk before the lamp fails; do not drag anyone behind you.", "Иди, пока свет не погас; никого не тащи за собой."),
            "future": ("Olası iklim: daha içe dönük bir aralık.", "A possible climate: a more inward interval.", "Возможный климат: более внутренний промежуток."),
        },
        ["major_02", "major_18", "swords_04"],
        ("Başrahibe ve Ay iç oda; Kılıç Dördü dinlenme payıdır.", "Priestess and Moon are the inner room; Four of Swords a share of rest.", "Жрица и Луна — внутренняя комната; Четвёрка Мечей — доля покоя."),
    ),
    M(10, ("Kader Çarkı", "Wheel of Fortune", "Колесо Фортуны"),
        (["döngü", "değişim", "tesadüf"], ["cycle", "turn", "chance"], ["цикл", "поворот", "случай"]),
        (["direnç", "kurban rolü", "takıntı"], ["resistance", "victim role", "fixation"], ["сопротивление", "роль жертвы", "зацикленность"]),
        {
            "symbolic": ("Dönen bir düzen; elde tutulmayan bir ritim.", "A turning order; a rhythm that cannot be gripped.", "Вращающийся строй; ритм, который не удержать."),
            "love": ("İlişkide bir evre değişebilir; bu, sonsuz mutluluk veya yıkım iddiası değildir.", "A phase in a bond may turn; this is not a claim of endless joy or ruin.", "Фаза связи может повернуться; это не утверждение вечной радости или краха."),
            "career": ("Dış koşullar kayabilir; uyum, panikten daha sakin bir yanıt olabilir.", "Outer conditions may shift; adapting may be calmer than panic.", "Внешние условия могут сдвинуться; адаптация спокойнее паники."),
            "money": ("Gelgit olabilir; tek bir ana bütün anlamı yüklemek ağırdır.", "Ebb and flow may appear; loading one moment with all meaning is heavy.", "Могут быть приливы; вешать на один миг весь смысл — тяжело."),
            "personal": ("Kontrol edilemeyen bir dönüş, alçakgönüllülük isteyebilir.", "An ungoverned turn may ask for humility.", "Неуправляемый поворот может просить смирения."),
            "challenge": ("Döngü, kadercilik veya suçlama hikâyesine bağlanabilir.", "The cycle may be bound into fatalism or blame.", "Цикл может стать историей рока или вины."),
            "guidance": ("Çarka tutunma; ritmini fark et.", "Do not cling to the wheel; notice its rhythm.", "Не цепляйся за колесо; заметь его ритм."),
            "future": ("Olası iklim: koşulların yeniden dizilişi — yönü sen seçersin.", "A possible climate: conditions rearranging — you still choose heading.", "Возможный климат: перестановка условий — курс всё же выбираешь ты."),
        },
        ["major_13", "major_21", "wands_10"],
        ("Ölüm boşaltır, Dünya tamamlar, Değnek Onu yük izidir.", "Death clears; the World completes; Ten of Wands is the load.", "Смерть очищает; Мир завершает; Десятка Жезлов — ноша."),
    ),
]
