"""Swords and Pentacles — 28 cards."""

from oracly_tarot_minors_base import C

SWORDS = [
    C("swords", 1, ("keskinlik|fikir|hava", "edge|idea|air", "остриё|идея|воздух"),
      ("sert söz|dağınık zihin|kesmek için kesmek", "harsh word|scattered mind|cutting to cut", "жёсткое слово|рассеянный ум|резать ради резанья"),
      ("İlk keskinlik; henüz savaş değil.", "A first edge; not yet a war.", "Первое остриё; ещё не война."),
      ("Bağda net bir cümle gerekebilir.", "A clear sentence may be needed in a bond.", "В связи может быть нужна ясная фраза."),
      ("İş te yeni bir fikir belirebilir.", "A new idea at work may appear.", "На работе может явиться новая идея."),
      ("Keskin bir karar kaynakları da ayırabilir.", "A sharp decision may also divide means.", "Острое решение может разделить и средства."),
      ("İçeride duru bir düşünce uyanabilir.", "A clear thought may wake inside.", "Внутри может проснуться ясная мысль."),
      ("Keskinlik, yaralamaya kayabilir.", "Edge may slide into wounding.", "Остриё может стать ранением."),
      ("Net ol; keserek konuşma.", "Be clear; do not speak by cutting.", "Будь ясен; не говори режа."),
      ("Olası iklim: daha duru bir fikir.", "A possible climate: a clearer idea.", "Возможный климат: более ясная идея."),
      ["wands_01", "major_01", "swords_02"],
      ("Değnek Ası kıvılcım, Büyücü el, Kılıç İkilisi duruştur.", "Ace of Wands spark; Magician hand; Two of Swords stance.", "Туз Жезлов — искра; Маг — рука; Двойка Мечей — поза.")),
    C("swords", 2, ("körü körüne duruş|iki düşünce|kapalı göz", "stalemate|two thoughts|closed eyes", "тупик|две мысли|закрытые глаза"),
      ("karar kaçışı|inkâr|donma", "flight from decision|denial|freeze", "бегство от решения|отрицание|заморозка"),
      ("İki kılıç arasında duran zihin.", "A mind standing between two swords.", "Ум, стоящий между двумя мечами."),
      ("İlişkide bir durak, seçim korkusu olabilir.", "A pause in a bond may be fear of choosing.", "Пауза в связи может быть страхом выбора."),
      ("İş te iki görüş kilitlenebilir.", "Two views at work may lock.", "На работе два взгляда могут замкнуться."),
      ("Kararsızlık harcamayı da dondurabilir.", "Indecision may also freeze spending.", "Нерешительность может заморозить и траты."),
      ("İçeride görmemek için kapanan göz olabilir.", "Eyes closed in order not to see may live inside.", "Внутри могут жить глаза, закрытые чтобы не видеть."),
      ("Duruş, sonsuz ertelemeye kayabilir.", "The stance may slide into endless delay.", "Поза может стать бесконечной отсрочкой."),
      ("Gözünü aç; henüz vurmak zorunda değilsin.", "Open your eyes; you do not have to strike yet.", "Открой глаза; ещё не обязательно бить."),
      ("Olası iklim: seçimden önceki kilit.", "A possible climate: a lock before choosing.", "Возможный климат: замок до выбора."),
      ["major_06", "cups_02", "wands_02"],
      ("Aşıklar seçim, Kupa ve Değnek ikilileri bağ ve ufuktur.", "Lovers choice; Twos of Cups and Wands bond and horizon.", "Влюблённые — выбор; Двойки Кубков и Жезлов — связь и горизонт.")),
    C("swords", 3, ("kırık söz|acı netlik|kalp kenarı", "broken word|painful clarity|heart-edge", "сломанное слово|больная ясность|край сердца"),
      ("dramatik acı|suçlama|kapanmama", "dramatic pain|blame|unclosed", "драматическая боль|вина|незакрытость"),
      ("Keskin bir üzüntü; tiyatro değildir.", "A sharp sorrow; it is not theatre.", "Острая печаль; это не театр."),
      ("Bağda inciten bir gerçek konuşulabilir.", "A hurting truth may be spoken in a bond.", "В связи может быть сказана ранящая правда."),
      ("İş te hayal kırıklığı belirginleşebilir.", "Disappointment at work may sharpen.", "На работе может обостриться разочарование."),
      ("Bir kayıp hesabı açılabilir.", "An account of loss may open.", "Может открыться счёт потери."),
      ("İçeride kırık ve hâlâ duru bir yer olabilir.", "A place both broken and still clear may live inside.", "Внутри может жить место и сломанное, и всё ещё ясное."),
      ("Acı, kimlik olabilir.", "Pain may become identity.", "Боль может стать личностью."),
      ("Acıyı adlandır; sahne yapma.", "Name the pain; do not stage it.", "Назови боль; не ставь её на сцену."),
      ("Olası iklim: daha çıplak bir üzüntü.", "A possible climate: barer sorrow.", "Возможный климат: более голая печаль."),
      ["cups_05", "major_13", "swords_05"],
      ("Kupa Beşlisi yas, Ölüm kapanış, Kılıç Beşlisi çatışmadır.", "Five of Cups mourning; Death closing; Five of Swords clash.", "Пятёрка Кубков — траур; Смерть — закрытие; Пятёрка Мечей — спор.")),
    C("swords", 4, ("dinlenme|zihin molası|kın", "rest|mind pause|sheath", "отдых|пауза ума|ножны"),
      ("kaçış uyku|erteleme|uyuşma", "escape-sleep|delay|numbness", "сон-бегство|отсрочка|онемение"),
      ("Kının içindeki kılıç; savaş bitmiş gibi değil, ara.", "Sword in the sheath; not as if war ended — an interval.", "Меч в ножнах; не будто война кончилась — промежуток."),
      ("Bağda sessiz bir ara gerekebilir.", "A quiet interval may be needed in a bond.", "В связи может быть нужен тихий промежуток."),
      ("İş te durup düşünmek sakin duruştur.", "Stopping to think at work is a calm stance.", "На работе остановиться и подумать — спокойная поза."),
      ("Harcama molası bir nefes olabilir.", "A pause in spending may be a breath.", "Пауза в тратах может быть дыханием."),
      ("İçeride yorgun bir zihin yere yatmak isteyebilir.", "A tired mind may want to lie down inside.", "Внутри усталый ум может хотеть лечь."),
      ("Mola, hayattan çekilmeye kayabilir.", "The pause may slide into withdrawing from life.", "Пауза может стать уходом из жизни."),
      ("Kınına koy; kaybolma.", "Sheathe; do not disappear.", "Вложи в ножны; не исчезай."),
      ("Olası iklim: zihinsel bir kış uykusu değil, kısa bir kın.", "A possible climate: not mental hibernation — a brief sheath.", "Возможный климат: не спячка ума — краткие ножны."),
      ["major_09", "cups_04", "major_12"],
      ("Ermiş yalnızlık, Kupa Dördü durgunluk, Asılan Adam açıdır.", "Hermit solitude; Four of Cups stillness; Hanged Man angle.", "Отшельник — одиночество; Четвёрка Кубков — застой; Повешенный — ракурс.")),
    C("swords", 5, ("boş zafer|incitme|söz savaşı", "hollow win|hurting|war of words", "пустая победа|ранение|война слов"),
      ("aşağılık|intikam|yalnız kalma", "humiliation|revenge|being left", "унижение|месть|остаться одному"),
      ("Kazanılmış gibi duran bir kesik; neşe yoktur.", "A cut that looks like winning; there is no joy.", "Разрез, похожий на победу; радости нет."),
      ("Bağda incitici bir haklılık belirebilir.", "A hurting rightness may appear in a bond.", "В связи может явиться ранящая правота."),
      ("İş te rekabetin gölgesi görülebilir.", "The shadow of rivalry at work may be seen.", "На работе может быть видна тень соперничества."),
      ("Kazanç, ilişki maliyetine bağlanabilir.", "Gain may be bound to a relational cost.", "Прибыль может быть связана с ценой отношений."),
      ("İçeride 'ben kazandım' ve boşluk birlikte durabilir.", "'I won' and vacancy may stand together inside.", "Внутри вместе могут стоять «я выиграл» и пустота."),
      ("Zafer, yalnızlığa kayabilir.", "Winning may slide into aloneness.", "Победа может стать одиночеством."),
      ("Kılıcı indir; puan sayma.", "Lower the sword; do not keep score.", "Опусти меч; не веди счёт."),
      ("Olası iklim: sözlerin keskinleştiği bir ara.", "A possible climate: an interval where words sharpen.", "Возможный климат: промежуток, где слова острятся."),
      ["wands_05", "cups_05", "major_15"],
      ("Değnek ve Kupa Beşlisi sınav ve yas, Şeytan bağlanmadır.", "Fives of Wands and Cups trial and mourning; Devil attachment.", "Пятёрки Жезлов и Кубков — испытание и траур; Дьявол — привязанность.")),
    C("swords", 6, ("geçiş|sakin su üstü|yükü taşıma", "crossing|calm water surface|carrying the load", "переход|спокойная гладь|нести ношу"),
      ("kaçış|geçmişi götürme|varamama korkusu", "escape|carrying the past|fear of not arriving", "бегство|нести прошлое|страх не прибыть"),
      ("Suyun üstünde giden zihin; henüz liman değil.", "Mind traveling on water; not yet harbor.", "Ум, идущий по воде; ещё не гавань."),
      ("Bağda bir geçiş dönemi belirebilir.", "A crossing period may appear in a bond.", "В связи может явиться период перехода."),
      ("İş te yer veya rol değişimi konuşulabilir.", "A change of place or role at work may be spoken.", "На работе могут говорить о смене места или роли."),
      ("Kaynakları taşıyarak geçmek gerekebilir.", "Means may need to be carried across.", "Средства, возможно, нужно нести через переход."),
      ("İçeride yola çıkan yorgun bir duruluk olabilir.", "A tired clarity setting out may live inside.", "Внутри может жить усталая ясность, выходящая в путь."),
      ("Geçiş, kaçış olabilir.", "The crossing may be escape.", "Переход может быть бегством."),
      ("Taşı; bütün geçmişi tekneye yükleme.", "Carry; do not load the whole past into the boat.", "Неси; не грузи всё прошлое в лодку."),
      ("Olası iklim: daha sakin bir geçit.", "A possible climate: a calmer passage.", "Возможный климат: более спокойный проход."),
      ["wands_06", "major_07", "cups_08"],
      ("Değnek Altılısı geçiş, Savaş Arabası yön, Kupa Sekizlisi ayrılıştır.", "Six of Wands crossing; Chariot heading; Eight of Cups leaving.", "Шестёрка Жезлов — переход; Колесница — курс; Восьмёрка Кубков — уход.")),
    C("swords", 7, ("saklama|kayış|strateji", "hiding|slip|strategy", "укрытие|скольжение|стратегия"),
      ("hırsızlık hissi|güvensizlik|yalnız plan", "theft-feeling|mistrust|lone plan", "ощущение кражи|недоверие|одинокий план"),
      ("Görünmeden çekilen bir kılıç; yargı değil, iz.", "A sword drawn unseen; not a verdict — a trace.", "Меч, извлечённый невидимо; не приговор — след."),
      ("Bağda saklanan bir söz olabilir.", "A hidden word may sit in a bond.", "В связи может сидеть скрытое слово."),
      ("İş te dolaylı bir hareket fark edilebilir.", "An indirect move at work may be noticed.", "На работе может быть замечено косвенное движение."),
      ("Kaynakların sessizce kayması görülebilir.", "Means quietly slipping may be seen.", "Может быть видно тихое ускользание средств."),
      ("İçeride gizlenen bir strateji olabilir.", "A hidden strategy may live inside.", "Внутри может жить скрытая стратегия."),
      ("Kayış, kendine de yalan olabilir.", "The slip may also be a lie to oneself.", "Скольжение может быть и ложью себе."),
      ("Gizlediğini gör; hırsız ilan etme.", "See what is hidden; do not declare a thief.", "Увидь скрытое; не объявляй вора."),
      ("Olası iklim: daha dolaylı bir zihin.", "A possible climate: a more indirect mind.", "Возможный климат: более косвенный ум."),
      ["major_18", "cups_07", "pentacles_07"],
      ("Ay sis, Kupa Yedilisi hayal, Tılsım Yedilisi bekleyiştir.", "Moon mist; Seven of Cups dream; Seven of Pentacles waiting.", "Луна — туман; Семёрка Кубков — мечта; Семёрка Пентаклей — ожидание.")),
    C("swords", 8, ("sıkışma|kendi kılıcı|bağlı zihin", "tightness|one's own sword|bound mind", "теснота|свой меч|связанный ум"),
      ("kurban hikâyesi|hareketsizlik|korku ağı", "victim story|immobility|web of fear", "история жертвы|неподвижность|сеть страха"),
      ("Kendi düşüncesiyle sarılı zihin.", "A mind wrapped in its own thought.", "Ум, обмотанный собственной мыслью."),
      ("Bağda çıkışsızlık hissedilebilir; kapı yok değildir.", "No-exit may be felt in a bond; it does not mean there is no door.", "В связи может ощущаться безвыходность; это не значит, что нет двери."),
      ("İş te sıkışmış bir rol belirebilir.", "A stuck role at work may appear.", "На работе может явиться застрявшая роль."),
      ("Kaynak korkusu hareketi dondurabilir.", "Fear around means may freeze motion.", "Страх вокруг средств может заморозить движение."),
      ("İçeride kendi kurduğu bir ağ olabilir.", "A web one built oneself may live inside.", "Внутри может жить сеть, которую сплели сами."),
      ("Sıkışma, gerçek dış kısıttan ayrı durabilir.", "Tightness may sit apart from a real outer limit.", "Теснота может стоять отдельно от реального внешнего предела."),
      ("Bağı fark et; henüz kesmek zorunda değilsin.", "Notice the bind; you do not have to cut yet.", "Заметь связь; ещё не обязательно резать."),
      ("Olası iklim: zihinsel bir daralma.", "A possible climate: a mental narrowing.", "Возможный климат: умственное сужение."),
      ["major_15", "wands_08", "cups_08"],
      ("Şeytan bağ, Değnek Sekizlisi hız, Kupa Sekizlisi ayrılıştır.", "Devil bind; Eight of Wands speed; Eight of Cups leaving.", "Дьявол — связь; Восьмёрка Жезлов — скорость; Восьмёрка Кубков — уход.")),
    C("swords", 9, ("gece düşüncesi|kaygı|zihin yükü", "night thought|anxiety|mind load", "ночная мысль|тревога|ноша ума"),
      ("felaket hayali|uykusuzluk kimliği|suç", "catastrophe-dream|insomnia-identity|guilt", "мечта-катастрофа|личность бессонницы|вина"),
      ("Gece çoğalan kılıçlar; gündüz kadar gerçek olmayabilirler.", "Swords that multiply at night; they may be less real by day.", "Мечи, что множатся ночью; днём они могут быть менее реальны."),
      ("Bağda kaygı konuşmaları artabilir.", "Anxious talk may increase in a bond.", "В связи могут усилиться тревожные разговоры."),
      ("İş te gece zihni işi büyütebilir.", "The night-mind may enlarge work.", "Ночной ум может увеличить дело."),
      ("Para korkusu, gerçek hesaptan büyük durabilir.", "Money-fear may sit larger than the real account.", "Страх денег может быть больше реального счёта."),
      ("İçeride uyanık duran bir nöbetçi olabilir.", "A sentry that will not sleep may live inside.", "Внутри может жить часовой, который не спит."),
      ("Kaygı, kehanet gibi giyinebilir.", "Anxiety may dress as prophecy.", "Тревога может одеться пророчеством."),
      ("Düşünceyi say; hepsine inanma.", "Count the thoughts; do not believe them all.", "Сочти мысли; не верь всем."),
      ("Olası iklim: daha gürültülü bir gece zihni.", "A possible climate: a noisier night-mind.", "Возможный климат: более шумный ночной ум."),
      ["major_18", "wands_09", "cups_09"],
      ("Ay belirsizlik, Değnek Dokuzu nöbet, Kupa Dokuzu yeterliliktir.", "Moon unclearness; Nine of Wands watch; Nine of Cups enough.", "Луна — неясность; Девятка Жезлов — дозор; Девятка Кубков — довольно.")),
    C("swords", 10, ("bitmiş savaş|zihin sonu|yerde kılıç", "finished war|mind's end|sword on ground", "законченная война|конец ума|меч на земле"),
      ("felaket kimliği|kalkmama|her şey bitti hikâyesi", "disaster-identity|not rising|all-is-over story", "личность бедствия|не вставать|история «всё кончено»"),
      ("Zihinsel bir son; bedenin sonu değildir.", "A mental ending; not the end of a body.", "Умственный конец; не конец тела."),
      ("Bağda tükenmiş bir dil belirebilir.", "Exhausted language may appear in a bond.", "В связи может явиться исчерпанный язык."),
      ("Bir iş fikrinin sonu konuşulabilir.", "The end of a work idea may be spoken.", "Могут говорить о конце рабочей идеи."),
      ("Bir düzenin zihnen kapandığı hissedilebilir.", "An arrangement may feel mentally closed.", "Порядок может ощущаться умственно закрытым."),
      ("İçeride 'tamam' diyen yorgun bir yer olabilir.", "A tired place saying 'enough' may live inside.", "Внутри может жить усталое место, говорящее «всё»."),
      ("Son, sonsuz yenilgi hikâyesine bağlanabilir.", "The end may bind to a story of endless defeat.", "Конец может привязаться к истории вечного поражения."),
      ("Yerde yatmayı bitir; henüz dans etmek zorunda değilsin.", "Finish lying on the ground; you do not have to dance yet.", "Закончи лежать на земле; ещё не обязательно танцевать."),
      ("Olası iklim: bir zihin döngüsünün sonu.", "A possible climate: the end of a mind-cycle.", "Возможный климат: конец цикла ума."),
      ["major_13", "major_16", "wands_10"],
      ("Ölüm biçim sonu, Kule çatlak, Değnek Onu omuz yüküdür.", "Death end of form; Tower crack; Ten of Wands shoulder-load.", "Смерть — конец формы; Башня — трещина; Десятка Жезлов — ноша плеч.")),
    C("swords", 11, ("merak|keskin öğrenci|soru", "curiosity|sharp student|question", "любопытство|острый ученик|вопрос"),
      ("dedikodu|acele hüküm|dinlememe", "gossip|hasty verdict|not listening", "сплетня|поспешный приговор|неслушание"),
      ("Havanın habercisi; yargıç değil.", "Messenger of air; not a judge.", "Вестник воздуха; не судья."),
      ("Bağda soru sormak yumuşak bir kapı olabilir.", "Asking in a bond may be a gentle door.", "Спрашивать в связи может быть мягкой дверью."),
      ("İş te öğrenilecek bir dil belirebilir.", "A language to be learned at work may appear.", "На работе может явиться язык, которому учатся."),
      ("Bilgi, spekülasyondan ayrı durmalıdır.", "Information should sit apart from speculation.", "Сведение должно стоять отдельно от догадки."),
      ("İçeride keskin ve henüz olgun olmayan bir zihin olabilir.", "A sharp, not-yet-mature mind may live inside.", "Внутри может жить острый, ещё не зрелый ум."),
      ("Soru, yaralamaya kayabilir.", "The question may slide into wounding.", "Вопрос может стать ранением."),
      ("Sor; mahkeme kurma.", "Ask; do not assemble a court.", "Спроси; не собирай суд."),
      ("Olası iklim: daha keskin bir merak.", "A possible climate: sharper curiosity.", "Возможный климат: более острое любопытство."),
      ["major_01", "wands_11", "cups_11"],
      ("Büyücü zanaat, Değnek ve Kupa Habercileri ateş ve sudur.", "Magician craft; Pages of Wands and Cups fire and water.", "Маг — ремесло; Пажи Жезлов и Кубков — огонь и вода.")),
    C("swords", 12, ("hızlı zihin|söz atı|ileri kesiş", "fast mind|word-horse|forward cut", "быстрый ум|конь слова|разрез вперёд"),
      ("düşüncesiz hız|saldırı|dinlememe", "thoughtless speed|attack|not listening", "бессмысленная скорость|атака|неслушание"),
      ("Düşünceyle yola çıkan kılıç.", "A sword that takes thought on the road.", "Меч, берущий мысль в дорогу."),
      ("Bağda hızlı sözler belirebilir.", "Quick words may appear in a bond.", "В связи могут явиться быстрые слова."),
      ("İş te ani bir hamle mümkün görünür.", "A sudden move at work may be possible.", "На работе возможен внезапный ход."),
      ("Hızlı karar kaynakları da sarsabilir.", "A fast decision may also shake means.", "Быстрое решение может тряхнуть и средства."),
      ("İçeride duramayan bir argüman olabilir.", "An argument that cannot wait may live inside.", "Внутри может жить довод, который не ждёт."),
      ("Hız, başkasını ezmeye kayabilir.", "Speed may slide into crushing another.", "Скорость может начать давить другого."),
      ("Sür; rastgele kesme.", "Ride; do not cut at random.", "Скачи; не режь наугад."),
      ("Olası iklim: daha hızlı bir zihin.", "A possible climate: a quicker mind.", "Возможный климат: более быстрый ум."),
      ["wands_12", "major_07", "cups_12"],
      ("Değnek Şövalyesi ateş, Savaş Arabası yön, Kupa Şövalyesi gönül yoludur.", "Knight of Wands fire; Chariot heading; Knight of Cups heart-road.", "Рыцарь Жезлов — огонь; Колесница — курс; Рыцарь Кубков — дорога сердца.")),
    C("swords", 13, ("dürüst sınır|keskin şefkat|net söz", "honest boundary|sharp kindness|clear word", "честная граница|острая доброта|ясное слово"),
      ("soğuk yargı|mesafe silahı|acı dil", "cold verdict|distance-as-weapon|bitter tongue", "холодный приговор|дистанция-оружие|горький язык"),
      ("Gerçeği nazik tutan zihin.", "A mind that holds truth kindly.", "Ум, держащий правду мягко."),
      ("Bağda dürüst bir sınır konuşulabilir.", "An honest boundary may be spoken in a bond.", "В связи может быть сказана честная граница."),
      ("İş te net ve adil dil sakin durabilir.", "Clear and fair speech at work may sit calmly.", "На работе ясная и честная речь может сидеть спокойно."),
      ("Hesap, utandırmadan duru olabilir.", "An account may be clear without shaming.", "Счёт может быть ясен без стыда."),
      ("İçeride hem keskin hem koruyan bir yer olabilir.", "A place both sharp and protecting may live inside.", "Внутри может жить место и острое, и защищающее."),
      ("Netlik, soğumaya kayabilir.", "Clarity may slide into coldness.", "Ясность может стать холодом."),
      ("Doğru söyle; keserek söyleme.", "Speak truly; do not speak by cutting.", "Говори правду; не говори режа."),
      ("Olası iklim: daha dürüst bir dil.", "A possible climate: more honest speech.", "Возможный климат: более честная речь."),
      ["major_11", "cups_13", "swords_14"],
      ("Adalet ölçü, Kupa Kraliçesi şefkat, Kılıç Kralı zihin yönüdür.", "Justice measure; Queen of Cups compassion; King of Swords mind-heading.", "Справедливость — мера; Королева Кубков — сострадание; Король Мечей — курс ума.")),
    C("swords", 14, ("ilke|sakin yargı|zihin omurgası", "principle|calm judgement|mind-spine", "принцип|спокойное суждение|хребет ума"),
      ("katılık|kalpsiz kural|mesafe putu", "rigidity|heartless rule|idol of distance", "жёсткость|бессердечное правило|кумир дистанции"),
      ("İlkeyle duran kılıç.", "A sword that stands on principle.", "Меч, стоящий на принципе."),
      ("Bağda ilke ve netlik öne çıkabilir.", "Principle and clarity may come forward in a bond.", "В связи могут выйти принцип и ясность."),
      ("İş te adil bir karar duruşu belirebilir.", "A stance of fair decision at work may appear.", "На работе может явиться поза справедливого решения."),
      ("Kural, kaynağı da düzenleyebilir.", "A rule may also order means.", "Правило может упорядочить и средства."),
      ("İçeride soğuk değil, duru bir omurga istenebilir.", "A spine that is clear, not cold, may be wanted inside.", "Внутри может быть нужен хребет ясный, не холодный."),
      ("İlke, insanı ezmeye kayabilir.", "Principle may slide into crushing a person.", "Принцип может начать давить человека."),
      ("İlkeyi tut; kalbi dışarıda bırakma.", "Hold the principle; do not leave the heart outside.", "Держи принцип; не оставляй сердце вовне."),
      ("Olası iklim: daha ilkeli bir zihin.", "A possible climate: a more principled mind.", "Возможный климат: более принципиальный ум."),
      ["major_04", "major_11", "pentacles_14"],
      ("İmparator yapı, Adalet ölçü, Tılsım Kralı madde yönüdür.", "Emperor structure; Justice measure; King of Pentacles matter-heading.", "Император — строй; Справедливость — мера; Король Пентаклей — курс материи.")),
]

PENTACLES = [
    C("pentacles", 1, ("tohum|madde|el", "seed|matter|hand", "семя|материя|рука"),
      ("fırsat kaçırma korkusu|açgöz|erteleme", "fear of missed chance|greed|delay", "страх упущенного шанса|жадность|отсрочка"),
      ("İlk tohum; henüz bahçe değil.", "A first seed; not yet a garden.", "Первое семя; ещё не сад."),
      ("Bağda somut bir jest belirebilir.", "A concrete gesture may appear in a bond.", "В связи может явиться конкретный жест."),
      ("İş te somut bir başlangıç mümkün görünür.", "A concrete work beginning may be possible.", "Возможно конкретное начало дела."),
      ("Küçük bir kaynak kapısı aralanabilir.", "A small door of means may open a little.", "Может чуть открыться малая дверь средств."),
      ("İçeride elde tutulabilir bir değer uyanabilir.", "A value that can be held in the hand may wake inside.", "Внутри может проснуться ценность, которую можно держать в руке."),
      ("Tohum, hemen servet hikâyesine kayabilir.", "The seed may slide into an instant-fortune story.", "Семя может стать историей мгновенного богатства."),
      ("Ekle; henüz hasat sayma.", "Plant; do not count a harvest yet.", "Посади; ещё не считай урожай."),
      ("Olası iklim: maddi bir başlangıç.", "A possible climate: a material beginning.", "Возможный климат: материальное начало."),
      ["wands_01", "major_01", "pentacles_03"],
      ("Değnek Ası kıvılcım, Büyücü el, Tılsım Üçlüsü zanaattır.", "Ace of Wands spark; Magician hand; Three of Pentacles craft.", "Туз Жезлов — искра; Маг — рука; Тройка Пентаклей — ремесло.")),
    C("pentacles", 2, ("denge|jonglör|ritim", "balance|juggle|rhythm", "равновесие|жонглирование|ритм"),
      ("dağılma|erteleme|iki arada kalma", "scatter|delay|stuck between", "рассев|отсрочка|застревание между"),
      ("İki ağırlık arasında dans eden el.", "A hand dancing between two weights.", "Рука, танцующая между двумя тяжестями."),
      ("Bağda tempo ve pratik denge konuşulabilir.", "Tempo and practical balance may be spoken in a bond.", "В связи могут говорить о темпе и практической мере."),
      ("İş te birden fazla iş ritmi belirebilir.", "More than one work rhythm may appear.", "Может явиться больше одного рабочего ритма."),
      ("Gelir-gider dansı görünür olabilir.", "A dance of in-and-out means may be visible.", "Может быть виден танец прихода и расхода."),
      ("İçeride düşürmeden tutmaya çalışan bir yer olabilir.", "A place trying to hold without dropping may live inside.", "Внутри может жить место, которое старается держать, не роняя."),
      ("Denge, hiçbirini seçememeye kayabilir.", "Balance may slide into choosing none.", "Равновесие может стать неумением выбрать."),
      ("Ritmi tut; her topu parlatma.", "Keep the rhythm; do not polish every ball.", "Держи ритм; не полируй каждый шар."),
      ("Olası iklim: pratik bir denge aralığı.", "A possible climate: a practical interval of balance.", "Возможный климат: практический промежуток равновесия."),
      ["major_14", "wands_02", "cups_02"],
      ("Denge harman, Değnek ve Kupa ikilileri ufuk ve bağdır.", "Temperance blend; Twos of Wands and Cups horizon and bond.", "Умеренность — смесь; Двойки Жезлов и Кубков — горизонт и связь.")),
    C("pentacles", 3, ("zanaat|işbirliği|işlik", "craft|collaboration|workshop", "ремесло|сотрудничество|мастерская"),
      ("kıyas|yalnız deha|özensizlik", "comparison|lone genius|carelessness", "сравнение|одинокий гений|небрежность"),
      ("Birlikte örülen iş; alkış değil.", "Work woven together; not applause.", "Работа, сплетённая вместе; не аплодисменты."),
      ("Bağda ortak bir iş belirebilir.", "A shared task may appear in a bond.", "В связи может явиться общее дело."),
      ("İş te zanaat ve geri bildirim öne çıkabilir.", "Craft and feedback at work may come forward.", "На работе могут выйти ремесло и обратная связь."),
      ("Emeğin değeri konuşulabilir.", "The worth of labor may be spoken.", "Могут говорить о цене труда."),
      ("İçeride 'biz yaptık' cümlesi ısınabilir.", "The sentence 'we made this' may warm inside.", "Внутри может согреться фраза «мы это сделали»."),
      ("Zanaat, kıyasa kayabilir.", "Craft may slide into comparison.", "Ремесло может стать сравнением."),
      ("İşi güzel yap; vitrine çevirme.", "Make the work well; do not turn it into a shop window.", "Сделай работу хорошо; не превращай её в витрину."),
      ("Olası iklim: daha zanaatkâr bir ara.", "A possible climate: a more craftsmanlike interval.", "Возможный климат: более ремесленный промежуток."),
      ["wands_03", "major_05", "cups_03"],
      ("Değnek Üçlüsü ufuk, Aziz aidiyet, Kupa Üçlüsü masadır.", "Three of Wands horizon; Hierophant belonging; Three of Cups table.", "Тройка Жезлов — горизонт; Иерофант — принадлежность; Тройка Кубков — стол.")),
    C("pentacles", 4, ("tutma|eşik bekçisi|kapalı el", "holding|threshold guard|closed hand", "удержание|страж порога|закрытая рука"),
      ("cimrilik|korku kasası|paylaşamama", "miserliness|fear-vault|cannot share", "скупость|сейф страха|неумение делиться"),
      ("Sıkı tutulan tohum; güvenlik ve sıkışma aynı kapıda durur.", "A tightly held seed; safety and tightness stand at the same door.", "Туг держанное семя; безопасность и теснота стоят у одной двери."),
      ("Bağda kontrol veya tutma belirebilir.", "Control or holding may appear in a bond.", "В связи может явиться контроль или удержание."),
      ("İş te kaynak koruma öne çıkabilir.", "Protecting resources at work may come forward.", "На работе может выйти защита ресурсов."),
      ("Birikim sakin de boğucu da durabilir.", "Saving may sit calm or suffocating.", "Накопление может сидеть спокойно или удушающе."),
      ("İçeride kaybetme korkusu elini kapatabilir.", "Fear of losing may close the hand inside.", "Страх потери может закрыть руку внутри."),
      ("Tutma, hayatı durdurmaya kayabilir.", "Holding may slide into stopping life.", "Удержание может остановить жизнь."),
      ("Koruma; kilitleme.", "Protect; do not lock.", "Храни; не запирай."),
      ("Olası iklim: daha tutucu bir güvenlik.", "A possible climate: more holding safety.", "Возможный климат: более удерживающая безопасность."),
      ["major_15", "wands_04", "cups_04"],
      ("Şeytan bağ, Değnek Dördü mola, Kupa Dördü durgunluktur.", "Devil bind; Four of Wands pause; Four of Cups stillness.", "Дьявол — связь; Четвёрка Жезлов — пауза; Четвёрка Кубков — застой.")),
    C("pentacles", 5, ("yoksunluk|eşik dışı|soğuk taş", "lack|outside the threshold|cold stone", "нехватка|вне порога|холодный камень"),
      ("utanç|yardım reddi|yalnızlık zırhı", "shame|refusing help|armor of aloneness", "стыд|отказ от помощи|броня одиночества"),
      ("Kapı dışındaki madde; değer yok olmuş değildir.", "Matter outside the door; worth is not gone.", "Материя за дверью; ценность не исчезла."),
      ("Bağda yoksunluk veya dışarıda kalma hissedilebilir.", "Lack or being left outside may be felt in a bond.", "В связи может ощущаться нехватка или остаться вовне."),
      ("İş te güvencesizlik belirebilir.", "Insecurity at work may appear.", "На работе может явиться незащищённость."),
      ("Maddi daralma görünür olabilir.", "A material narrowing may be visible.", "Может быть видно материальное сужение."),
      ("İçeride utanan bir yoksulluk hissi olabilir.", "A ashamed sense of poverty may live inside.", "Внутри может жить стыдящееся чувство бедности."),
      ("Yoksunluk, kimliğe kayabilir.", "Lack may slide into identity.", "Нехватка может стать личностью."),
      ("Kapıyı gör; gururla donma.", "See the door; do not freeze in pride.", "Увидь дверь; не замёрзни в гордости."),
      ("Olası iklim: daha çıplak bir ihtiyaç.", "A possible climate: a barer need.", "Возможный климат: более голая нужда."),
      ["cups_05", "major_16", "swords_05"],
      ("Kupa Beşlisi yas, Kule çatlak, Kılıç Beşlisi boş zaferdir.", "Five of Cups mourning; Tower crack; Five of Swords hollow win.", "Пятёрка Кубков — траур; Башня — трещина; Пятёрка Мечей — пустая победа.")),
    C("pentacles", 6, ("pay|veriş|terazi", "share|giving|scales", "доля|даяние|весы"),
      ("üstten bakış|borçlandırma|dengesiz cömertlik", "looking down|indebting|uneven generosity", "взгляд сверху|одалживание виной|неровная щедрость"),
      ("Verilen ve alınan madde; merhamet vitrini değil.", "Matter given and received; not a display of mercy.", "Материя данная и принятая; не витрина милости."),
      ("Bağda alma-verme ritmi konuşulabilir.", "A rhythm of giving and receiving may be spoken in a bond.", "В связи могут говорить о ритме давать и принимать."),
      ("İş te adil pay gündeme gelebilir.", "A fair share at work may come forward.", "На работе может выйти справедливая доля."),
      ("Yardım ve borç aynı şey değildir.", "Help and debt are not the same.", "Помощь и долг — не одно."),
      ("İçeride hem veren hem alan bir el olabilir.", "A hand both giving and receiving may live inside.", "Внутри может жить рука и дающая, и принимающая."),
      ("Pay, güç oyununa kayabilir.", "Share may slide into a power game.", "Доля может стать игрой силы."),
      ("Ver; küçük düşürme.", "Give; do not diminish.", "Дай; не унижай."),
      ("Olası iklim: daha ölçülü bir paylaşım.", "A possible climate: more measured sharing.", "Возможный климат: более мерное разделение."),
      ["major_11", "cups_06", "wands_06"],
      ("Adalet ölçü, Kupa Altılısı hatıra, Değnek Altılısı geçiştir.", "Justice measure; Six of Cups memory; Six of Wands crossing.", "Справедливость — мера; Шестёрка Кубков — память; Шестёрка Жезлов — переход.")),
    C("pentacles", 7, ("bekleyiş|ekim|sabır", "waiting|sowing|patience", "ожидание|посев|терпение"),
      ("sabırsızlık|emeği küçümseme|erken hasat", "impatience|scorning labor|early harvest", "нетерпение|пренебрежение трудом|ранний урожай"),
      ("Henüz olgunlaşmamış bahçe.", "A garden not yet ripe.", "Сад, ещё не зрелый."),
      ("Bağda emek ve zaman konuşulabilir.", "Labor and time may be spoken in a bond.", "В связи могут говорить о труде и времени."),
      ("İş te sonuç beklemek yorucu olabilir.", "Waiting for a work result may tire.", "На работе ожидание результата может утомить."),
      ("Yatırım henüz meyve vermemiş görünebilir.", "An investment may look unripe.", "Вложение может казаться незрелым."),
      ("İçeride sabır isteyen bir çiftçi olabilir.", "A farmer asking for patience may live inside.", "Внутри может жить земледелец, просящий терпения."),
      ("Bekleyiş, pişmanlığa kayabilir.", "Waiting may slide into regret.", "Ожидание может стать сожалением."),
      ("Bahçeyi izle; sökme.", "Watch the garden; do not pull it up.", "Смотри сад; не вырывай."),
      ("Olası iklim: daha sabırlı bir emek.", "A possible climate: more patient labor.", "Возможный климат: более терпеливый труд."),
      ["major_14", "wands_07", "swords_07"],
      ("Denge tempo, Değnek Yedilisi duruş, Kılıç Yedilisi kayıştır.", "Temperance pacing; Seven of Wands stance; Seven of Swords slip.", "Умеренность — темп; Семёрка Жезлов — стойка; Семёрка Мечей — скольжение.")),
    C("pentacles", 8, ("ustalık|tekrar|işlik disiplini", "mastery|repetition|workshop discipline", "мастерство|повторение|дисциплина мастерской"),
      ("mekaniklik|tükenme|anlamsız tekrar", "mechanics|depletion|empty repetition", "механика|истощение|пустое повторение"),
      ("Tekrarlanan el; sanatın sessiz hali.", "The repeating hand; the quiet form of art.", "Повторяющаяся рука; тихий вид искусства."),
      ("Bağda emekle kurulan güven belirebilir.", "Trust built by labor may appear in a bond.", "В связи может явиться доверие, построенное трудом."),
      ("İş te ustalık yolu öne çıkabilir.", "A path of mastery at work may come forward.", "На работе может выйти путь мастерства."),
      ("Düzenli emek, spekülasyondan ayrı durur.", "Regular labor sits apart from speculation.", "Регулярный труд стоит отдельно от догадки."),
      ("İçeride çalışan sessiz bir zanaatkâr olabilir.", "A quiet craftsperson at work may live inside.", "Внутри может жить тихий ремесленник за работой."),
      ("Disiplin, hayatı işe indirgeyebilir.", "Discipline may reduce life to work.", "Дисциплина может свести жизнь к работе."),
      ("Tekrar et; kendini yok etme.", "Repeat; do not erase yourself.", "Повторяй; не стирай себя."),
      ("Olası iklim: daha ustaca bir emek.", "A possible climate: more masterful labor.", "Возможный климат: более мастерский труд."),
      ["major_01", "wands_08", "pentacles_03"],
      ("Büyücü el, Değnek Sekizlisi hız, Tılsım Üçlüsü işliktir.", "Magician hand; Eight of Wands speed; Three of Pentacles workshop.", "Маг — рука; Восьмёрка Жезлов — скорость; Тройка Пентаклей — мастерская.")),
    C("pentacles", 9, ("yeterlilik|bahçe|kendi emeği", "enough-ness|garden|one's own labor", "достаточность|сад|свой труд"),
      ("yalnız refah|gösteriş|kapalı bahçe", "lone plenty|display|closed garden", "одинокое изобилие|показ|закрытый сад"),
      ("Kendi emeğinin bahçesi; vitrin değil.", "The garden of one's labor; not a shop window.", "Сад своего труда; не витрина."),
      ("Bağda bağımsız bir olgunluk belirebilir.", "An independent maturity may appear in a bond.", "В связи может явиться независимая зрелость."),
      ("İş te kişisel yeterlilik hissedilebilir.", "Personal enough-ness at work may be felt.", "На работе может ощущаться личная достаточность."),
      ("Kazancın sakin hali mümkün görünür.", "The calm form of earning may be possible.", "Возможен спокойный вид заработка."),
      ("İçeride 'ben yaptım' diyen sakin bir gurur olabilir.", "A calm pride saying 'I made this' may live inside.", "Внутри может жить спокойная гордость «я это сделал»."),
      ("Bahçe, başkasını dışarıda bırakmaya kayabilir.", "The garden may slide into leaving others out.", "Сад может начать оставлять других вовне."),
      ("Bahçede dur; kapıyı kilitleme.", "Stand in the garden; do not lock the gate.", "Стой в саду; не запирай калитку."),
      ("Olası iklim: daha kendi emeğine yaslanan bir ara.", "A possible climate: an interval leaning on one's own labor.", "Возможный климат: промежуток с опорой на свой труд."),
      ["cups_09", "major_17", "wands_09"],
      ("Kupa Dokuzu iç doyum, Yıldız sakin ışık, Değnek Dokuzu nöbettir.", "Nine of Cups inner enough; Star quiet light; Nine of Wands watch.", "Девятка Кубков — внутренняя достаточность; Звезда — тихий свет; Девятка Жезлов — дозор.")),
    C("pentacles", 10, ("soy|kalıcı masa|kök varlık", "lineage|lasting table|rooted means", "род|долгий стол|укоренённые средства"),
      ("miras baskısı|vitrin aile|kapanmayan hesap", "heritage pressure|display family|unclosed account", "давление наследия|витринная семья|незакрытый счёт"),
      ("Zamanın içindeki madde; bir ömürlük vitrin değil.", "Matter inside time; not a lifelong shop window.", "Материя внутри времени; не пожизненная витрина."),
      ("Bağda kök ve gelecek kuşak konuşulabilir.", "Roots and a coming generation may be spoken in a bond.", "В связи могут говорить о корнях и грядущем поколении."),
      ("İş te kalıcı bir yapı belirebilir.", "A lasting structure at work may appear.", "На работе может явиться долгий строй."),
      ("Kalıcı varlık, gösterişten ayrı durur.", "Lasting means sit apart from display.", "Долгие средства стоят отдельно от показа."),
      ("İçeride bir soya ait olma ısınabilir.", "Belonging to a lineage may warm inside.", "Внутри может согреться принадлежность к роду."),
      ("Soy, kişiyi ezmeye kayabilir.", "Lineage may slide into crushing the person.", "Род может начать давить человека."),
      ("Kökünü gör; tapınağa çevirme.", "See your root; do not turn it into a temple.", "Увидь корень; не превращай его в храм."),
      ("Olası iklim: daha köklü bir maddi duruş.", "A possible climate: a more rooted material stance.", "Возможный климат: более укоренённая материальная поза."),
      ["cups_10", "major_21", "wands_10"],
      ("Kupa Onu masa, Dünya tamamlanma, Değnek Onu yük izidir.", "Ten of Cups table; World completion; Ten of Wands load.", "Десятка Кубков — стол; Мир — завершение; Десятка Жезлов — ноша.")),
    C("pentacles", 11, ("öğrenci el|pratik merak|tohum haberi", "student hand|practical curiosity|seed-news", "рука ученика|практическое любопытство|весть семени"),
      ("savurgan çırak|öğrenmeme|acele ustalık", "wasteful apprentice|not learning|hasty mastery", "расточительный ученик|не учиться|поспешное мастерство"),
      ("Maddenin habercisi; tüccar değil.", "Messenger of matter; not a merchant.", "Вестник материи; не купец."),
      ("Bağda pratik bir öğrenme belirebilir.", "Practical learning may appear in a bond.", "В связи может явиться практическое учение."),
      ("İş te çıraklık kapısı aralanabilir.", "A door of apprenticeship at work may open a little.", "На работе может чуть открыться дверь ученичества."),
      ("Küçük bir maddi ders gelebilir.", "A small material lesson may come.", "Может прийти малый материальный урок."),
      ("İçeride elini işe sürmek isteyen bir yer olabilir.", "A place wanting to put the hand to work may live inside.", "Внутри может жить место, желающее приложить руку к делу."),
      ("Öğrenci, her şeyi spekülasyona kaydırabilir.", "The student may slide everything into speculation.", "Ученик может всё сдвинуть в догадку."),
      ("Elle öğren; zengin numarası yapma.", "Learn by hand; do not perform wealth.", "Учись рукой; не играй богатство."),
      ("Olası iklim: daha pratik bir merak.", "A possible climate: more practical curiosity.", "Возможный климат: более практическое любопытство."),
      ["wands_11", "cups_11", "swords_11"],
      ("Üç Haberci ateş, su ve havadır; bu el topraktadır.", "The three Pages are fire, water, air; this hand is in earth.", "Три Пажа — огонь, вода, воздух; эта рука в земле.")),
    C("pentacles", 12, ("yavaş yol|sürülmüş tarla|sebat", "slow road|ploughed field|steadfastness", "медленная дорога|вспаханное поле|стойкость"),
      ("inat|hareketsizlik|fırsat körlüğü", "stubbornness|immobility|blind to opening", "упрямство|неподвижность|слепота к отверстию"),
      ("Tarla temposunda giden madde.", "Matter traveling at field-tempo.", "Материя, идущая темпом поля."),
      ("Bağda yavaş ve sadık bir ritim belirebilir.", "A slow faithful rhythm may appear in a bond.", "В связи может явиться медленный верный ритм."),
      ("İş te sebat, hızdan daha sakin durabilir.", "Steadfastness at work may sit calmer than speed.", "На работе стойкость может сидеть спокойнее скорости."),
      ("Yavaş birikim mümkün görünür.", "Slow accumulation may be possible.", "Возможно медленное накопление."),
      ("İçeride acele etmeyen bir öküz olabilir.", "An ox that does not hurry may live inside.", "Внутри может жить вол, который не спешит."),
      ("Sebat, donmaya kayabilir.", "Steadfastness may slide into freeze.", "Стойкость может стать заморозкой."),
      ("Sür; yarış atı olma.", "Plough; do not become a racehorse.", "Паши; не становись скакуном."),
      ("Olası iklim: daha yavaş bir madde yolu.", "A possible climate: a slower road of matter.", "Возможный климат: более медленная дорога материи."),
      ["major_14", "wands_12", "cups_12"],
      ("Denge tempo, Değnek ve Kupa Şövalyeleri ateş ve su yoludur.", "Temperance pacing; Knights of Wands and Cups fire- and water-roads.", "Умеренность — темп; Рыцари Жезлов и Кубков — дороги огня и воды.")),
    C("pentacles", 13, ("bereketli ev|pratik şefkat|bahçe hanımı", "fertile house|practical care|garden host", "плодородный дом|практическая забота|хозяйка сада"),
      ("kontrol ev|cimrilik|gösteriş bakımı", "control-house|miserliness|display care", "дом-контроль|скупость|показная забота"),
      ("Evi madden tutan olgun el.", "A mature hand that holds a house in matter.", "Зрелая рука, держащая дом в материи."),
      ("Bağda pratik bakım belirebilir.", "Practical care may appear in a bond.", "В связи может явиться практическая забота."),
      ("İş te kaynak yönetimi sakin durabilir.", "Resource stewardship at work may sit calmly.", "На работе управление ресурсами может сидеть спокойно."),
      ("Ev ekonomisi konuşulabilir.", "A household economy may be spoken.", "Могут говорить о домашнем хозяйстве."),
      ("İçeride hem cömert hem ölçülü bir ev sahibi olabilir.", "A host both generous and measured may live inside.", "Внутри может жить хозяин и щедрый, и мерный."),
      ("Bakım, kontrol evine kayabilir.", "Care may slide into a house of control.", "Забота может стать домом контроля."),
      ("Evi tut; kilitleme.", "Hold the house; do not lock it.", "Держи дом; не запирай."),
      ("Olası iklim: daha bereketli bir pratik.", "A possible climate: a more fertile practice.", "Возможный климат: более плодородная практика."),
      ["major_03", "cups_13", "pentacles_14"],
      ("İmparatoriçe bakım, Kupa Kraliçesi deniz, Tılsım Kralı madde yönüdür.", "Empress care; Queen of Cups sea; King of Pentacles matter-heading.", "Императрица — забота; Королева Кубков — море; Король Пентаклей — курс материи.")),
    C("pentacles", 14, ("köklü varlık|sorumlu madde|bahçe kralı", "rooted means|responsible matter|garden king", "укоренённые средства|ответственная материя|король сада"),
      ("statü putu|katılık|cömert olmayan zenginlik", "idol of status|rigidity|ungenerous wealth", "кумир статуса|жёсткость|нещедрое богатство"),
      ("Maddeyi sorumlu tutan duruş.", "A stance that holds matter responsibly.", "Поза, ответственно держащая материю."),
      ("Bağda güvenlik ve olgunluk öne çıkabilir.", "Safety and maturity may come forward in a bond.", "В связи могут выйти безопасность и зрелость."),
      ("İş te kalıcı sorumluluk konuşulabilir.", "Lasting responsibility at work may be spoken.", "На работе могут говорить о долгой ответственности."),
      ("Varlık, vitrin olmadan durabilir.", "Means may stand without a shop window.", "Средства могут стоять без витрины."),
      ("İçeride hem cömert hem sağlam bir yetişkin olabilir.", "An adult both generous and solid may live inside.", "Внутри может жить взрослый и щедрый, и крепкий."),
      ("Varlık, insanı ezmeye kayabilir.", "Means may slide into crushing a person.", "Средства могут начать давить человека."),
      ("Kökle; tahtı putlaştırma.", "Take root; do not worship the throne.", "Укоренись; не делай трон кумиром."),
      ("Olası iklim: daha sorumlu bir madde.", "A possible climate: more responsible matter.", "Возможный климат: более ответственная материя."),
      ["major_04", "wands_14", "cups_14"],
      ("İмparator yapı, Değnek ve Kupa Kralları ateş ve su yönüdür.", "Emperor structure; Kings of Wands and Cups fire and water heading.", "Император — строй; Короли Жезлов и Кубков — курс огня и воды.")),
]
