/**
 * Dream Phase 3 lexicon — folded TR/EN/RU phrases (lowercase, ı→i, ё→е).
 * Mirrors `lib/features/dream/safety/dream_safety_lexicon.dart` and
 * `dream_output_lexicon.dart` verbatim; parity is proven by the shared
 * corpus in `tests/fixtures/dream_safety/`.
 */
const r = String.raw;

export const INPUT = {
  /** Present/future first-person intent — never excused by dream framing. */
  crisis: [
    r`kendimi (?:öldürmek|öldürmeyi|asmak|asmayi) (?:istiyorum|düşünüyorum|planliyorum)`,
    r`kendime zarar (?:vermek|vermeyi) (?:istiyorum|düşünüyorum|planliyorum)`,
    r`intihar (?:etmek|etmeyi) (?:istiyorum|düşünüyorum|planliyorum)`,
    r`(?:canima kiymak|hayatima son vermek) (?:istiyorum|düşünüyorum)`,
    r`(?:kendimi öldüreceğim|kendime zarar vereceğim|intihar edeceğim|canima kiyacağim|hayatima son vereceğim)`,
    r`(?:kendimi öldürmem|kendime zarar vermem|intihar etmem) (?:gerek|lazim)`,
    r`yaşamak istemiyorum`,
    r`ölmek istiyorum`,
    r`intihar düşünce(?:lerim|m) var`,
    r`i (?:really |just )?want to (?:kill myself|die|end my life|end it all|hurt myself|harm myself|cut myself)`,
    r`(?:i'm|i am|im) (?:going|planning) (?:to|on) (?:kill|killing|hurt|hurting|harm|harming|cut|cutting|end|ending) (?:myself|my life)`,
    r`i(?: will|'ll) (?:kill|hurt|harm|cut) myself`,
    r`i (?:have to|need to|must|should) (?:kill|hurt|harm|cut) myself`,
    r`(?:i'm|i am|im|i feel) suicidal`,
    r`(?:i'm|i am|i keep|i've been|i have been) thinking (?:about|of) (?:suicide|killing myself|ending my life|hurting myself|harming myself)`,
    r`i (?:don't|dont|do not) want to (?:live|be alive) anymore`,
    r`хочу (?:покончить с собой|умереть|убить себя|причинить себе вред|навредить себе|порезать себя)`,
    r`(?:покончу с собой|убью себя|причиню себе вред|наврежу себе)`,
    r`(?:планирую|собираюсь) (?:покончить с собой|убить себя|причинить себе вред|навредить себе)`,
    r`не хочу (?:больше )?жить`,
    r`(?:думаю|мысли) о (?:самоубийстве|суициде)`,
    r`(?:надо|нужно|должен|должна) (?:покончить с собой|убить себя|причинить себе вред)`,
  ],
  acute: [
    r`(?:kendimi )?güvende (?:hissetmiyorum|değilim)`,
    r`kontrol(?:ümü|ü) kaybediyorum`,
    r`kendimi (?:kontrol edemiyorum|koruyamiyorum|güvende tutamiyorum)`,
    r`tehlikedeyim`,
    r`(?:acil|hemen) yardima ihtiyacim var`,
    r`(?:i'm|i am|im) in (?:immediate |real )?danger`,
    r`i (?:can't|cant|cannot) keep myself safe`,
    r`i (?:don't|dont|do not) feel safe`,
    r`(?:i'm|i am|im) losing control`,
    r`i need (?:emergency|urgent|immediate) help`,
    r`i need help right now`,
    r`я (?:сейчас )?в опасности`,
    r`не чувствую себя в безопасности`,
    r`я теряю контроль`,
    r`не могу (?:себя контролировать|себя обезопасить|обезопасить себя)`,
    r`мне (?:срочно нужна|нужна срочная|нужна экстренная) помощь`,
  ],
  abuse: [
    r`cinsel (?:saldiri|istismar|taciz)`, r`tecavüz`, r`taciz`, r`istismar`,
    r`ensest`, r`sexual(?:ly)? (?:assault|abuse)`, r`raped?(?!\p{L})`,
    r`molest`, r`abused?(?!\p{L})`, r`incest`, r`изнасил`, r`насили`,
    r`домогател`, r`растлен`,
  ],
  reality: [
    r`gerçekten`, r`gerçek hayatta`, r`gerçekte(?!\p{L})`, r`başima gel`,
    r`bana yapil`, r`çocukken`, r`çocukluğumda`, r`yillar önce`,
    r`geçmişte`, r`really happened`, r`actually happened`, r`in real life`,
    r`as a (?:child|kid)`, r`when i was (?:a child|a kid|young|little)`,
    r`happened to me`, r`i went through`, r`years ago`, r`на самом деле`,
    r`в реальной жизни`, r`в детстве`, r`со мной (?:было|случилось|произошло)`,
    r`было со мной`, r`я пережил`, r`много лет назад`,
  ],
  proof: [
    r`kanitliyor`, r`kanitladi`, r`kaniti(?:dir)?(?!\p{L})`, r`ispatliyor`,
    r`ispatladi`, r`doğruluyor`, r`doğruladi`, r`teyit ediyor`,
    r`prove[sd]?(?!\p{L})`, r`proof`, r`confirm(?:s|ed)?(?!\p{L})`,
    r`evidence that`, r`доказыва`, r`доказал`, r`доказательств`,
    r`подтвержда`, r`подтвердил`,
  ],
  agents: [
    r`devlet`, r`polis`, r`istihbarat`, r`cin(?:ler|lerin|leri|in|i)?(?!\p{L})`,
    r`şeytan`, r`ruh(?:lar|larin|un)?(?!\p{L})`, r`uzayli`,
    r`büyü(?:cü|yle|nün)?(?!\p{L})`,
    r`beni (?:gerçekten |gizlice )?(?:izl|takip|gözetl|dinl)`,
    r`gizli güç`, r`sesler`, r`government`, r`police`, r`fbi`, r`cia(?!\p{L})`,
    r`spirits?(?!\p{L})`, r`d?jinn`, r`demons?(?!\p{L})`, r`aliens?(?!\p{L})`,
    r`ghosts?(?!\p{L})`, r`(?:watching|following|spying on|monitoring|tracking) me`,
    r`being (?:watched|followed|monitored|tracked)`, r`voices`, r`hidden forces?`,
    r`следят`, r`следит`, r`слежк`, r`правительств`, r`государств`, r`полици`,
    r`спецслужб`, r`дух(?:и|ов|ам|а)?(?!\p{L})`, r`джинн`, r`демон`,
    r`бес(?:ы|ов)?(?!\p{L})`, r`инопланет`, r`пришельц`, r`голоса`,
  ],
  voices: [
    r`sesler (?:bana )?(?:emir veriyor|ne yapacağimi söylüyor|konuşuyor)`,
    r`uyanikken (?:de )?sesler`, r`sesler duyuyorum`,
    r`voices (?:are )?(?:telling|tell|command|commanding|order|ordering) me`,
    r`i (?:hear|keep hearing) voices`,
    r`голоса (?:приказывают|говорят мне|велят)`, r`слышу голоса`,
  ],
  diagnosisTerms: [
    r`şizofren`, r`bipolar`, r`psikoz`, r`psikotik`, r`tssb`, r`ptsd`,
    r`travma sonrasi stres`, r`depresyon`, r`akil hastasi`, r`ruh hastasi`,
    r`otizm`, r`dehb`, r`adhd`, r`kanser`, r`demans`, r`okb(?!\p{L})`,
    r`obsesif`, r`kişilik bozukluğu`, r`anksiyete bozukluğu`,
    r`panik bozukluğu`, r`schizophreni`, r`psychosis`, r`psychotic`,
    r`post-?traumatic`, r`depress(?:ion|ed)`, r`mentally ill`,
    r`mental illness`, r`autis`, r`cancer`, r`dementia`, r`ocd(?!\p{L})`,
    r`personality disorder`, r`anxiety disorder`, r`panic disorder`,
    r`шизофрени`, r`биполяр`, r`психоз`, r`психотич`, r`птср`,
    r`посттравматическ`, r`депресси`, r`психически бол`, r`аутизм`, r`сдвг`,
    r`рак(?:а|ом|у)?(?!\p{L})`, r`деменци`, r`окр(?!\p{L})`,
  ],
  diagnosisLinks: [
    r`m[iuü](?:yim|yum|yüm|sun|sin|dur|dir)?(?!\p{L})`, r`gösteriyor`,
    r`kanitl`, r`belirti`, r`işaret`, r`anlamina`,
    r`anlayabilir`, r`teşhis`, r`do i have`, r`am i(?!\p{L})`,
    r`(?:proves?|shows?|means?|indicates?|suggests?) (?:that )?i(?:'m| am| have)?(?!\p{L})`,
    r`diagnos`, r`sign (?:of|that)`, r`symptom`, r`ли я`,
    r`значит`, r`означает`, r`доказыва`, r`признак`, r`симптом`, r`диагноз`,
  ],
  dream: [
    r`rüya(?:m|miz|si|sin)?da(?:ki)?(?!\p{L})`, r`düşümde`,
    r`kabus(?:um)?(?:da|ta)(?:ki)?(?!\p{L})`,
    r`in (?:my|the|this|that|a) (?:dream|nightmare)`,
    r`i (?:dreamt|dreamed|dream)(?!\p{L})`, r`i had a (?:dream|nightmare)`,
    r`i was dreaming`, r`во сне`, r`(?:снилось|приснилось|приснился|приснилась)`,
    r`в (?:моем |этом )?(?:сне|кошмаре)`,
  ],
  waking: [
    r`şimdi`, r`şu an(?:da)?(?!\p{L})`, r`uyandim`, r`uyandiğimda`,
    r`uyaninca`, r`uyandiktan`, r`uyanikken`, r`gerçek hayatta`,
    r`gerçekte(?!\p{L})`, r`bugün`, r`artik`, r`now(?!\p{L})`, r`currently`,
    r`today`, r`i woke`, r`woke up`, r`after waking`, r`awake`,
    r`in real life`, r`сейчас`, r`теперь`, r`сегодня`, r`проснул`, r`наяву`,
    r`в реальной жизни`, r`на самом деле`,
  ],
  memory: [
    r`intihar`, r`kendime zarar`, r`kendimi öldür`, r`kendini öldür`,
    r`self-harm`, r`suicid`, r`kill (?:myself|yourself)`, r`самоубий`,
    r`суицид`, r`покончить с собой`, r`şizofren`, r`psikoz`, r`tssb`, r`ptsd`,
    r`schizophren`, r`psychosis`, r`шизофрен`, r`психоз`, r`птср`,
    r`tecavüz`, r`taciz`, r`istismar`, r`raped?(?!\p{L})`, r`sexual assault`,
    r`molest`, r`изнасил`, r`насили`, r`teşhis`, r`diagnos`, r`диагноз`,
  ],
};

export const OUTPUT = {
  selfHarm: [
    r`kendine zarar ver(?:melisin|men gerek|meyi düşün(?:melisin|(?!\p{L}))|(?!\p{L}))`,
    r`kendini öldür(?:melisin|men gerek|(?!\p{L}))`,
    r`intihar et(?:melisin|men gerek|meyi düşün(?:melisin|(?!\p{L}))|(?!\p{L}))`,
    r`(?:canina kiy|hayatina son ver)(?:malisin|melisin|(?!\p{L}))`,
    r`(?:you should|you must|you need to|you have to|go ahead and) (?:hurt|harm|kill|cut) yourself`,
    r`(?:hurt|harm|kill|cut) yourself`,
    r`(?:end|take) your (?:own )?life`,
    r`(?:тебе стоит|тебе нужно|тебе надо|ты должен|ты должна) (?:причинить себе вред|убить себя|покончить с собой|навредить себе)`,
    r`(?:убей себя|покончи с собой|причини себе вред|навреди себе)`,
  ],
  medical: [
    r`ila[cç]\p{L}* (?:birak|kes)(?:malisin|(?!\p{L}))`,
    r`tedavi\p{L}* (?:birak|kes)(?:malisin|(?!\p{L}))`,
    r`(?:doktora|terapiye|psikiyatriste) gitme(?:ne gerek yok|(?!\p{L}))`,
    r`(?:doktora|ilaca|ilaçlara|terapiye|tedaviye) ihtiyacin yok`,
    r`stop (?:taking )?(?:your )?(?:medication|medicine|meds|pills|treatment)`,
    r`(?:don't|do not) need (?:a doctor|medication|medicine|therapy|treatment|meds)`,
    r`(?:don't|do not|never) (?:see|go to|visit) (?:a |your )?(?:doctor|therapist|psychiatrist)`,
    r`skip (?:your )?(?:medication|meds|therapy|treatment)`,
    r`avoid (?:doctors|therapy|treatment)`,
    r`(?:брось|бросьте|прекрати|перестань) (?:принимать )?(?:лекарств|таблетк|лечени)`,
    r`не ходи к врачу`,
    r`не нужен врач`,
    r`тебе не нужн[ыо] (?:лекарства|таблетки|лечение)`,
  ],
  diagnosis: [
    r`(?:şizofren|bipolar|psikoz|psikotik|depresyon|akil hastasi|ruh hastasi|tssb|ptsd|travma sonrasi stres)\p{L}* (?:olduğunu|olduğun) (?:gösteriyor|kanitliyor|doğruluyor)`,
    r`(?:şizofren|bipolar|psikotik|akil hastasi|ruh hastasi|psikozda|depresyonda)sin(?!\p{L})`,
    r`(?:tssb|ptsd|travma sonrasi stres bozukluğu)\S* (?:var|yaşiyorsun)(?!\p{L})`,
    r`(?:proves?|shows?|means?|indicates?|confirms?|suggests?) (?:that )?you (?:have|are|suffer from) (?:(?:a|an|some) )?(?:schizophreni|bipolar|psychos|psychotic|ptsd|post-?traumatic|depress|mentally ill|mental illness|adhd|autis|cancer|dementia)`,
    r`you(?: have| suffer from|'re| are) (?:(?:a|an) )?(?:schizophreni|bipolar|psychos|psychotic|ptsd|post-?traumatic|mentally ill|mental illness|dementia)`,
    r`(?:у тебя|ты страдаешь) (?:шизофрени|биполяр|психоз|птср|депресси|посттравматическ)`,
    r`ты психически (?:болен|больна)`,
  ],
  delusion: [
    r`(?:gerçekten|kesinlikle|gerçek hayatta|dış dünyada) (?:seni |sizi |sana )?(?:izliyor|izleniyorsun|takip ediyor|takip ediliyorsun|gözetliyor|mesaj gönderiyor|mesaj yolluyor|iletişim kuruyor)`,
    r`(?:seni|sizi) (?:gerçekten|kesinlikle|gizlice) (?:izliyor|takip ediyor|gözetliyor)`,
    r`(?:izlediğini|takip ettiğini|izlendiğini|mesaj gönderdiğini|iletişim kurduğunu) (?:kanitliyor|doğruluyor|gösteriyor)`,
    r`(?:is|are) (?:really|truly|definitely|actually) (?:watching|following|monitoring|tracking|spying on|communicating with|sending) you`,
    r`you(?:'re| are) (?:really |truly |definitely |actually )being (?:watched|followed|monitored|tracked)`,
    r`(?:proves?|confirms?) (?:that )?(?:someone|somebody|they|the government|the police|spirits|aliens|jinn|demons|ghosts)`,
    r`(?:действительно|на самом деле|точно) (?:следят|следит|наблюдают|общаются|посылают)`,
    r`за тобой (?:действительно|на самом деле|точно) следят`,
    r`(?:доказывает|подтверждает),? что (?:за тобой|духи|инопланетяне|правительство|джинны)`,
  ],
  traumaTerms: [
    r`istismar`, r`taciz`, r`tecavüz`, r`saldiri`, r`şiddet`, r`travma`,
    r`yaşadiklarin`, r`başina gelen`, r`abuse`, r`assault`, r`raped?(?!\p{L})`,
    r`molest`, r`trauma`, r`violence`, r`what happened to you`, r`насили`,
    r`изнасил`, r`травм`, r`надругател`, r`домогател`,
  ],
  blame: [
    r`bir (?:sebeple|nedenle)`, r`karma(?:n|nin|nda)?(?!\p{L})`, r`karmik`,
    r`hak ettin`, r`senin suçun`, r`sen sebep oldun`,
    r`kaderin(?:di|de vardi)?(?!\p{L})`, r`bir ders (?:olarak|vermek|almalisin)`,
    r`cezasi`, r`happened for a reason`, r`karmic`, r`you deserved`,
    r`your fault`, r`you caused`, r`you brought (?:it|this) on`,
    r`punishment`, r`meant to happen`, r`your destiny`, r`a lesson (?:for you|you)`,
    r`fated`, r`не случайно`, r`по какой-то причине`, r`карм(?:а|ы|ическ)`,
    r`заслужил`, r`твоя вина`, r`ты виноват`, r`наказани`, r`судьб`, r`суждено`,
    r`урок`,
  ],
  death: [
    r`öleceksin`, r`ölümün yakin`, r`yakinda öle(?:ceksin|cek)`, r`biri ölecek`,
    r`birini kaybedeceksin`, r`kaza geçireceksin`,
    r`you (?:will|are going to) die`, r`you'll die`,
    r`your death is (?:near|coming|close)`,
    r`someone (?:close to you )?(?:will|is going to) die`,
    r`ты (?:скоро )?умрешь`, r`твоя смерть близка`, r`кто-то (?:из близких )?умрет`,
  ],
};
