# ORACLY Android release R8 rules.
# Plugin AARs contribute consumer ProGuard files. Keep only Flutter embedding
# entry points that release builds require when minify is enabled.

-keep class io.flutter.embedding.** { *; }
-keep class io.flutter.plugin.** { *; }

# WorkManager opens its Room database during AndroidX Startup, before Flutter.
# Room instantiates this generated implementation reflectively by its fixed
# `<Database>_Impl` name and zero-argument constructor. Keep that exact entry
# point in minified release builds.
-keep class androidx.work.impl.WorkDatabase_Impl { public <init>(); }

# Play Core split/deferred APIs referenced by Flutter embedding but not shipped
# as a hard dependency in this app. Rules generated by R8 missing_rules.txt
# after enabling minify (assembleRelease).
-dontwarn com.google.android.play.core.splitcompat.SplitCompatApplication
-dontwarn com.google.android.play.core.splitinstall.SplitInstallException
-dontwarn com.google.android.play.core.splitinstall.SplitInstallManager
-dontwarn com.google.android.play.core.splitinstall.SplitInstallManagerFactory
-dontwarn com.google.android.play.core.splitinstall.SplitInstallRequest$Builder
-dontwarn com.google.android.play.core.splitinstall.SplitInstallRequest
-dontwarn com.google.android.play.core.splitinstall.SplitInstallSessionState
-dontwarn com.google.android.play.core.splitinstall.SplitInstallStateUpdatedListener
-dontwarn com.google.android.play.core.tasks.OnFailureListener
-dontwarn com.google.android.play.core.tasks.OnSuccessListener
-dontwarn com.google.android.play.core.tasks.Task
